In [10]:
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_colwidth', -1)
pd.set_option('display.colheader_justify', 'left')

In [11]:
cleaned_data = pd.read_csv('cleaned_data.csv', engine='python')
dirty_data = pd.read_csv('dirty_data.csv', engine='python')
submission_example = pd.read_csv('submission_example.csv')
test_data = pd.read_csv('test_data.csv')
variable_definitions = pd.read_csv('variable_definitions.csv', engine='python')

In [12]:
# Function to get clean nd dirty_data that are different
def data_diff(clean, dirty):
    ne_stacked = (clean!= dirty).stack()
    changed = ne_stacked[ne_stacked]
    changed.index.names = ['id', 'col']
    difference_locations  = np.where(clean!= dirty)
    new_dirty = dirty.values[difference_locations]
    new_clean = clean.values[difference_locations]
    return pd.DataFrame({'dirt': new_dirty, 'clean': new_clean}, index=changed.index)
#     return pd.DataFrame(new_clean, columns=changed.index, index=['clean'])

Taking into serious consideration the columns description

I am having issuses understsanding the tag numbers column

In [4]:
cleaned_data.head()

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Tag_3,Lost_Tags,T_Number,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,PCVNumber,Expenditure
0,1998_RE_0001,4/17/1998,researcher_19,site_110,creek,net,fisher_619,site_58,species_1,site_80,NotTagged_0001,None,NaN,NaN,NaN,63.50,58.42,NaN,Unknown,NaN,Released,4/17/1998,NaN,NaN,NaN,NaN
1,1998_RE_0002,7/7/1998,researcher_15,site_15,creek,longline,fisher_522,site_22,species_1,not_recorded,NotTagged_0002,None,NaN,NaN,NaN,48.26,36.83,NaN,Unknown,1B-1LLS,NaN,NaN,NaN,NaN,NaN,NaN
2,1998_RE_0003,8/3/1998,not_recorded,site_12,creek,not_recorded,fisher_1254,not_recorded,species_1,site_109,NotTagged_0003,None,NaN,NaN,NaN,44.45,33.00,NaN,Unknown,NaN,Released,8/3/1998,NaN,NaN,NaN,NaN
3,1998_RE_0004,8/7/1998,researcher_19,site_110,creek,not_recorded,fisher_360,not_recorded,species_2,site_108,NotTagged_0004,None,NaN,NaN,NaN,34.29,31.75,NaN,Unknown,There was pillings on carapace.,Released,8/7/1998,NaN,NaN,NaN,NaN
4,1998_RE_0005,9/25/1998,researcher_17,site_8,creek,collected floater,fisher_865,site_8,species_3,site_121,NotTagged_0005,None,NaN,NaN,NaN,68.58,63.50,NaN,Unknown,Bs on C+ old panga wounds,Released,9/25/1998,Found trapped in mangroves,NaN,NaN,NaN

#### size of cleaned and dirty data

In [4]:
cleaned_data.shape, dirty_data.shape

((4292, 26), (4292, 26))

#### Fill missing values with 'NOWAY'

In [13]:
dirty_data =  dirty_data.fillna('NOWAY')
cleaned_data =  cleaned_data.fillna('NOWAY')

cleaned data is seeing discrepancies with dirty_data in NA

## Analysing the data seperately

In [5]:
cleaned_data.describe(include='all')

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Tag_3,Lost_Tags,T_Number,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,PCVNumber,Expenditure
count,4292,4292,4292,4292,4292,4292,4292,4292,4292,4292,4292,4292,4292,4292,4292,4292.0,4292.0,4292,4292,4292,4292,4292,4292,4292,4292,4292
unique,4292,1953,21,74,4,11,1074,35,5,52,2773,48,1,116,3,570.0,522.0,99,5,4131,4,469,99,30,1,1
top,2005_RE_0033,12/11/2010,researcher_9,site_53,creek,net,fisher_861,site_8,species_1,site_80,KE3032,None,NOWAY,NOWAY,NOWAY,42.5,41.5,NOWAY,Unknown,NOWAY,Released,NOWAY,NOWAY,NOWAY,NOWAY,NOWAY
freq,1,20,1930,911,3193,3506,530,1696,3662,2273,24,4240,4292,4079,4290,46.0,47.0,3602,3140,37,2948,3611,4016,4223,4292,4292

In [6]:
cleaned_data.isnull().sum().sort_values()

Rescue_ID                0
SpecialRemarks           0
Release_Admiss_Notes     0
Date_Release             0
Status                   0
TurtleCharacteristics    0
Sex                      0
Weight_Kg                0
CCW_cm                   0
CCL_cm                   0
T_Number                 0
Lost_Tags                0
Tag_3                    0
Tag_2                    0
Tag_1                    0
ReleaseSite              0
Species                  0
LandingSite              0
Fisher                   0
CaptureMethod            0
ForagingGround           0
CaptureSite              0
Researcher               0
Date_Caught              0
PCVNumber                0
Expenditure              0
dtype: int64

In [7]:
dirty_data.isnull().sum().sort_values()

Rescue_ID                0
SpecialRemarks           0
Release_Admiss_Notes     0
Date_Release             0
Status                   0
TurtleCharacteristics    0
Sex                      0
Weight_Kg                0
CCW_cm                   0
CCL_cm                   0
T_Number                 0
Lost_Tags                0
Tag_3                    0
Tag_2                    0
Tag_1                    0
ReleaseSite              0
Species                  0
LandingSite              0
Fisher                   0
CaptureMethod            0
ForagingGround           0
CaptureSite              0
Researcher               0
Date_Caught              0
PCVNumber                0
Expenditure              0
dtype: int64

#### Get difference between the cleaned and dirty data

In [14]:
# get differemce between the cleaned and dirty data
diff_df = data_diff(cleaned_data, dirty_data)
# data_diff[0]

### All data in column Expenditure, PCVNumber and Tag_3  are missing

analysing data in this columns to see if it contains any useful info.  
After analysing and compaing with dirty data, i observed that this columns has no usefull info. Now resolving to move this columns from both data_set

### Deleting Expenditure, PCVNumber and Tag_3 in both cleaned and dirty data

In [15]:
cleaned_data = cleaned_data.drop(['Expenditure','PCVNumber', 'Tag_3'], axis=1)
dirty_data = dirty_data.drop(['Expenditure','PCVNumber', 'Tag_3'], axis=1)

### T_Number

T_Number has only 2 values and the rest ae missing values for both clean and data, Therefore, i believe it is irelevant

In [16]:
cleaned_data = cleaned_data.drop(['T_Number'], axis=1)
dirty_data = dirty_data.drop(['T_Number'], axis=1)

i am done with irrelevant data, now i want to investigate the cause of inputing wrong data.    

i would start by investigating the difference between the dirt and clean data in all field.

## Data Investigation

### Causes of Errorenous data in each field

Lemme start investigation columns by columns. but 1st i need to know the relevant columns in the datasets

In [12]:
len(cleaned_data.columns)

22

So there are 22 columns .  Now let me check the columns names

In [13]:
cleaned_data.columns

Index(['Rescue_ID', 'Date_Caught', 'Researcher', 'CaptureSite',
       'ForagingGround', 'CaptureMethod', 'Fisher', 'LandingSite', 'Species',
       'ReleaseSite', 'Tag_1', 'Tag_2', 'Lost_Tags', 'CCL_cm', 'CCW_cm',
       'Weight_Kg', 'Sex', 'TurtleCharacteristics', 'Status', 'Date_Release',
       'Release_Admiss_Notes', 'SpecialRemarks'],
      dtype='object')

There is no erronoeus field in Rescue_ID, and so , i would start with Date_Caught

##### Get the clean and error values for each column in a dataframe

In [17]:
# Get all clean and errorenous values for each dataframe in a column
Date_Caught = diff_df.xs('Date_Caught', level='col')
Date_Released = diff_df.xs('Date_Release', level='col')
Researcher = diff_df.xs('Researcher', level='col')
ForagingGround = diff_df.xs('ForagingGround', level='col')
Release_Admiss_Notes= diff_df.xs('Release_Admiss_Notes', level='col')
Date_Release= diff_df.xs('Date_Release', level='col')
Status= diff_df.xs('Status', level='col')
TurtleCharacteristics= diff_df.xs('TurtleCharacteristics', level='col')
Sex= diff_df.xs('Sex', level='col')
Weight_Kg= diff_df.xs('Weight_Kg', level='col')
CCW_cm= diff_df.xs('CCW_cm', level='col')
CCL_cm= diff_df.xs('CCL_cm', level='col')
Lost_Tags= diff_df.xs('Lost_Tags', level='col')
Tag_2= diff_df.xs('Tag_2', level='col')
Tag_1= diff_df.xs('Tag_1', level='col')
ReleaseSite= diff_df.xs('ReleaseSite', level='col')
Species= diff_df.xs('Species', level='col')
LandingSite= diff_df.xs('LandingSite', level='col')
Fisher= diff_df.xs('Fisher', level='col')
CaptureMethod= diff_df.xs('CaptureMethod', level='col')
CaptureSite = diff_df.xs('CaptureSite', level='col')
SpecialRemarks = diff_df.xs('SpecialRemarks', level='col')
# Tag_type = diff_df.xs('Tag_type', level='col')

In [ ]:
cleaned_data.columns

I dont know what reference point to use in checking for missing values, because i dont trust the validity of any of the values in the columns ,    
but from the look of things, lemme start with the columns that has the least amount of wrong values.

#### Check for columns with least number of wrong values

In [18]:
col_wrong_values = [Date_Caught, Researcher, CaptureSite,
       ForagingGround, CaptureMethod, Fisher, LandingSite,
       Species, ReleaseSite, Tag_1, Tag_2, Lost_Tags, CCL_cm,
       CCW_cm, Weight_Kg, Sex, TurtleCharacteristics, Status,
       Date_Release, Release_Admiss_Notes, SpecialRemarks]
col_wrong_values_2 = [ 'Date_Caught', 'Researcher', 'CaptureSite',
       'ForagingGround', 'CaptureMethod', 'Fisher', 'LandingSite', 'Species',
       'ReleaseSite', 'Tag_1', 'Tag_2', 'Lost_Tags', 'CCL_cm', 'CCW_cm',
       'Weight_Kg', 'Sex', 'TurtleCharacteristics', 'Status', 'Date_Release',
       'Release_Admiss_Notes', 'SpecialRemarks']

len_of_dirty_data = []
for col in col_wrong_values:
    len_of_dirty_data.append(len(col))

In [19]:
df_no_wong_cols = pd.DataFrame(data = {'column': col_wrong_values_2, 'num_of_dirty': len_of_dirty_data}).sort_values(by='num_of_dirty')

Tag_2 , species, Release admission_note, lost_Tag, SpecialRemarks, Tag_1 are the columns with the least amount of wrong value.

lets investifate futher

##### Tag_2

In [20]:
Tag_2
# from the variable_description, Tag_2 depends on Tag_1 to operate.
# '''
# Second tag added to large turtles. Turtles with two tags: tag 1 is an odd number e.g. 
# KEL0169 and tag 2 is even and consequent e.g. KEL0170
# '''
#therefore, for Tag_2 to be wrong, Tag_1 must be wrong
# one of the reason for wrong values is due to small_weight given to the values
# A value with Tag_2 must have a large weight or length of  at least 50cm
#from investigation again all wrong_values in Tag_1 that has a Tag_2 values, automatically,
# the tag_1 becomes wrong

     dirt     clean
id
136   W444     None
3794  KEB7505  KEB7504
4075  KE7521   KEB7521
4185  KE7534   KEB7534
4287  KE6262   none

Investigate Tag_2 in cleaned_data

In [17]:
Tag_1.loc[cleaned_data.loc[(cleaned_data.Tag_2) != 'None'].index]

C:\Users\Bless\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.

     dirt     clean
139   NaN      NaN
262   NaN      NaN
277   NaN      NaN
291   NaN      NaN
421   NaN      NaN
628   NaN      NaN
778   NaN      NaN
1275  NaN      NaN
1583  NaN      NaN
1786  NaN      NaN
1886  NaN      NaN
1893  NaN      NaN
2062  NaN      NaN
2083  NaN      NaN
2113  NaN      NaN
2127  NaN      NaN
2152  NaN      NaN
2174  NaN      NaN
2198  NaN      NaN
2249  NaN      NaN
2334  NaN      NaN
2341  NaN      NaN
2369  NaN      NaN
2587  NaN      NaN
2617  NaN      NaN
2619  NaN      NaN
2956  NaN      NaN
2992  NaN      NaN
3271  NaN      NaN
3518  NaN      NaN
3580  NaN      NaN
3583  NaN      NaN
3751  NaN      NaN
3760  NaN      NaN
3794  KEB7504  KEB7503
3859  NaN      NaN
3864  NaN      NaN
3873  NaN      NaN
4052  NaN      NaN
4075  KE7520   KEB7520
4105  NaN      NaN
4141  NaN      NaN
4149  NaN      NaN
4160  NaN      NaN
4173  NaN      NaN
4185  KE7533   KEB7533
4197  NaN      NaN
4231  NaN      NaN
4246  NaN      NaN
4267  NaN      NaN
4274  NaN      NaN
4287  KE6161   missing data

In [21]:
# check for values in Tag_2 that are in Tag_1

[x for x in set(test_data.Tag_2.values.tolist()) if x in set(cleaned_data.Lost_Tags.values.tolist())]
# no values in Tag_2 is in Cleaned Tag_1 or Lost_Tag

[]

#### Check for wrong_values in Tag_1 inorder to get wrong values in Tag_2

In [22]:
# Looked at all differnce between clean and Dirty
Tag_1.sort_values(by='dirt')

     dirt          clean
id
183   301           KE0301
3217  4879          KEB7514
3733  5549          KE5549
4054  5708          KE5708
3736  6648          KE5548
121   CC00192       KE0768
136   CC00198       KE0371
189   KE0314        KE0304
4039  KE4108        4108
4115  KE4894        4894
3802  KE5081        5081
4055  KE5397        5397
4200  KE5397        5397
4002  KE5419        5419
3764  KE5565        Missing Data
3579  KE5565        KE5675
3795  KE5577        KE7799
3818  KE5617        KE5717
3808  KE5653        KE5663
4232  KE5950        KEB7584
4182  KE5956        missing data
4261  KE5963        KE6451
4255  KE5963        KE6451
4287  KE6161        missing data
3929  KE7514        KEB7514
3958  KE7515        KEB7515
4075  KE7520        KEB7520
4185  KE7533        KEB7533
4131  KE8119        KEB8119
3794  KEB7504       KEB7503
545   KES 0838      KE0838
0     Missing data  NotTagged_0001

#### Analyse Tag_1 based on tag_type

In [23]:
# splitting the values by tag_type and its eqivalent number and assign it to a new column
cleaned_data['Tag_type'] = cleaned_data.Tag_1.str.split('(\d+)', expand=True)[0]
cleaned_data['Tag_num'] = cleaned_data.Tag_1.str.split('(\d+)', expand=True)[1]

In [24]:
# do the above for the test  data
test_data['Tag_type'] = test_data.Tag_1.str.split('(\d+)', expand=True)[0]
test_data['Tag_num'] = test_data.Tag_1.str.split('(\d+)', expand=True)[1]

After analysing clean and test, we observed some patterns in tag_1   
From this pattern, we can get our wrong values

In [22]:
cleaned_data.Tag_type.value_counts()

KE              3064
                606
NotTagged_      347
KA              106
H               54
CC              52
W               21
KEB             20
Y               19
missing data    2
Missing Data    1
Name: Tag_type, dtype: int64

In [18]:
test_data.Tag_type.value_counts()
# checking the tag_type in test and cleaned,
# we would observe that test has some wrong tag in them

KE            1261
              55
KEB           23
NotTagged_    13
KES           6
CC            2
Ke            1
kE            1
Name: Tag_type, dtype: int64

#### Check if 2 tag_types have the same tag_number

In [25]:
# Extract the numbers assigned to each Tag_1 type in a variable for clean
clean_Tag_1_no_letters = cleaned_data.loc[cleaned_data['Tag_type'] == '']['Tag_num'].tolist()
clean_Tag_1_KE = cleaned_data.loc[cleaned_data['Tag_type'] == 'KE']['Tag_num'].tolist()
clean_Tag_1_KA = cleaned_data.loc[cleaned_data['Tag_type'] == 'KA']['Tag_num'].tolist()
clean_Tag_1_H = cleaned_data.loc[cleaned_data['Tag_type'] == 'H']['Tag_num'].tolist()
clean_Tag_1_CC = cleaned_data.loc[cleaned_data['Tag_type'] == 'CC']['Tag_num'].tolist()
clean_Tag_1_W = cleaned_data.loc[cleaned_data['Tag_type'] == 'W']['Tag_num'].tolist()
clean_Tag_1_KEB = cleaned_data.loc[cleaned_data['Tag_type'] == 'KEB']['Tag_num'].tolist()
clean_Tag_1_Y = cleaned_data.loc[cleaned_data['Tag_type'] == 'Y']['Tag_num'].tolist()

In [26]:
# Do the above cell for test_data
# Extract the numbers assigned to each Tag_1 type in a variable
Tag_1_no_letters = test_data.loc[test_data['Tag_type'] == '']['Tag_num'].tolist()
Tag_1_KE = test_data.loc[test_data['Tag_type'] == 'KE']['Tag_num'].tolist()
Tag_1_KA = test_data.loc[test_data['Tag_type'] == 'KA']['Tag_num'].tolist()
Tag_1_H = test_data.loc[test_data['Tag_type'] == 'H']['Tag_num'].tolist()
Tag_1_CC = test_data.loc[test_data['Tag_type'] == 'CC']['Tag_num'].tolist()
Tag_1_W = test_data.loc[test_data['Tag_type'] == 'W']['Tag_num'].tolist()
Tag_1_KEB = test_data.loc[test_data['Tag_type'] == 'KEB']['Tag_num'].tolist()
Tag_1_Y = test_data.loc[test_data['Tag_type'] == 'Y']['Tag_num'].tolist()

In [18]:
# Checking tag_Ke and no_letters intercept in clean
[x for x in set(clean_Tag_1_KE) if x in set(clean_Tag_1_no_letters)]
# only ke and no_letters numbers intercepts
# but this looks like wrong naming from the authors of this file

['5814', '5371', '5078', '4026', '5539', '3271']

In [27]:
# Do the above for test, #tag_no_number and KEB seems clean
intercept_noletter_KE = [x for x in set(Tag_1_KE) if x in set(Tag_1_no_letters)]
intercept_KE_KEB = [x for x in set(Tag_1_KE) if x in set(Tag_1_KEB)]


## from investigation only ke and no_letters intercept; and also KEB and KE intercepts
# so i would investigate more into this interception

#### Handling Intercept_noletter_KE

In [ ]:
# Investigate this value to know which is wrong 
# cleaned_data.loc[cleaned_data['Tag_num'].isin(intecept)].sort_values(by= 'Tag_num')[['Date_Caught', 'Tag_1']]
#i observed the initial value of this was from Date of Tag_1_with_no_letter, KE only won from num 55xx
#The dirty value proved this right

#From the clean, most tag_type_1_no_letter _numbers are < 5500 
#Therefore any tag_type that intercepts with tag__no_letter, with numbers < 5500, then the tag_type is wrong 
#and, any tag_type that intercepts with tag_no_letter, with numbers > 5500, then the tag_no_letter is wrong

In [28]:
# Get prospective wrong values from the intercept of tag_noletters and KE
df_intercept_noletter_KE = test_data.loc[test_data['Tag_num'].isin(intercept_noletter_KE)].sort_values(by= 'Tag_num')

# convert TAg_number to integer
df_intercept_noletter_KE.Tag_num = df_intercept_noletter_KE.Tag_num.astype(dtype='int32')

df_wrong_Tag_1_no_leter = df_intercept_noletter_KE.loc[(df_intercept_noletter_KE['Tag_num'] > 5500) & (df_intercept_noletter_KE['Tag_type']=='')]
df_wrong_Tag_1_KE = df_intercept_noletter_KE.loc[(df_intercept_noletter_KE['Tag_num'] < 5500) & (df_intercept_noletter_KE['Tag_type']=='KE')]

In [76]:
df_intercept_noletter_KE

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Tag_3,Lost_Tags,T_Number,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,PCVNumber,Expenditure,Tag_type,Tag_num
304,2011_RE_0305,4/26/2011,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,not_recorded,3393,None,NaN,NaN,NaN,65.0,57.5,33.5,NaN,Green algae on carapace. V notch in LRF. Pinkish algae on neck.,NaN,NaN,NaN,NaN,NaN,NaN,,3393
566,2011_RE_0567,7/9/2011,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_62,KE3393,None,NaN,NaN,NaN,66.4,58.5,35.5,NaN,brown algae on rear flipper& neck and should,NaN,NaN,NaN,NaN,NaN,NaN,KE,3393
1359,2011_RE_1363,12/31/2011,researcher_22,site_38,ocean,net,fisher_360,site_118,species_2,site_73,KE3828,None,NaN,NaN,NaN,52.2,47.2,16.5,NaN,Thick layer of green algae on the carapace.A healing wound on the right shoulder.Small barnacles on the neck and shoulders.1/3 of the RRF missing.,Released,12/31/2011,NaN,NaN,NaN,NaN,KE,3828
347,2011_RE_0348,5/10/2011,researcher_4,site_111,creek,net,fisher_178,site_118,species_2,not_recorded,3828,None,NaN,NaN,NaN,50.0,44.0,14.0,NaN,Green algae on the carapace (thick). Tip of RRF missing. Small barnacles around the neck.,NaN,NaN,NaN,NaN,NaN,NaN,,3828
269,2011_RE_0270,4/13/2011,researcher_4,site_24,creek,net,fisher_530,site_118,species_2,not_recorded,KE3828,None,NaN,NaN,NaN,49.0,44.9,13.5,NaN,Green algae on carapace (thick). Tip of RRF missing.Small barnacles around the neck,NaN,NaN,NaN,NaN,NaN,NaN,KE,3828
227,2011_RE_0228,3/27/2011,researcher_4,not_recorded,creek,net,fisher_381,site_118,species_2,site_108,3828,None,NaN,NaN,NaN,49.0,44.4,NaN,NaN,green algae on carapace& notch on the eighth LMS& half of the LRF is missing& small barnacles around the shoulders.,NaN,NaN,NaN,NaN,NaN,NaN,,3828
149,2011_RE_0150,2/27/2011,researcher_22,site_58,creek,net,fisher_50,site_58,species_2,site_73,3828,None,NaN,NaN,NaN,49.2,43.6,13.5,NaN,Green algea on the carapace.calcareous algea&1/4 of the LRF is missing.A notch on the 8th marginal scute.Few barnacles on the plastron with brown algea.,NaN,NaN,NaN,NaN,NaN,NaN,,3828
467,2011_RE_0468,6/11/2011,researcher_22,site_112,creek,net,fisher_50,site_118,species_2,not_recorded,KE3828,None,NaN,NaN,NaN,50.0,45.2,14.0,NaN,Green& brown and white calcareous algae on the carapace. Brown algae on shoulders.,NaN,NaN,NaN,NaN,NaN,NaN,KE,3828
1224,2011_RE_1228,12/3/2011,researcher_4,site_38,ocean,net,fisher_2,site_118,species_2,site_62,3828,None,NaN,NaN,NaN,51.6,47.1,15.5,NaN,A healed wound on the RFF.Green algae on the carapace.Pinkish algae on the neck and on the front flippers.Almost quarter of the RRF is missing.,Released,12/3/2011,NaN,NaN,NaN,NaN,,3828
41,2011_RE_0042,1/12/2011,researcher_4,site_106,creek,net,fisher_50,site_118,species_2,site_62,3828,None,NaN,NaN,NaN,48.5,43.5,12.5,NaN,Green algea& thick towards rear shell.Notch in the 8th LMs.Part of RFF missing.Pink algea on the plastron.,NaN,NaN,NaN,NaN,NaN,NaN,,3828
883,2011_RE_0887,10/8/2011,researcher_9,site_24,creek,net,fisher_1060,site_118,species_2,site_108,KE3828,None,NaN,NaN,NaN,50.8,46.5,15.0,NaN,"white patches of calcareous algae on scute joint. A fraction of RRF missing, a small hole on LRF",Released,10/8/2011,NaN,NaN,NaN,NaN,KE,3828
383,2011_RE_0384,5/19/2011,researcher_4,site_58,creek,net,fisher_1175,site_118,species_2,not_recorded,4013,None,NaN,NaN,NaN,41.0,37.5,7.5,NaN,Thick green algae on the carapace. Numerous small barns around neck and shoulders. Both front flippeers tips missing. Green algae on the plastron.,NaN,NaN,NaN,NaN,NaN,NaN,,4013
587,2011_RE_0588,7/18/2011,researcher_4,site_41,ocean,net,fisher_652,site_118,species_2,site_80,KE4013,None,NaN,NaN,NaN,41.3,38.3,7.5,NaN,white& green calcareous algae& half of front flippers missing& white calcareous algae on carapace& small barnacles around the neck& scutes on carapace and plastron flaking,NaN,NaN,NaN,NaN,NaN,NaN,KE,4013
560,2011_RE_0561,7/7/2011,researcher_4,site_115,ocean,net,fisher_369,site_118,species_2,site_62,KE4013,None,NaN,NaN,NaN,41.8,39.0,9.5,NaN,50% of the front flippers missing& green algae with patches of whitish calcerous algae& green algae all over the plastron& small barnacles around the neck and tail,NaN,NaN,NaN,NaN,NaN,NaN,KE,4013
557,2011_RE_0558,7/5/2011,researcher_4,site_111,creek,net,fisher_1242,site_118,species_2,site_62,KE4013,None,NaN,NaN,NaN,41.2,38.8,7.5,NaN,Both front half missing.Green algea on the carapace.Patches of calcareous algea on the carapace(3rd LLs and 4th Cs)Brown algea around the neck and shoulders.Numerous barnacles on the neck.Green algea and pinkish calcareous on the plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,4013
1234,2011_RE_1238,12/4/2011,researcher_4,site_46,creek,net,fisher_583,site_118,species_2,site_62,4013,None,NaN,NaN,NaN,43.5,39.8,10.5,NaN,Green algae on the carapace.Several notches on the left marginals.Patches of whitish calcareous algae on the carapace.Pinkish algae on the neck.12th marginal scutes.Both front flippers halves are missing.,Released,12/4/2011,NaN,NaN,NaN,NaN,,4013
55,2011_RE_0056,1/16/2011,researcher_4,site_119,creek,net,fisher_1142,site_118,species_2,site_62,KE4082,None,NaN,NaN,NaN,42.1,40.5,9.5,NaN,Green algae on carapace& flipper and plastron. BS on plastron removed. white patches of calcaneous algae on carapace.,NaN,NaN,NaN,NaN,NaN,NaN,KE,4082
518,2011_RE_0519,6/27/2011,researcher_4,site_33,creek,net,fisher_890,site_118,species_2,site_62,4082,None,NaN,NaN,NaN,44.4,41.6,11.0,NaN,Green algae on the carapace.Patches of pinkish calcareous algae .Right side of the 5th Cs is slightly broken.Brown algea on the neck.Barnacles and green algea on the plastron.,NaN,NaN,NaN,NaN,NaN,NaN,,4082
219,2011_RE_0220,3/26/2011,researcher_4,site_41,creek,net,fisher_957,site_118,species_2,site_62,4082,None,NaN,NaN,NaN,43.0,41.0,10.0,NaN,Green algea on the carapace.Brown algea on the shoulders.Several barnacles on the carapace.,NaN,NaN,NaN,NaN,NaN,NaN,,4082
891,2011_RE_0895,10/8/2011,researcher_9,site_45,ocean,net,fisher_957,site_118,species_2,site_108,KE5376,None,NaN,NaN,NaN,42.7,40.6,10.0,NaN,"2 small ntches in the 11th RMS, outer of LRF is jagged",Released,10/8/2011,NaN,NaN,NaN,NaN,KE,5376
817,2011_RE_0821,9/25/2011,researcher_4,site_46,ocean,net,fisher_50,site_118,species_2,site_108,KE5376,None,NaN,NaN,NaN,43.5,40.3,10.5,NaN,a V- ntch on LRF flaking on plastron,NaN,NaN,NaN,NaN,NaN,NaN,KE,5376
804,2011_RE_0808,9/23/2011,researcher_4,site_41,ocean,net,fisher_718,site_118,species_2,site_62,KE5376,None,NaN,NaN,NaN,42.9,40.2,10.5,NaN,part of the tip of the left rear flipper missing; notch between the 9th and 10th right marginal scute; dead barnacle wounds on the right inframarginal; green algae on te plastron; dead barnacle wounds on the right and left abdominal scutes; notch on the 5,NaN,NaN,NaN,NaN,NaN,NaN,KE,5376
1055,2011_RE_1059,11/4/2011,researcher_4,site_46,creek,net,fisher_570,site_118,species_2,site_62,KE5376,None,NaN,NaN,NaN,43.1,41.6,10.5,NaN,"Thick green algae on the carapace,chunk missing out on both rear flippers.Flaking,few small barnacle wounds,and thin green algae on the carapace",Released,11/4/2011,NaN,NaN,NaN,NaN,KE,5376
695,2011_RE_0697,8/22/2011,researcher_4,site_24,creek,net,fisher_530,site_118,species_2,site_80,KE5376,None,NaN,NaN,NaN,42.7,40.9,10.5,NaN,Flaking between 2nd and3rd central scutes& green algae on the,NaN,NaN,NaN,NaN,NaN,NaN,KE,5376
497,2011_RE_0498,6/24/2011,researcher_22,site_46,creek,net,fisher_1142,site_118,species_2,site_62,KE5376,None,NaN,NaN,NaN,43.1,39.9,10.0,NaN,Green algae on carapace. Notches between 10th and 11th RMS. Clean plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5376
410,2011_RE_0411,5/26/2011,researcher_4,site_41,creek,net,fisher_583,site_118,species_2,not_recorded,KE5376,None,NaN,NaN,NaN,42.1,40.5,NaN,NaN,Green on the carapace. Clean plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5376
35,2011_RE_0036,1/11/2011,researcher_4,site_46,creek,net,fisher_1142,site_118,species_2,site_62,5376,None,NaN,NaN,NaN,41.8,39.8,9.5,NaN,Thick green algea.Patch of pinkish calcareous algea on he second Cs.Barnacles on the LFF.Pinkish alga on the neck.,NaN,NaN,NaN,NaN,NaN,NaN,,5376
262,2011_RE_0263,4/12/2011,researcher_4,site_41,creek,net,fisher_957,site_118,species_2,not_recorded,KE5376,None,NaN,NaN,NaN,42.7,40.4,8.5,NaN,Green algae on carapace thicker towards rear. White patches of calcareous algae and green algae on plastron. Barnacles(small) on plastron,NaN,NaN,NaN,NaN,NaN,NaN,KE,5376
276,2011_RE_0277,4/15/2011,researcher_4,site_115,creek,net,fisher_1142,site_118,species_2,not_recorded,KE5376,None,NaN,NaN,NaN,42.7,40.3,9.0,NaN,Green algae on shell.Barnacles (small) on carapace. Flaking on plastron. Green algae on plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5376
1271,2011_RE_1275,12/10/2011,researcher_22,site_41,ocean,net,fisher_957,site_118,species_2,site_80,KE5379,None,NaN,NaN,NaN,42.5,37.9,10.0,NaN,"green and whitec patches of calcareous algae on carapace, plastron full of green & brown algae",Released,12/10/2011,NaN,NaN,NaN,NaN,KE,5379
206,2011_RE_0207,3/19/2011,researcher_4,site_65,creek,net,fisher_957,site_118,species_2,site_62,5379,None,NaN,NaN,NaN,40.7,36.4,7.5,NaN,Green algae on the carapace and plasron. White patches of calcareous algae on the carapace. Notch on the 8th marginal scute. Small B's around the neck.,NaN,NaN,NaN,NaN,NaN,NaN,,5379
281,2011_RE_0282,4/17/2011,researcher_4,site_115,creek,net,fisher_957,site_118,species_2,not_recorded,KE5379,None,NaN,NaN,NaN,40.7,36.8,8.0,NaN,Green algae on the shell. Flaking tips of scutes. Small notch in the 8th LMS. Healed barnacle wounds on plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5379
596,2011_RE_0597,7/20/2011,researcher_4,site_46,ocean,net,fisher_369,site_118,species_2,site_62,KE5379,None,NaN,NaN,NaN,41.7,36.6,8.0,NaN,scutes flaking on carapace& green algae on carapace& notch on the left marginal 8th& between 9&10& few barnacles around neck& pink and green algae on plastron& flaking abdominal left& barnacles wound on right phemeral and anal,NaN,NaN,NaN,NaN,NaN,NaN,KE,5379
367,2011_RE_0368,5/13/2011,researcher_9,site_41,creek,net,fisher_381,site_118,species_2,not_recorded,KE5630,None,NaN,NaN,NaN,40.4,36.0,NaN,NaN,Light green algae on the carapace. Few small barns on soft body.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5630
274,2011_RE_0275,4/14/2011,researcher_4,site_46,creek,net,fisher_1142,site_118,species_2,not_recorded,KE5630,None,NaN,NaN,NaN,41.3,36.0,7.5,NaN,Green algae on carapace and flippers and plastron.4,NaN,NaN,NaN,NaN,NaN,NaN,KE,5630
506,2011_RE_0507,6/25/2011,researcher_22,site_115,ocean,net,fisher_957,site_62,species_2,not_recorded,KE5630,None,NaN,NaN,NaN,41.0,36.1,NaN,NaN,Green and brown algae on carapace.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5630
502,2011_RE_0503,6/24/2011,researcher_22,site_61,ocean,net,fisher_381,site_118,species_2,site_62,KE5630,None,NaN,NaN,NaN,41.2,36.1,7.0,NaN,Patches of green algae on the rearshell and the supra. White patches of algae on the carapace.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5630
612,2011_RE_0613,7/26/2011,researcher_4,site_38,ocean,net,fisher_43,site_118,species_2,site_62,KE5630,None,NaN,NaN,NaN,41.5,36.2,7.5,NaN,few small barnacles on plastron&calcareos algae on plastron&green algae on plastron&thick green algea on rear carapace& large flake on 3rd right lateral scutes& u- notch between 1st and2nd inner scales of lFF,NaN,NaN,NaN,NaN,NaN,NaN,KE,5630
664,2011_RE_0666,8/10/2011,researcher_4,site_38,ocean,net,fisher_1031,site_118,species_2,site_62,5630,None,NaN,NaN,NaN,41.3,36.0,8.5,NaN,thick green algae on rear carapace& flaking on 1st central scute& notch on LFF& green algae on carapace& tag rip on LRF& notch between 10th&11th marginal scutes slightly broken,NaN,NaN,NaN,NaN,NaN,NaN,,5630
421,2011_RE_0422,5/26/2011,researcher_4,site_41,creek,net,fisher_381,site_118,species_2,not_recorded,KE5630,None,NaN,NaN,NaN,41.2,36.2,7.5,NaN,Patches of green algae on the lower parts of the carapace and supra.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5630
1304,2011_RE_1308,12/18/2011,researcher_4,site_38,ocean,net,fisher_1142,site_118,species_2,site_62,KE5630,None,NaN,NaN,NaN,43.5,37.1,8.0,NaN,Flaking scutes.Green algae on the carapace and patches of whitish calcareous algae on the carapace and plastron.,Released,12/18/2011,NaN,NaN,NaN,NaN,KE,5630
1310,2011_RE_1314,12/19/2011,researcher_4,site_115,ocean,net,fisher_1198,site_118,species_2,site_62,KE5630,None,NaN,NaN,NaN,43.2,37.4,8.0,NaN,Few patches of pink calcareous algae on the carapace.Green algae on the plastron.Notch in the inner scale of the LFF.,Released,12/19/2011,NaN,NaN,NaN,NaN,KE,5630
470,2011_RE_0471,6/12/2011,researcher_4,site_38,ocean,net,fisher_62,site_118,species_2,not_recorded,KE5630,None,NaN,NaN,NaN,41.5,36.0,7.5,NaN,Green algae on rear shell. Pinkish calcareous algae on plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5630
863,2011_RE_0867,10/5/2011,researcher_4,site_24,creek,net,fisher_1047,site_118,species_2,site_1,KE5630,None,NaN,NaN,NaN,41.5,36.5,7.5,NaN,"few barnacles on flippers, white calcreous algae on plastron, flakings on LFF",Released,10/5/2011,NaN,NaN,NaN,NaN,KE,5630
147,2011_RE_0148,2/27/2011,researcher_22,site_41,creek,net,fisher_957,site_118,species_2,site_73,KE5630,None,NaN,NaN,NaN,40.5,35.8,6.0,NaN,White calcareous algea&green and brown on the carapace.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5630
146,2011_RE_0147,2/26/2011,researcher_9,site_119,creek,net,fisher_652,site_118,species_2,site_62,KE5630,None,NaN,NaN,NaN,40.1,35.7,5.5,NaN,Lots of green algea on the carapace.Brown algea on the rear shell.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5630
934,2011_RE_0938,10/21/2011,researcher_4,site_41,ocean,net,fisher_911,site_118,species_2,site_62,kE5630,None,NaN,NaN,NaN,42.2,36.5,8.5,NaN,"thick green algae at rear of carapace, 3rd right lateral scutes is broken,tip of RFF missing.",Released,10/21/2011,NaN,NaN,NaN,NaN,kE,5630
553,2011_RE_0554,7/5/2011,researcher_4,site_41,creek,net,fisher_1047,site_118,species_2,site_62,KE5630,None,NaN,NaN,NaN,41.1,36.1,6.5,NaN,green algae on the carapace&flake on 3rd right lateral scute& pinkish calcareous on plastron& thin green algae on plastron,NaN,NaN,NaN,NaN,NaN,NaN,KE,5630
45,2011_RE_0046,1/13/2011,researcher_4,site_41,creek,net,fisher_369,site_118,species_2,site_62,KE5630,None,NaN,NaN,NaN,40.2,34.6,6.5,NaN,Green algea on the carapace&flippers&and around the neck.Patches of calcareous algea on the shell.Green algea on the plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5630
24,2011_RE_0025,1/6/2011,researcher_4,site_123,ocean,net,fisher_162,site_118,species_1,site_108,KE5867,None,NaN,NaN,NaN,33.5,33.1,4.0,NaN,G reen algae. Small notch between 5th and 6th RMS. Pinkish algae around neck and shoulders.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5867
244,2011_RE_0245,4/5/2011,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,not_recorded,5867,None,NaN,NaN,NaN,33.5,33.1,6.0,NaN,sent to rehab- died 6/4/2011,NaN,NaN,NaN,NaN,NaN,NaN,,5867
63,2011_RE_0064,1/20/2011,researcher_4,site_41,ocean,net,fisher_749,site_118,species_1,not_recorded,KE5867,None,NaN,NaN,NaN,33.3,33.0,4.0,NaN,Green algae. Small notch between 5th and 6th rt marginal scute. Pinkish algae around neck and shoulders. Generalized weakness. Sent to rehab,NaN,NaN,sent to rehab,NaN,NaN,NaN,KE,5867
1242,2011_RE_1246,12/5/2011,researcher_4,site_32,creek,longline,fisher_596,site_58,species_1,site_80,KE5968,None,NaN,NaN,NaN,47.8,44.6,12.0,NaN,"Few small barnacles on the carapace.Thin green algae on the carapace.Small notches in the 10th and 11th LMS and the 11th and the left supra.Minor flakings on the plastron,but general clean.",Released,12/5/2011,NaN,NaN,NaN,NaN,KE,5968
175,2011_RE_0176,3/10/2011,researcher_4,site_12,creek,net,fisher_732,site_110,species_1,site_80,KE5968,None,NaN,NaN,NaN,45.0,42.2,10.5,NaN,Thin green algea on the carapace.Plastron beginning to flake.Small notch between 10th and 11th LMs.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5968
671,2011_RE_0673,8/14/2011,researcher_4,site_111,creek,net,fisher_595,site_58,species_1,site_80,5968,None,NaN,NaN,NaN,47.0,43.4,12.5,NaN,thin green algae on the carapace& cluster of small barnacles on the 3rd central scute(removed) and on the plastron&notch in between 10th &11th left marginal scute& hooked on the right side of the upper beak(small injury of~1/2 cm& minor flakings on the pl,NaN,NaN,NaN,NaN,NaN,NaN,,5968

#### Handling Intercept_KE_KEB

#From the clean, most tag_type_1_KE numbers are < 7500
#Therefore any tag_type that intercepts with tag_KE, with numbers < 7500, then the tag_type is wrong
#and, any tag_type that intercepts with tag_KE, with numbers > 7500, then  tag_KE is wrong

Get the df of wrong values

In [20]:
# Get dataframe of the intercept KE and KEB
df_intercept_KE_KEB = test_data.loc[test_data['Tag_num'].isin(intercept_KE_KEB)].sort_values(by= 'Tag_num')
# convert TAg_number to integer
df_intercept_KE_KEB.Tag_num = df_intercept_KE_KEB.Tag_num.astype(dtype='int32')
#Values greater than 7500 in KE
df_wrong_Tag_1_KEB_KE = df_intercept_KE_KEB.loc[(df_intercept_KE_KEB['Tag_num'] > 7500) & (df_intercept_KE_KEB['Tag_type']=='KE')]
#Values less than 7500 in KEB
df_wrong_Tag_1_KE_KEB =df_intercept_KE_KEB.loc[(df_intercept_KE_KEB['Tag_num'] <7500) & (df_intercept_KE_KEB['Tag_type']=='KEB')]

##### Looking  in Tag_1_KE fully

since it is obeserved that KE and no_letter likes to intercept,   
check for test KE that intercepts in clean_no_letter

#### Check for values in test Tag_1_KE that intercepts with Clean Tag_1_no_letter

In [21]:
intercept_test_KE_clean_noLetters = [x for x in set(Tag_1_KE)if x in set(clean_Tag_1_no_letters)]

In [22]:
df_intercept_KE_2 = test_data.loc[test_data['Tag_num'].isin(intercept_test_KE_clean_noLetters)].sort_values(by= 'Tag_num')

#get the suspected wrong value in a dataframe
df_wrong_Tag_1_KE_clean_noLetters =df_intercept_KE_2.loc[(df_intercept_KE_2['Tag_type']=='KE')]

### Check for values in test Tag_1_KEB that intercepts with Clean Tag_1_KE

In [23]:
intercept_test_KE_clean_KEB = [x for x in set(Tag_1_KE)if x in set(clean_Tag_1_KEB)]

In [24]:
df_intercept_KE_3 = test_data.loc[test_data['Tag_num'].isin(intercept_test_KE_clean_KEB)].sort_values(by= 'Tag_num')
#get the suspected wrong value in a dataframe
df_wrong_Tag_1_KE_clean_KEB = df_intercept_KE_3.loc[(df_intercept_KE_3['Tag_type']=='KE')]
# df_intercept_KE_3

### Tag_1 with more than one species

I need to check if a particular Tag_1 has more than one species

In [25]:
# fuction to get data frame with more than one species
def plenty_species(df):
    # Get a dataframe of Tag_1 and species, grouped by Tag_1
    df_Tag_1_Species = df.groupby('Tag_1')['Species'].apply(lambda x: x.unique()).to_frame().reset_index()
    #check the unique values of each species
    #Locate values that contain more than one Species, 
    df_Tag_1_Species.Species = df_Tag_1_Species.Species.astype('str')
#     df_Tag_1_Species.Species.value_counts()
#     df_Tag_1_Species.loc[df_Tag_1_Species['Species'].isin(["['species_1' 'species_2']", "['species_2' 'species_1']"])]

    # Get Tag_1 with more than one Species in a dataframe
    Tag_1_more_than_1_Species =  df_Tag_1_Species.loc[df_Tag_1_Species['Species'].isin(["['species_1' 'species_2']", "['species_2' 'species_1']"])]
    Tag_1_more_than_1_Species = Tag_1_more_than_1_Species.Tag_1.tolist()
    return Tag_1_more_than_1_Species

In [34]:
# Tag_1 in cleaned_data with multiple species
plenty_species(cleaned_data)

['KE1814', 'KE5770']

In [35]:
# Tag_1 in test_data with multiple species
plenty_species(test_data)

['KE5818',
 'KE6037',
 'KE6089',
 'KE6149',
 'KE6223',
 'KE6250',
 'KE6388',
 'KE6442',
 'KE6474',
 'KE6578']

#### Check if any of this Tag_1 with multispecies is in clean data

In [26]:
cleaned_data.loc[cleaned_data.Tag_1.isin(plenty_species(test_data))].sort_values(by ='Tag_1')
# from the tag_1 it can be seen that 5818 is in the cleaned_data and they all belong to species_2
#check for 5818 value in the test data with a different Species
#check for which rows contains a different weight, L, W range

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Lost_Tags,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,Tag_type,Tag_num
3994,2010_RE_0840,10/18/2010,researcher_4,site_58,creek,net,fisher_891,site_118,species_2,site_62,KE5818,None,NOWAY,34.2,32.5,4.5,NOWAY,Green algae and patches of white calcareous algae on the carapace& thin green algae on the plastron with minor flaking,NOWAY,NOWAY,NOWAY,NOWAY,KE,5818
4142,2010_RE_0991,11/28/2010,researcher_4,site_38,ocean,net,fisher_292,site_118,species_2,site_62,KE5818,None,NOWAY,35,33.1,5.5,NOWAY,Green thick algea towards the rear shell.Black complexion under neath the rear flippers.,NOWAY,NOWAY,NOWAY,NOWAY,KE,5818

In [27]:
# Get Tag_1 in test that is the species is not 'Species_2'
multi_species = test_data.loc[test_data.Tag_1.isin(plenty_species(test_data))].sort_values(by ='Tag_1')
multi_species.loc[multi_species.Tag_1.isin(['KE5818']) & (multi_species.Species != 'species_2')]

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Tag_3,Lost_Tags,T_Number,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,PCVNumber,Expenditure,Tag_type,Tag_num
211,2011_RE_0212,3/23/2011,researcher_4,site_53,creek,net,fisher_861,site_8,species_1,site_80,KE5818,None,NaN,NaN,NaN,43.0,39.0,10.0,NaN,Numerous small barnacles on the carapace.Flaking on the 2nd and 5th Cs.Right supra is broken.Clean plastron.Tag ripin the left rear flipper.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5818

In [28]:
#check for statistical characteristics of prospective values in both cleaned and test
cl_58 = cleaned_data.loc[cleaned_data.Tag_1.isin(plenty_species(test_data))].sort_values(by ='Tag_1')
tst_58 = multi_species.loc[multi_species.Tag_1.isin(['KE5818'])]
(pd.concat([cl_58 , tst_58], sort=False)['Weight_Kg'])- pd.concat([cl_58 , tst_58], sort=False)['Weight_Kg'].std()

3994    2.03779
4142    3.03779
176     3.03779
211     7.53779
Name: Weight_Kg, dtype: object

#### Get the df of the tag_1 with a different species value from the one in the cleaned_data

In [29]:
# assign this discrepencies in 5818 to a wrong df
df_wrong_tag_1_multi_species = multi_species.loc[multi_species.Tag_1.isin(['KE5818']) & (multi_species.Species != 'species_2')]

#### Find multi-species with more than two examples

###### In species with more than 2 Species,  
###### if the sizes(weight, ccm_L, ccm_W) are in the same range following valid date , then the wrong value is from the less occuring species, elses the wrong value is from the tag_1 whose size is far away from the normal range of size in the tag(weight, ccm_L, ccm_W).

##### work on this algorithm again so that it can generalise

In [88]:
# From multispecies with more than 2 species, i can get the most occuring species
# and pick the species with less occurance as a wrong value
# multi_species with more than 2 examples.
df_2_species_count = (multi_species.Tag_1.value_counts() > 2).reset_index()
species_more_than_2 = df_2_species_count.loc[df_2_species_count.Tag_1 == True]['index'].tolist()

In [39]:
species_more_than_2

['KE6388', 'KE6474', 'KE6089', 'KE6149']

In [89]:
# get the dataframe of this values
test_data.loc[test_data.Tag_1.isin([species_more_than_2[0]])].sort_values(by='Tag_num')
# .Weight_Kg.mean() -(test_data.loc[test_data.Tag_1.isin([species_more_than_2[0]])].sort_values(by='Tag_num').Weight_Kg)
# its obseved that all data_weight are normal and as such, the wrong value is from the species

df_wrong_species_multispecies = test_data.loc[(test_data.Species != 'species_1') & (test_data.Tag_1 == species_more_than_2[0])]
# for each Tag_1 in  multi_species with more than 2, get size that is far away from the normal

In [90]:
# get the dataframe of this values
test_data.loc[test_data.Tag_1.isin([species_more_than_2[1]])].sort_values(by='Tag_num')
# .Weight_Kg.mean() - (test_data.loc[test_data.Tag_1.isin([species_more_than_2[1]])].sort_values(by='Tag_num').Weight_Kg)
# its obseved that all data_weight are normal and as such, the wrong value is from the species

df_wrong_species_multispecies = pd.concat([df_wrong_species_multispecies,test_data.loc[(test_data.Species != 'species_1') & (test_data.Tag_1 == species_more_than_2[1])]]) 
# for each Tag_1 in  multi_species with more than 2, get size that is far away from the normal
# df_wrong_tag_1_multi_species = pd.concat([df_wrong_tag_1_multi_species, test_data.loc[(test_data.Species != 'species_2') & (test_data.Tag_1 == species_more_than_2[1])]])
# Tag_1 should be wrong

In [91]:
# get the dataframe of this values
test_data.loc[test_data.Tag_1.isin([species_more_than_2[2]])].sort_values(by='Tag_num')
# .Weight_Kg.median()- (test_data.loc[test_data.Tag_1.isin([species_more_than_2[2]])].sort_values(by='Tag_num').Weight_Kg)
# its observed that all data_weight are not normal and as suh, wrong value is from Tag_1

# df_wrong_tag_1_multi_species = 
# for each Tag_1 in  multi_species with more than 2, get size that is far away from the normal
# df_wrong_tag_1_multi_species = pd.concat([df_wrong_tag_1_multi_species, test_data.loc[(test_data.Species = 'species_2') & (test_data.Tag_1 == species_more_than_2[2])]])
df_wrong_species_multispecies = pd.concat([df_wrong_species_multispecies,test_data.loc[(test_data.Species != 'species_2') & (test_data.Tag_1 == species_more_than_2[2])]])

In [92]:
# get the dataframe of this values
test_data.loc[test_data.Tag_1.isin([species_more_than_2[3]])].sort_values(by='Tag_num')
# .Weight_Kg.median()- (test_data.loc[test_data.Tag_1.isin([species_more_than_2[3]])].sort_values(by='Tag_num').Weight_Kg)
# its observed that all data_weight are not normal and as such, wrong value is from Tag_1


# df_wrong_Tag_1_multi_species = pd.concat([df_wrong_Tag_1_multi_species, df_wrong_tag_1_multi_species])                                        
# for each Tag_1 in  multi_species with more than 2, get size that is far away from the normal
df_wrong_species_multispecies = pd.concat([df_wrong_species_multispecies,test_data.loc[(test_data.Species != 'species_2') & (test_data.Tag_1 == species_more_than_2[3])]])

In [93]:
df_wrong_species_multispecies

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Tag_3,Lost_Tags,T_Number,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,PCVNumber,Expenditure,Tag_type,Tag_num
831,2011_RE_0835,9/30/2011,researcher_9,site_28,ocean,net,fisher_420,site_13,species_2,site_108,KE6388,None,NaN,NaN,NaN,34.6,33.0,4.5,NaN,"green algae on the carapace and plastron, patches of calcareous algae on the carapace.",Released,9/30/2011,NaN,NaN,NaN,NaN,KE,6388
866,2011_RE_0870,10/5/2011,researcher_4,site_24,creek,net,fisher_1047,site_118,species_2,site_1,KE6388,None,NaN,NaN,NaN,34.6,33.0,4.5,NaN,thin green algae on plastron and carapace.,Released,10/5/2011,NaN,NaN,NaN,NaN,KE,6388
617,2011_RE_0618,7/27/2011,researcher_4,site_38,ocean,net,fisher_360,site_118,species_2,site_73,KE6149,None,NaN,NaN,NaN,47.5,46.5,15.0,NaN,Shallow notch on left rear flipper& right supra slightly broken. Clean plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,6149
239,2011_RE_0240,4/2/2011,researcher_4,site_23,ocean,net,fisher_656,site_23,species_1,not_recorded,KE6089,None,NaN,NaN,NaN,36.3,34.5,6.0,NaN,few flakes on carapac& notch in 3rd central scute& barnacle on plastron,NaN,NaN,taken to rehab,NaN,NaN,NaN,KE,6089
466,2011_RE_0467,6/11/2011,researcher_22,site_115,creek,net,fisher_957,site_118,species_1,not_recorded,KE6089,None,NaN,NaN,NaN,37.0,35.3,6.5,NaN,White calcareous and grey algae on carapace. A bruise in the 5th marginal scute.,NaN,NaN,NaN,NaN,NaN,NaN,KE,6089
876,2011_RE_0880,10/7/2011,researcher_22,site_33,creek,net,fisher_930,site_58,species_1,site_108,KE6474,None,NaN,NaN,NaN,45.5,41.8,11.0,NaN,"net bruising & blood on LFF, few barnacles on carapace, tag rip on left supra caudal scutes, a hard slightly protruding scar tissue on LFF.",Released,10/7/2011,NaN,NaN,NaN,NaN,KE,6474

In [94]:
df_wrong_tag_1_multi_species

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Tag_3,Lost_Tags,T_Number,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,PCVNumber,Expenditure,Tag_type,Tag_num
211,2011_RE_0212,3/23/2011,researcher_4,site_53,creek,net,fisher_861,site_8,species_1,site_80,KE5818,None,NaN,NaN,NaN,43.0,39.0,10.0,NaN,Numerous small barnacles on the carapace.Flaking on the 2nd and 5th Cs.Right supra is broken.Clean plastron.Tag ripin the left rear flipper.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5818

### Find multi species with just 2 examples

In [95]:
# multi_species with more than 2 examples.
df_1_species_count = (multi_species.Tag_1.value_counts() == 2).reset_index()
species_equal_2 = df_1_species_count.loc[df_1_species_count.Tag_1 == True]['index'].tolist()
df_1_species_count = test_data.loc[test_data.Tag_1.isin(species_equal_2)].sort_values(by= 'Tag_1')

In [96]:
# Turn the date_time value to pandas date time
df_1_species_count.Date_Caught = pd.to_datetime(df_1_species_count.Date_Caught)
df_1_species_count.Date_Caught

176    2011-03-10
211    2011-03-23
133    2011-02-18
1136   2011-11-20
543    2011-07-03
859    2011-10-05
597    2011-07-21
615    2011-07-26
591    2011-07-18
943    2011-10-21
1278   2011-12-13
1357   2011-12-31
Name: Date_Caught, dtype: datetime64[ns]

In [ ]:
df_1_species_count

In [97]:
# i need to go through th whole row and chek if 2 rows has same value for Tag_1
# if they are equal i should, check for date_caught that is most recent
# put this most recent_datecaught in a dataframe
# intuition behind is due to the fact that a tag_1 has already been given, before giving this new date Tag

list_wrong_Tag_1_based_n_Date = []
values_2_Tag_1 = set(df_1_species_count.Tag_1.values.tolist())
for i in values_2_Tag_1:
     list_wrong_Tag_1_based_n_Date.append(df_1_species_count.loc[df_1_species_count.Tag_1.isin([i])]['Date_Caught'].max())
# Get the suspected wrong_valued in a Dataframe        
df_wrong_Tag_1_basedon_Date = df_1_species_count.loc[df_1_species_count.Date_Caught.isin(list_wrong_Tag_1_based_n_Date)]

In [47]:
df_wrong_Tag_1_basedon_Date

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Tag_3,Lost_Tags,T_Number,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,PCVNumber,Expenditure,Tag_type,Tag_num
211,2011_RE_0212,2011-03-23,researcher_4,site_53,creek,net,fisher_861,site_8,species_1,site_80,KE5818,None,NaN,NaN,NaN,43.0,39.0,10.0,NaN,Numerous small barnacles on the carapace.Flaking on the 2nd and 5th Cs.Right supra is broken.Clean plastron.Tag ripin the left rear flipper.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5818
1136,2011_RE_1140,2011-11-20,researcher_4,site_38,ocean,net,fisher_292,site_118,species_2,site_62,KE6037,None,NaN,NaN,NaN,36.5,34.6,5.5,NaN,Few barnacles and thin green algea on the plastron.,Released,11/20/2011,NaN,NaN,NaN,NaN,KE,6037
859,2011_RE_0863,2011-10-05,researcher_4,site_41,ocean,net,fisher_490,site_118,species_2,site_1,KE6223,None,NaN,NaN,NaN,32.2,29.2,3.5,NaN,"tag rip but tag still on,white calcareous algae on carapace.",Released,10/5/2011,NaN,NaN,NaN,NaN,KE,6223
615,2011_RE_0616,2011-07-26,researcher_4,site_41,ocean,net,fisher_791,site_118,species_2,site_62,KE6250,None,NaN,NaN,NaN,30.7,29.0,4.0,NaN,thick green algae on carapace&green algae on plastron,NaN,NaN,NaN,NaN,NaN,NaN,KE,6250
943,2011_RE_0947,2011-10-21,researcher_22,site_53,creek,net,fisher_637,site_8,species_1,site_62,KE6442,None,NaN,NaN,NaN,50.5,45.7,14.0,NaN,tag rip on the lrf,Released,10/21/2011,NaN,NaN,NaN,NaN,KE,6442
1357,2011_RE_1361,2011-12-31,researcher_22,site_120,ocean,net,fisher_141,site_118,species_1,site_73,KE6578,None,NaN,NaN,NaN,45.1,33.1,13.0,NaN,Tiny barnacles on neck and shoulders.,Released,12/31/2011,NaN,NaN,NaN,NaN,KE,6578

In [26]:
Date_Caught.dirt = pd.to_datetime(Date_Caught.dirt)
Date_Caught.clean = pd.to_datetime(Date_Caught.clean)

C:\Users\Bless\Anaconda3\lib\site-packages\pandas\core\generic.py:4405: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value

In [ ]:
# you can see that index 211 has a wrong Tag, since the dimesions and weighs are not the same with the rest and as such, i 
# give the df for this value

In [98]:
test_data.loc[test_data.Tag_1.isin(plenty_species(test_data))].sort_values(by ='Tag_1')

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Tag_3,Lost_Tags,T_Number,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,PCVNumber,Expenditure,Tag_type,Tag_num
176,2011_RE_0177,3/10/2011,researcher_4,site_38,ocean,net,fisher_530,site_118,species_2,site_62,KE5818,None,NaN,NaN,NaN,36.8,36.0,5.5,NaN,Green algea with patches of pinkish/whitish calcareous algea on the carapace.Smallbarnacles around shoulders andrear flippers and around the tail.pinkish algae on the plastron.Dark complexion on flippers and head.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5818
211,2011_RE_0212,3/23/2011,researcher_4,site_53,creek,net,fisher_861,site_8,species_1,site_80,KE5818,None,NaN,NaN,NaN,43.0,39.0,10.0,NaN,Numerous small barnacles on the carapace.Flaking on the 2nd and 5th Cs.Right supra is broken.Clean plastron.Tag ripin the left rear flipper.,NaN,NaN,NaN,NaN,NaN,NaN,KE,5818
133,2011_RE_0134,2/18/2011,researcher_22,site_33,creek,net,fisher_489,site_12,species_1,site_73,KE6037,None,NaN,NaN,NaN,58.3,54.3,22.5,NaN,White calcareous algae on plastron. Notch on 10th and 11th marginal scutes. Few BS on neck and flippers. Tag rip on LRF.,NaN,NaN,NaN,NaN,NaN,NaN,KE,6037
1136,2011_RE_1140,11/20/2011,researcher_4,site_38,ocean,net,fisher_292,site_118,species_2,site_62,KE6037,None,NaN,NaN,NaN,36.5,34.6,5.5,NaN,Few barnacles and thin green algea on the plastron.,Released,11/20/2011,NaN,NaN,NaN,NaN,KE,6037
239,2011_RE_0240,4/2/2011,researcher_4,site_23,ocean,net,fisher_656,site_23,species_1,not_recorded,KE6089,None,NaN,NaN,NaN,36.3,34.5,6.0,NaN,few flakes on carapac& notch in 3rd central scute& barnacle on plastron,NaN,NaN,taken to rehab,NaN,NaN,NaN,KE,6089
890,2011_RE_0894,10/8/2011,researcher_9,site_115,ocean,net,fisher_734,site_118,species_2,site_108,KE6089,None,NaN,NaN,NaN,38.0,36.1,7.0,NaN,no major characterstics,Released,10/8/2011,NaN,NaN,NaN,NaN,KE,6089
466,2011_RE_0467,6/11/2011,researcher_22,site_115,creek,net,fisher_957,site_118,species_1,not_recorded,KE6089,None,NaN,NaN,NaN,37.0,35.3,6.5,NaN,White calcareous and grey algae on carapace. A bruise in the 5th marginal scute.,NaN,NaN,NaN,NaN,NaN,NaN,KE,6089
617,2011_RE_0618,7/27/2011,researcher_4,site_38,ocean,net,fisher_360,site_118,species_2,site_73,KE6149,None,NaN,NaN,NaN,47.5,46.5,15.0,NaN,Shallow notch on left rear flipper& right supra slightly broken. Clean plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,6149
404,2011_RE_0405,5/25/2011,researcher_4,site_41,creek,net,fisher_583,site_118,species_1,not_recorded,KE6149,None,NaN,NaN,NaN,46.6,44.7,13.5,NaN,White calcareous algae on the carapace. Clean plastron. Healthy turtle.,NaN,NaN,NaN,NaN,NaN,NaN,KE,6149
356,2011_RE_0357,5/11/2011,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,not_recorded,KE6149,None,NaN,NaN,NaN,46.2,45.1,14.0,NaN,Green algae on carapace. Shallow U-notch in the LRF.,NaN,NaN,NaN,NaN,NaN,NaN,KE,6149
859,2011_RE_0863,10/5/2011,researcher_4,site_41,ocean,net,fisher_490,site_118,species_2,site_1,KE6223,None,NaN,NaN,NaN,32.2,29.2,3.5,NaN,"tag rip but tag still on,white calcareous algae on carapace.",Released,10/5/2011,NaN,NaN,NaN,NaN,KE,6223
543,2011_RE_0544,7/3/2011,researcher_4,site_13,ocean,net,fisher_420,site_13,species_1,site_62,KE6223,None,NaN,NaN,NaN,41.5,39.7,9.0,NaN,5th Cs divided into 3 parts. Small division in the 4th LLs. No other major Physical Characteristcs.,NaN,NaN,NaN,NaN,NaN,NaN,KE,6223
597,2011_RE_0598,7/21/2011,researcher_4,site_18,creek,net,fisher_232,site_18,species_1,site_80,KE6250,None,NaN,NaN,NaN,36.4,35.9,6.0,NaN,patches of white calcareous algae on the carapace& lots of barnacles(medium sized) on the carapace and plastron (removed)& turle generally emaciated especially on the plastron,NaN,NaN,NaN,NaN,NaN,NaN,KE,6250
615,2011_RE_0616,7/26/2011,researcher_4,site_41,ocean,net,fisher_791,site_118,species_2,site_62,KE6250,None,NaN,NaN,NaN,30.7,29.0,4.0,NaN,thick green algae on carapace&green algae on plastron,NaN,NaN,NaN,NaN,NaN,NaN,KE,6250
831,2011_RE_0835,9/30/2011,researcher_9,site_28,ocean,net,fisher_420,site_13,species_2,site_108,KE6388,None,NaN,NaN,NaN,34.6,33.0,4.5,NaN,"green algae on the carapace and plastron, patches of calcareous algae on the carapace.",Released,9/30/2011,NaN,NaN,NaN,NaN,KE,6388
866,2011_RE_0870,10/5/2011,researcher_4,site_24,creek,net,fisher_1047,site_118,species_2,site_1,KE6388,None,NaN,NaN,NaN,34.6,33.0,4.5,NaN,thin green algae on plastron and carapace.,Released,10/5/2011,NaN,NaN,NaN,NaN,KE,6388
1277,2011_RE_1281,12/12/2011,researcher_4,site_28,ocean,net,fisher_441,site_13,species_1,site_80,KE6388,None,NaN,NaN,NaN,36.7,34.3,5.5,NaN,"thick green algae on rear carapace, numerous patches of whitish calcareous algae on carapace",Released,12/12/2011,NaN,NaN,NaN,NaN,KE,6388
591,2011_RE_0592,7/18/2011,researcher_4,site_23,ocean,net,fisher_420,site_13,species_2,site_80,KE6442,None,NaN,NaN,NaN,37.0,33.0,6.0,NaN,green algae patches& clean plastron,NaN,NaN,NaN,NaN,NaN,NaN,KE,6442
943,2011_RE_0947,10/21/2011,researcher_22,site_53,creek,net,fisher_637,site_8,species_1,site_62,KE6442,None,NaN,NaN,NaN,50.5,45.7,14.0,NaN,tag rip on the lrf,Released,10/21/2011,NaN,NaN,NaN,NaN,KE,6442
876,2011_RE_0880,10/7/2011,researcher_22,site_33,creek,net,fisher_930,site_58,species_1,site_108,KE6474,None,NaN,NaN,NaN,45.5,41.8,11.0,NaN,"net bruising & blood on LFF, few barnacles on carapace, tag rip on left supra caudal scutes, a hard slightly protruding scar tissue on LFF.",Released,10/7/2011,NaN,NaN,NaN,NaN,KE,6474
993,2011_RE_0997,10/31/2011,researcher_4,site_123,ocean,net,fisher_162,site_118,species_2,site_108,KE6474,None,NaN,NaN,NaN,41.8,38.7,8.5,NaN,"thick green algae towards rear of carapace, flippers in good condition",Released,10/31/2011,NaN,NaN,NaN,NaN,KE,6474
1155,2011_RE_1159,11/23/2011,researcher_4,site_115,ocean,net,fisher_957,site_118,species_2,site_62,KE6474,None,NaN,NaN,NaN,41.6,38.4,6.5,NaN,Greenish algae on the rear carapace.Patches of whitish calcareous algae on the carapace.Pinkish algae on the platron.,Released,11/23/2011,NaN,NaN,NaN,NaN,KE,6474
1278,2011_RE_1282,12/13/2011,researcher_4,site_38,ocean,net,fisher_360,site_118,species_2,site_80,KE6578,None,NaN,NaN,NaN,45.2,43.2,11.5,NaN,"thin green algae on the carapace, numerous small barnacles around neck and shoulders and rear flipper.",Released,12/13/2011,NaN,NaN,NaN,NaN,KE,6578
1357,2011_RE_1361,12/31/2011,researcher_22,site_120,ocean,net,fisher_141,site_118,species_1,site_73,KE6578,None,NaN,NaN,NaN,45.1,33.1,13.0,NaN,Tiny barnacles on neck and shoulders.,Released,12/31/2011,NaN,NaN,NaN,NaN,KE,6578

In [99]:
# Get a dataframe of Tag_1 and species, grouped by Tag_1
df_Tag_1_Species = test_data.groupby('Tag_1')['Species'].apply(lambda x: x.unique()).to_frame().reset_index()
#check the unique values of each species
#Locate values that contain more than one Species, 
df_Tag_1_Species.Species = df_Tag_1_Species.Species.astype('str')
df_Tag_1_Species.Species.value_counts()
df_Tag_1_Species.loc[df_Tag_1_Species['Species'].isin(["['species_1' 'species_2']", "['species_2' 'species_1']"])]

# Get Tag_1 with more than one Species in a dataframe
Tag_1_more_than_1_Species =  df_Tag_1_Species.loc[df_Tag_1_Species['Species'].isin(["['species_1' 'species_2']", "['species_2' 'species_1']"])]
Tag_1_more_than_1_Species = Tag_1_more_than_1_Species.Tag_1.tolist()
# df_Tag_1_Species.Species

### Lost_Tag been used as Tag_1

#### Check if test tag_1 value is in cleaned lost_tag

In [100]:
#Lost_Tag been used as Tag_1
lost_tag_list = cleaned_data[cleaned_data.Lost_Tags != 'NOWAY']['Lost_Tags'].tolist()

In [101]:
df_wrong_Tag_1_in_Lost_Tag = test_data.loc[test_data.Tag_1.isin(lost_tag_list)]

### Tag_2

#### From the previous facts, all wrong values in tag_1 that has a tag_2 value is wrong .
How do  prove this now??

In [38]:
# Get all prospective wrong value in tag_1
wrong_Tag_1 = pd.read_csv('wrong_Tag_1.csv')
df_wrong_Tag_2 = wrong_Tag_1.loc[wrong_Tag_1.Tag_2!='None']

### Check if tag_2 is in clean_tag_2

In [30]:
# intercept_test_KE_clean_KEB =
[x for x in set(cleaned_data.loc[cleaned_data.Tag_2 != 'None'].Tag_2.tolist())if x in set(test_data.loc[test_data.Tag_2 != 'None'].Tag_2.tolist())]

['KE6444', 'KEB7536']

In [32]:
## check if it is in lost_tag
[x for x in set(cleaned_data.loc[cleaned_data.Lost_Tags != 'NOWAY'].Lost_Tags.tolist())if x in set(test_data.loc[test_data.Tag_2 != 'None'].Tag_2.tolist())]

[]

In [32]:
## check if it is in Tag_1
[x for x in set(cleaned_data.loc[cleaned_data.Tag_1!= 'NOWAY'].Tag_1.tolist())if x in set(test_data.loc[test_data.Tag_2 != 'None'].Tag_2.tolist())]

[]

In [36]:
# Weight_Kg

#### Tag_2 from wrong Weight_value

In [56]:
# from analysing clean value if  any size is < 40cm, then it shouldnt have a Tag_2
# because this turtle is not said to be big
df_tag_2 = test_data.loc[test_data.Tag_2!= 'None']
df_wrong_Tag_2_small_size = df_tag_2.loc[df_tag_2.CCL_cm < 40]

In [57]:
df_wrong_Tag_2_small_size

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Tag_3,Lost_Tags,T_Number,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,PCVNumber,Expenditure,Tag_type,Tag_num
444,2011_RE_0445,6/4/2011,researcher_22,site_53,creek,net,fisher_619,site_8,species_1,not_recorded,KE6246,KE6247,NaN,NaN,NaN,36.1,36.5,NaN,NaN,Taken to the Rehab.(Chokoraa),NaN,NaN,NaN,NaN,NaN,NaN,KE,6246
824,2011_RE_0828,9/28/2011,researcher_4,site_53,creek,net,fisher_861,site_8,species_1,site_80,KE6246,KE6247,NaN,NaN,NaN,36.2,36.8,5.5,NaN,"Numerous barnacles on both carapace & plastron, flakings on the carapace, green algae on carapace, sharp v-notch in the 11th LMS",Released,10/2/2011,NaN,NaN,NaN,NaN,KE,6246
850,2011_RE_0854,10/5/2011,researcher_4,site_58,creek,net,fisher_861,site_8,species_1,site_108,KE6246,KE6247,NaN,NaN,NaN,36.3,37.0,5.5,NaN,"was previously taken to rehab centre.numerous barnacles on both carapace. Flakings on the carapace, green algae on the carapace.short V notch in the 111th LMS",Released,10/5/2011,NaN,NaN,NaN,NaN,KE,6246
1001,2011_RE_1005,11/1/2011,researcher_4,site_58,creek,net,fisher_1054,site_110,species_1,not_recorded,KE6246,KE6247,NaN,NaN,NaN,36.2,36.8,5.5,NaN,taken to rehab for observtion,Admitted,NaN,NaN,NaN,NaN,NaN,KE,6246

### SpecialRemarks

In [40]:
SpecialRemarks

,dirt,clean
id,,
29,NOWAY,Found dead on 15/10/1999.
39,NOWAY,Fibropapillomatosis
406,NOWAY,"The turtle was released the next day after feeding but the turtle didn't swim away, it floated - it did some light swimming with the current. It looked very sick and weak although it wasn't emaciated - possibly severely stressed from capture"
506,NOWAY,Found dying on the beach the next day & put out of its misery.
3226,Fibropapillomatosis,NOTE 05/04/2018: Fibropapillomatosis? Unsure if admitted --> check with TRC records.
3249,NOWAY,"NOTE 05/04/2018: FP Patient, check TRC number in records"
3255,NOWAY,"NOTE 05/04/2018: Strange notes about turtle dying, no record of that in BCRP data book. Check with mortality records."
3271,Fibropapillomatosis,Fibropapillomatosis. NOTE 05/04/2018: turtle released? Or died? Check with TRC records
3390,NOWAY,NOTE 05/04/2018: no release date or time recorded
3517,Fibropapillomatosis,NOWAY
3714,NOWAY,NOTE 09/04/2018: Check on release date with TRC records!
3723,NOWAY,NOTE 09/04/2018: Check with TRC records
3725,NOWAY,NOTE 09/04/2018: Check with TRC records
3750,NOWAY,Tag replaced today: KE5565 on LRF replaced with KE5675 on RRF.
3751,NOWAY,NOTE 09/04/2018: Check with TRC records. Strange tag numbersäó_
3764,NOWAY,NOTE 09/04/2018: tag number in dta book recorded wrong. Correct tag number unknown
3794,NOWAY,NOTE 09/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used.
3829,NOWAY,Hatchling
3850,NOWAY,Polly
3859,NOWAY,NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used. Tag KE7505 broke during application.
3864,NOWAY,NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used. Tag KE7508 broke during application.
3929,NOWAY,"Tag removed, too small. 4879 replaced by KE7514. NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used."
3958,NOWAY,"NOTE 25/04/2018: Overlapping tag numbers, this tag is actually ""KE7515"""
4131,NOWAY,"NOTE 25/04/2018: Tag KE5903 lost, replaced with KE8119 (large tag) on 27/09/2012."
4287,NOWAY,"NOTE 25/04/2018: No record of this in any data book but may be a ""straight to TRC"" case, check with TRC records."

In [60]:
cleaned_data.loc[SpecialRemarks.index].sort_values(by='Tag_1')

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Lost_Tags,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,Tag_type,Tag_num
id,,,,,,,,,,,,,,,,,,,,,,,,
3725,2010_RE_0568,7/26/2010,researcher_4,site_46,creek,net,fisher_1142,site_118,species_2,site_108,3516,None,NOWAY,35.4,32.6,4.5,NOWAY,Patches of white calcareous algae with green algae. Almost 50% of right rear flipper missing. Green algae on plastron. Numerous of barnacles on plastron. Pinkish and whitish calcareous algaee on plastron. Weak.,NOWAY,NOWAY,Taken to rehab for observation,NOTE 09/04/2018: Check with TRC records,,3516
3249,2010_RE_0092,2/3/2010,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_108,3557,None,NOWAY,49.1,47.4,NOWAY,NOWAY,V notch in between 10th and 11 LMS& V notches in between 7th and 8th& and 9th and 10th Rms. White calcareous algae all over carapace& minor flake on plastron but generally clean. Flesh growth in the left eye& taken to rehab center,NOWAY,NOWAY,NOWAY,"NOTE 05/04/2018: FP Patient, check TRC number in records",,3557
3226,2010_RE_0069,1/25/2010,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_62,3557,None,NOWAY,49.4,47.3,NOWAY,NOWAY,Small u notch in 5th LMS& in btw 10th and 11 LMS& btw 9th and 10th RMS& btw 7th and 8th RMS. White patches of calcareous algae on RSS. Green algae on carapace& a growth on left eye not causing obstructions& not a fibro-growth. Tag pull a hole. Minor flake,NOWAY,NOWAY,NOWAY,NOTE 05/04/2018: Fibropapillomatosis? Unsure if admitted --> check with TRC records.,,3557
3390,2010_RE_0233,3/22/2010,researcher_4,site_111,creek,net,fisher_69,site_8,species_1,site_90,4194,None,NOWAY,51.7,49.6,NOWAY,NOWAY,Green algae on carapace& shallow U-notch in btw LMS and LSCS& flakings on 1st and 2nd right marginal scute& flakings on the plastron,NOWAY,NOWAY,NOWAY,NOTE 05/04/2018: no release date or time recorded,,4194
29,1999_RE_0014,6/24/1999,researcher_17,site_8,creek,not_recorded,fisher_266,not_recorded,species_1,site_108,H383,None,NOWAY,39.17,39.17,NOWAY,Unknown,SmBs-2LLS& 3Bs Lprefrontal& 1B-each rear flip& 1B-9Lmarginal& 3B- rear marginal,Released,6/24/1999,NOWAY,Found dead on 15/10/1999.,H,383
39,1999_RE_0024,8/19/1999,researcher_17,site_58,creek,net,fisher_1387,site_8,species_1,site_108,H477,None,NOWAY,46.5,43,NOWAY,Unknown,smBs on head& 4smBs-RRflip& 1B-3RLS & 7RM & 5CS& 2Bs 6RM. Multiple tumors on left flipper and RRF,Released,NOWAY,NOWAY,Fibropapillomatosis,H,477
506,2002_RE_0115,7/31/2002,researcher_18,site_35,creek,longline,fisher_1114,site_110,species_2,site_80,KE0808,None,NOWAY,34.1,30.9,NOWAY,Unknown,Missing LFF completely. Small wound on top of head/neck area. Seemed lively. Was found beached on Watamu Beach the next day and died.,Released,7/31/2002,NOWAY,Found dying on the beach the next day & put out of its misery.,KE,0808
3714,2010_RE_0557,7/20/2010,researcher_4,site_58,creek,net,fisher_563,site_118,species_2,site_108,KE5607,None,NOWAY,32.6,30.4,3.5,NOWAY,Flaking scutes. Thick green algae towards the rear shell. Flaking plastron. 2nd left lateral scute damaged. Inactive.,NOWAY,NOWAY,Taken to rehab for observation.,NOTE 09/04/2018: Check on release date with TRC records!,KE,5607
3723,2010_RE_0566,7/24/2010,researcher_4,site_7,ocean,net,fisher_953,site_120,species_1,not_recorded,KE5621,None,NOWAY,39.8,39.1,4.5,NOWAY,Minor flaking on the 2nd and 4th CS& LRF u-notch& general clean plastron& 8th and 9th LMS slightly broken,NOWAY,NOWAY,Taken to rehab,NOTE 09/04/2018: Check with TRC records,KE,5621
3750,2010_RE_0593,8/4/2010,researcher_4,site_58,creek,net,fisher_766,site_8,species_1,site_80,KE5675,None,KE5565,49.8,45.3,14.5,NOWAY,Inactive. Green algae on carapace. Tag rip in the left rear flipper. Flaking on the left supra. Grey patches on the center of scutes. Clean plastron with barnacles removed and bs wounds.,NOWAY,NOWAY,NOWAY,Tag replaced today: KE5565 on LRF replaced with KE5675 on RRF.,KE,5675
3271,2010_RE_0114,2/12/2010,researcher_9,site_47,ocean,beached,fisher_868,site_47,species_1,not_recorded,KE6111,KE6222,NOWAY,52,48.4,NOWAY,NOWAY,Thick green algae on carapace& a fibro tumour under the neck& brown algae on neck and shoulders& numerous small barnacles on flippers& neck and shoulders& big lacerations under the right shoulder& fibro tumour in the right side of tail&,NOWAY,NOWAY,Taken to rehab,Fibropapillomatosis. NOTE 05/04/2018: turtle released? Or died? Check with TRC records,KE,6111
3751,2010_RE_0594,8/4/2010,researcher_4,site_58,creek,net,fisher_1351,site_8,species_1,not_recorded,KE6333,KE6444,NOWAY,43.3,42,6.5,NOWAY,Thick green algae. Pink/white patches of calcareous algae.Badly emaciated (thin flipper& sunken eyes& protruding bones of plastron& bleeding wounds). General weak.,NOWAY,NOWAY,Taken to rehab. (Referenda),NOTE 09/04/2018: Check with TRC records. Strange tag numbersäó_,KE,6333
3850,2010_RE_0693,9/2/2010,researcher_4,site_41,creek,net,fisher_162,site_118,species_2,site_62,KE7799,None,KE5571,34,29.4,5,NOWAY,Patches of pinkish calcareous algae. Green algae towards rear shell. Muddy towards rear shell. Flaking tips of scutes. Juvenile.Clean plastron. No separetion on the head scales. No other major characteristics.,NOWAY,NOWAY,NOWAY,Polly,KE,7799
3794,2010_RE_0637,8/18/2010,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_80,KEB7503,KEB7504,NOWAY,88.6,86.1,NOWAY,Female,Patches of pinkish calcareous algae. U-notch on right rear flipper. Right supracaudal scute slightly broken. V-notch in left rear flipper. Clean plastron. Adult.,NOWAY,NOWAY,Adult,NOTE 09/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used.,KEB,7503
3859,2010_RE_0702,9/5/2010,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_80,KEB7506,KEB7507,NOWAY,100.3,97.8,NOWAY,Female,Numerous pinkish patches of calcareous algea on the shell.Open bruises on the left side of the 2nd CS and top left corner of the 2nd LLS.Shallow V-notch in the RFF andLRF.Net bruises on the FFs.,NOWAY,NOWAY,NOWAY,NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used. Tag KE7505 broke during application.,KEB,7506
3864,2010_RE_0707,9/6/2010,researcher_4,site_53,creek,net,fisher_637,site_8,species_1,site_97,KEB7509,KEB7510,NOWAY,69.5,64.7,42.5,NOWAY,Green algea on the carapace.Additional scute between 4th and 5th CS(6Cs).Tagripsin both rear flippres.Double notches in the LRF scales towards body.The 5th CS edge begin to flake.,NOWAY,9/7/2010,NOWAY,NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used. Tag KE7508 broke during application.,KEB,7509
3929,2010_RE_0773,9/28/2010,researcher_4,site_33,creek,net,fisher_496,site_8,species_1,site_80,KEB7514,None,4879,60,53.3,25,NOWAY,Green algae on carapace& big barnacles on plastron (removed)& health turtle well fed and strong.,NOWAY,NOWAY,NOWAY,"Tag removed, too small. 4879 replaced by KE7514. NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used.",KEB,7514
3958,2010_RE_0803,10/11/2010,researcher_4,site_53,creek,net,fisher_1144,site_8,species_1,site_80,KEB7515,None,NOWAY,62.5,54.5,28,NOWAY,Tag rip on the LRF& flaking plastron& barnacles on the plastron (removed)& green algae on carapace& heald wound at edge of 1st CS and 2nd CS+2nd RLS,NOWAY,NOWAY,Caught the day before,"NOTE 25/04/2018: Overlapping tag numbers, this tag is actually ""KE7515""",KEB,7515
4131,2010_RE_0980,11/25/2010,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_62,KEB8119,None,KE5903,52,48.6,18.5,NOWAY,Barnacles removed on the plastron.Pinkish algea around neck and shoulders.Thin green algea on the plastron and on shell.,NOWAY,NOWAY,NOWAY,"NOTE 25/04/2018: Tag KE5903 lost, replaced with KE8119 (large tag) on 27/09/2012.",KEB,8119
3764,2010_RE_0607,8/7/2010,researcher_9,site_38,ocean,net,fisher_1268,site_118,species_1,site_73,Missing Data,None,NOWAY,40.9,39.5,8,NOWAY,Numerous small barnacles on shell. A through spear gun injury at the middle of the right front flipper.,NOWAY,NOWAY,NOWAY,NOTE 09/04/2018: tag number in dta book recorded wrong. Correct tag number unknown,Missing Data,None
406,2002_RE_0014,2/10/2002,researcher_17,site_58,creek,net,fisher_560,site_58,species_1,site_71,NotTagged_0106,None,NOWAY,32.3,31.9,NOWAY,Unknown,1 LLS 1 b+ 3LM 1 b+ 2 LM 2 small b's+ 2 CS 2 small b's+ 3 Rls 1 small b+ 1 large cluster of b's on LFF+ a few small b's on both FF+ RFF has a small hook wound+ the head has 2 small b's on prefronal scutes+ a few small b's on rear flippers+ small cut super,Released,2/12/2002,the turtle swam slowly and it didn't go far.,"The turtle was released the next day after feeding but the turtle didn't swim away, it floated - it did some light swimming with the current. It looked very sick and weak although it wasn't emaciated - possibly severely stressed from capture",NotTagged_,0106
3255,2010_RE_0098,2/5/2010,researcher_4,site_115,ocean,net,fisher_1323,site_118,species_1,site_90,NotTagged_0309,None,NOWAY,49.7,47.1,NOWAY,NOWAY,Edges of scutes starting to flake& perfect turtle,NOWAY,NOWAY,Caught the day before; turtle died,"NOTE 05/04/2018: Strange notes about turtle dying, no record of that in BCRP data book. Check with mortality records.",NotTagged_,0309
3517,2010_RE_0360,4/23/2010,researcher_9,site_54,ocean,collected floater,not_recorded,site_54,species_1,not_recorded,NotTagged_0412,None,NOWAY,61.9,58.9,NOWAY,NOWAY,Heavily infested with fibro virus on neck& shoulders& flippers& and eyes& barnacles on plastron& shell begining to flake& brown algae on neck and shoulders& deep U-shaped notch on 11th LMS,NOWAY,NOWAY,Euthanized on 23/04/2010,NOWAY,NotTagged_,0412
3829,2010_RE_0672,8/26/2010,researcher_9,site_63,ocean,beached,fisher_433,site_63,species_1,not_recorded,NotTagged_0417,None,NOWAY,7,6.4,0.05,NOWAY,A big gash in the middle of the head. The wound was found inveded with paracite. Most likely peaked by a bird.,NOWAY,NOWAY,Died on 02/09/10. Was attacked by a hawk Short Beach ill patient in the rehab tank when they had been placed together. (Engulfed from the head).,Hatchling,NotTagged_,0417
4287,2010_RE_1138,12/30/2010,researcher_9,site_52,ocean,beached,fisher_78,site_31,species_1,site_97,missing data,none,NOWAY,39.4,39.9,8.5,NOWAY,Body condition was good but appeared very sick. It could not even lift its head to breath.,NOWAY,NOWAY,NOWAY,"NOTE 25/04/2018: No record of this in any data book but may be a ""straight to TRC"" case, check with TRC records.",missing data,None

Most special remarks wrong values are NAN. How do investigate into this values??

In [18]:
SpecialRemark_Tag_1_with_value = cleaned_data.loc[cleaned_data.SpecialRemarks != 'NOWAY'].Tag_1.tolist()

In [23]:
cleaned_data.loc[cleaned_data.Tag_1.isin(SpecialRemark_Tag_1_with_value)].sort_values(by='Tag_1')

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Lost_Tags,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,Tag_type,Tag_num
3047,2007_RE_0512,11/19/2007,researcher_23,site_38,ocean,net,fisher_400,site_118,species_1,not_recorded,3328,None,NOWAY,51.3,49,NOWAY,Unknown,SC's uneven. 2 large barnacles on carapace (killed). Several small tumours around soft tissues. Sent to rehab.,Admitted,NOWAY,Fibro; Released following day,Fibropapillomatosis,,3328
2659,2007_RE_0124,3/18/2007,researcher_23,site_53,creek,net,fisher_861,site_8,species_1,site_80,3398,None,KE1805,54.6,52.8,NOWAY,Unknown,Notch between 10 + 11 RM. Large notch between 6 + 7 RM. Outer edge of RRF uneven + notched.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2532,2006_RE_0402,12/30/2006,researcher_9,site_53,creek,net,fisher_861,site_8,species_1,site_116,3398,None,KE1805,52.7,50.8,NOWAY,Unknown,Shallow notch in 7th RMS. Rear shell beginning to flake.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2508,2006_RE_0378,12/20/2006,researcher_9,site_53,creek,net,fisher_861,site_8,species_1,site_80,3398,None,KE1805,52.9,50.6,NOWAY,Unknown,Flaking on scutes.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2493,2006_RE_0363,12/15/2006,researcher_9,site_53,creek,net,fisher_619,site_8,species_1,site_80,3398,None,KE1805,52.7,50.5,NOWAY,Unknown,Shallow big notch between 6th and 7th RMS. Baeutiful shell.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2460,2006_RE_0330,12/1/2006,researcher_9,site_53,creek,net,fisher_861,site_8,species_1,site_90,3398,None,KE1805,52.4,50.3,NOWAY,Unknown,Shallow notch in 7th RMS. Flaking shell.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2407,2006_RE_0277,10/29/2006,researcher_23,site_53,creek,net,fisher_930,site_58,species_1,site_80,3398,None,KE1805,52,50,NOWAY,Unknown,No.9& 10 + 11 LM uneven edges. Notch between No. 6 + 7 LM. Large notch between No. 6 and 7 RMS. Flaking on all scutes. Large groove at outer edge of LRF.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2253,2006_RE_0123,5/19/2006,researcher_9,site_53,creek,net,fisher_1194,site_8,species_1,site_80,3398,None,KE1805,46.4,44.9,NOWAY,Unknown,Small Bs on 2nd and 3rd CS& both SCLs + Plastron. A notch between 6th and 7th RMS,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2225,2006_RE_0095,3/31/2006,researcher_9,site_111,creek,net,fisher_294,site_8,species_1,site_87,3398,None,KE1805,45.7,44.5,NOWAY,Unknown,Bs on 11th RMS& Shell begins to flake.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2223,2006_RE_0093,3/23/2006,researcher_9,site_58,creek,net,fisher_1206,site_8,species_1,site_80,3398,None,KE1805,45.7,44.4,NOWAY,Unknown,Bs on 11th RMS + 5th LMS and the tips both SCLs are raised.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2157,2006_RE_0027,1/28/2006,researcher_23,site_8,creek,net,fisher_538,site_8,species_1,site_80,3398,None,KE1805,44.6,43.8,NOWAY,Unknown,2 lge grooves at edge of RRF& Two medium Bs on plastron. Flaking on all scutes.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2013,2005_RE_0325,9/29/2005,researcher_9,site_53,creek,net,fisher_861,site_8,species_1,site_87,3398,None,KE1805,40.4,40.4,NOWAY,Unknown,Shell begins to flake. Few Bs on plastron.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
1980,2005_RE_0292,9/1/2005,researcher_9,site_53,creek,net,fisher_155,site_8,species_1,site_108,3398,None,KE1805,39.3,39.7,NOWAY,Unknown,The shell is beginning to flake. Small Bs on the 1st CS and plastron. A healed laceration on the plastron. 8.5 cm.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
1950,2005_RE_0262,8/4/2005,researcher_9,site_53,creek,net,fisher_861,site_8,species_1,site_80,3398,None,KE1805,39,38.6,NOWAY,Unknown,Minor flaking on carapace. A healing laceration marks on 3rd LLS 8.5cm.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2697,2007_RE_0162,4/9/2007,researcher_23,site_33,creek,net,fisher_861,site_8,species_1,site_80,3398,None,KE1805,55.1,53.3,NOWAY,Unknown,Notch between No. 7 + 8 LM. Notch between No. 10 + 11 RM.2 large notches at outer edge of LRF. 1 barnacle on carapace.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2717,2007_RE_0182,4/22/2007,researcher_23,site_53,creek,net,fisher_294,site_8,species_1,site_80,3398,None,KE1805,55.4,53,NOWAY,Unknown,Groove in No. 7 RM. Skin growing over tag.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.",,3398
2844,2007_RE_0309,7/26/2007,researcher_9,site_33,creek,longline,fisher_598,site_42,species_1,site_80,3490,None,3231,47.4,41.7,NOWAY,Unknown,Hooked in the mouth. (Worm was the beit). Small barnacles on shoulders. LSC is slight small. Flaking plastron.,Released,NOWAY,NOWAY,NOTE (05/10/2017) tag 3231 lost between 10/05/2008-18/11/2008,,3490
3725,2010_RE_0568,7/26/2010,researcher_4,site_46,creek,net,fisher_1142,site_118,species_2,site_108,3516,None,NOWAY,35.4,32.6,4.5,NOWAY,Patches of white calcareous algae with green algae. Almost 50% of right rear flipper missing. Green algae on plastron. Numerous of barnacles on plastron. Pinkish and whitish calcareous algaee on plastron. Weak.,NOWAY,NOWAY,Taken to rehab for observation,NOTE 09/04/2018: Check with TRC records,,3516
1930,2005_RE_0242,7/18/2005,researcher_9,site_53,creek,net,fisher_109,site_58,species_1,site_80,3525,None,KE1510,51.1,44,NOWAY,Unknown,Additional scute between 4th and 5th CS. A huge chunk on 6th LMS. A small notch on LSC. Bs on 4th LLS& 5th CS& LSC& 9th RMS and on the head. 2nd LLS is raised.,Released,NOWAY,NOWAY,NOTE (06/10/2017): tag KE1510 was removed & replaced by 3525 on 10/06/2008..,,3525
1365,2004_RE_0134,4/22/2004,researcher_23,site_33,creek,longline,fisher_634,site_58,species_1,site_80,3525,None,KE1510,46.6,41.1,NOWAY,Unknown,Large notch between 5th + 6th LMS& small notch in between 11th LMS + the L SC& small notch in between the 11th RMS + the R SC& Large B on the 4th CS& Flaking on 1st + the 2nd RLS& 1st LLS& small notch in the Central RRF.,Released,NOWAY,NOWAY,NOTE (06/10/2017): tag KE1510 was deplyed on a hawksbill,,3525
3102,2007_RE_0567,12/9/2007,researcher_9,site_53,creek,net,fisher_294,site_8,species_1,not_recorded,3546,None,KE1839,53.7,49.8,NOWAY,Unknown,Tag lump in LRF. 1st joint of RFF is broken. Big notch in LRF. Flaking plastron.,Not_Recorded,NOWAY,NOWAY,"NOTE (06/10/2017): Lost tags KE1839, KE1966 and 3264.",,3546
2379,2006_RE_0249,10/6/2006,researcher_9,site_53,creek,net,fisher_1194,site_8,species_1,site_80,3546,None,KE1839,47.5,45,NOWAY,Unknown,Edges in RFs are jagged. Notch in LSCL. Shell begins to flake.,Released,NOWAY,NOWAY,"NOTE (06/10/2017): Lost tags KE1839, KE1966 and 3264.",,3546
2005,2005_RE_0317,9/25/2005,researcher_23,site_15,creek,net,fisher_977,site_8,species_1,site_80,3546,None,KE1839,41.9,40.3,NOWAY,Unknown,Notch in LSC. 3 large Bs on carapace. Large groove at centre of LRF.,Released,NOWAY,NOWAY,"NOTE (06/10/2017): Lost tags KE1839, KE1966 and 3264.",,3546
2012,2005_RE_0324,9/29/2005,researcher_23,not_recorded,creek,net,fisher_142,site_42,species_1,site_80,3546,None,KE1839,41.7,40.1,NOWAY,Unknown,Notch at centre of LSC& Flaking on all scutes. Circular scars on No. 5 CS + No. 4 RLS.,Released,NOWAY,NOWAY,"NOTE (06/10/2017): Lost tags KE1839, KE1966 and 3264.",,3546
3007,2007_RE_0472,11/5/2007,researcher_9,site_53,creek,net,fisher_861,site_8,species_1,site_80,3546,None,KE1839,53.2,49.4,NOWAY,Unknown,A big tag lump in LRF. 2 chips in LSCL. The joint between 1st CS and 1st LLS is flaking.,Released,NOWAY,NOWAY,"NOTE (06/10/2017): Lost tags KE1839, KE1966 and 3264.",,3546
2914,2007_RE_0379,9/14/2007,researcher_9,site_53,creek,net,fisher_861,site_8,species_1,site_73,3546,None,KE1839,52.5,48.7,NOWAY,Unknown,L shaped big notch in LRF. Tag place swollen tight to the tag. Small barnacles on flippers + both supra.,Released,NOWAY,NOWAY,"NOTE (06/10/2017): Lost tags KE1839, KE1966 and 3264.",,3546
2235,2006_RE_0105,4/25/2006,researcher_23,site_35,creek,longline,fisher_811,site_58,species_1,site_80,3546,None,KE1839,45.3,43,NOWAY,Unknown,Flaking on all scutes. Notch between No. 11 RM + RSC. Small notch between No. 11LM + LSC. Notch between No. 10 and 11 LM. V shaped notch at centre of LRF. Hooked in the mouth.,Released,NOWAY,NOWAY,"NOTE (06/10/2017): Lost tags KE1839, KE1966 and 3264.",,3546
3268,2010_RE_0111,2/10/2010,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_80,3557,None,NOWAY,49.2,47.5,NOWAY,NOWAY,V-notch in between 10th and 11th LMS& white calcareous algae all over carapace& v-notches between 7th-8th& 9th-10th RMS& minor flake on plastron but generally clean& taken to rehab for antibiotic on cauterized eye,NOWAY,NOWAY,NOTE 05/04/2018: Notes talk of cauterized eye --> FP? Check with TRC records.,NOWAY,,3557
3226,2010_RE_0069,1/25/2010,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_62,3557,None,NOWAY,49.4,47.3,NOWAY,NOWAY,Small u notch in 5th LMS& in btw 10th and 11 LMS& btw 9th and 10th RMS& btw 7th and 8th RMS. White patches of calcareous algae on RSS. Green algae on carapace& a growth on left eye not causing obstructions& not a fibro-growth. Tag pull a hole. Minor flake,NOWAY,NOWAY,NOWAY,NOTE 05/04/2018: Fibropapillomatosis? Unsure if admitted --> check with TRC records.,,3557
3249,2010_RE_0092,2/3/2010,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_108,3557,None,NOWAY,49.1,47.4,NOWAY,NOWAY,V notch in between 10th and 11 LMS& V notches in between 7th and 8th& and 9th and 10th Rms. White calcareous algae all over carapace& minor flake on plastron but generally clean. Flesh growth in the left eye& taken to rehab center,NOWAY,NOWAY,NOWAY,"NOTE 05/04/2018: FP Patient, check TRC number in records",,3557
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3795,2010_RE_0638,8/18/2010,researcher_4,site_62,creek,net,fisher_50,site_118,species_2,site_80,KE7799,None,KE5571,33.6,29.2,4.5,NOWAY,Patch of pinkish calcareous alsge. Green algae. Muddy towards rear shell. Flaking tips of scutes. Clean plastron. Juvenile.,NOWAY,NOWAY,NOWAY,NOWAY,KE,7799
3759,2010_RE_0602,8/6/2010,researcher_4,site_20,creek,net,fisher_50,site_118,species_2,site_62,KE7799,None,KE5571,33.5,29,5,NOWAY,Patches of pinkish calcareous algae. Green algae towards rear shell. Clean plastron. No separetion on the head scales. No other major characteristics.,NOWAY,NOWAY,NOWAY,NOWAY,KE,7799
3589,2010_RE_0432,5/22/2010,researcher_9,site_119,ocean,net,fisher_181,site_118,species_2,site_108,KE7799,None,KE5571,33.1,28.5,4.5,NOWAY,no major physical,NOWAY,NOWAY,NOWAY,NOWAY,KE,7799
4213,2010_RE_1062,12/13/2010,researcher_9,site_46,ocean,net,fisher_162,site_118,species_2,site_62,KE7799,None,KE5571,33.9,29.8,4.3,NOWAY,Thick brown and green algea on carapace and rear flippers.,NOWAY,NOWAY,NOWAY,NOWAY,KE,7799
4229,2010_RE_1078,12/15/2010,researcher_4,site_38,ocean,net,fisher_1031,site_118,species_2,site_62,KE7799,None,KE5571,34.7,29.7,5.5,NOWAY,Thick green algae on the shell and few patches of white calcareous algae. Pinkish algae on the neck. General clean plastron with thin algae on the edge.,NOWAY,NOWAY,NOWAY,NOWAY,KE,7799
3647,2010_RE_0490,6/20/2010,researcher_4,site_38,ocean,net,fisher_369,site_118,species_2,site_97,KE7799,None,KE5571,33.3,28.7,4,NOWAY,Flakings on the tips of scutes& green algae towards the rear shell& clean plastron,NOWAY,NOWAY,NOWAY,NOWAY,KE,7799
3630,2010_RE_0473,6/12/2010,researcher_4,site_65,creek,net,fisher_1055,site_118,species_2,site_73,KE7799,None,KE5571,33.2,28.7,3.75,NOWAY,Flakings tips of scutes& green algae on rear shell& very active& flaking plastron generally clean,NOWAY,NOWAY,NOWAY,NOWAY,KE,7799
3611,2010_RE_0454,6/3/2010,researcher_4,site_38,ocean,net,fisher_1031,site_118,species_2,site_97,KE7799,None,KE5571,33.3,28.7,4,NOWAY,Flakings on the tips of scutes& green algae towards the rear shell& clean plastron,NOWAY,NOWAY,NOWAY,NOWAY,KE,7799
3887,2010_RE_0730,9/16/2010,researcher_4,site_119,ocean,net,fisher_566,site_118,species_2,site_62,KE7799,None,KE5571,33.7,29.3,4.5,NOWAY,Thick green algae on the carapace toward the shell& clean plastron& patches of calcareous algae& flacking of ti[ of scutes,NOWAY,NOWAY,NOWAY,NOWAY,KE,7799
3794,2010_RE_0637,8/18/2010,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_80,KEB7503,KEB7504,NOWAY,88.6,86.1,NOWAY,Female,Patches of pinkish calcareous algae. U-notch on right rear flipper. Right supracaudal scute slightly broken. V-notch in left rear flipper. Clean plastron. Adult.,NOWAY,NOWAY,Adult,NOTE 09/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used.,KEB,7503
3859,2010_RE_0702,9/5/2010,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_80,KEB7506,KEB7507,NOWAY,100.3,97.8,NOWAY,Female,Numerous pinkish patches of calcareous algea on the shell.Open bruises on the left side of the 2nd CS and top left corner of the 2nd LLS.Shallow V-notch in the RFF andLRF.Net bruises on the FFs.,NOWAY,NOWAY,NOWAY,NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used. Tag KE7505 broke during application.,KEB,7506
3864,2010_RE_0707,9/6/2010,researcher_4,site_53,creek,net,fisher_637,site_8,species_1,site_97,KEB7509,KEB7510,NOWAY,69.5,64.7,42.5,NOWAY,Green algea on the carapace.Additional scute between 4th and 5th CS(6Cs).Tagripsin both rear flippres.Double notches in the LRF scales towards body.The 5th CS edge begin to flake.,NOWAY,9/7/2010,NOWAY,NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used. Tag KE7508 broke during application.,KEB,7509
3929,2010_RE_0773,9/28/2010,researcher_4,site_33,creek,net,fisher_496,site_8,species_1,site_80,KEB7514,None,4879,60,53.3,25,NOWAY,Green algae on carapace& big barnacles on plastron (removed)& health turtle well fed and strong.,NOWAY,NOWAY,NOWAY,"Tag removed, too small. 4879 replaced by KE7514. NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used.",KEB,7514
3217,2010_RE_0060,1/22/2010,researcher_4,site_110,creek,net,fisher_1007,site_8,species_1,site_85,KEB7514,None,4879,57.2,51.2,NOWAY,NOWAY,Green algae on carapace. Tip of RFF missing. Well fed and healthy turtle.,NOWAY,NOWAY,NOWAY,NOWAY,KEB,7514
3958,2010_RE_0803,10/11/2010,researcher_4,site_53,creek,net,fisher_1144,site_8,species_1,site_80,KEB7515,None,NOWAY,62.5,54.5,28,NOWAY,Tag rip on the LRF& flaking plastron& barnacles on the plastron (removed)& green algae on carapace& heald wound at edge of 1st CS and 2nd CS+2nd RLS,NOWAY,NOWAY,Caught the day before,"NOTE 25/04/2018: Overlapping tag numbers, this tag is actually ""KE7515""",KEB,7515
4131,2010_RE_0980,11/25/2010,researcher_4,site_38,ocean,net,fisher_360,site_118,species_1,site_62,KEB8119,None,KE5903,52,48.6,18.5,NOWAY,Barnacles removed on the plastron.Pinkish algea around neck and shoulders.Thin green algea on the plastron and on shell.,NOWAY,NOWAY,NOWAY,"NOTE 25/04/2018: Tag KE5903 lost, replaced with KE8119 (large tag) on 27/09/2012.",KEB,8119
3764,2010_RE_0607,8/7/2010,researcher_9,site_38,ocean,net,fisher_1268,site_118,species_1,site_73,Missing Data,None,NOWAY,40.9,39.5,8,NOWAY,Numerous small barnacles on shell. A through spear gun injury at the middle of the right front flipper.,NOWAY,NOWAY,NOWAY,NOTE 09/04/2018: tag number in dta book recorded wrong. Correct tag number unknown,Missing Data,None
406,2002_RE_0014,2/10/2002,researcher_17,site_58,creek,net,fisher_560,site_58,species_1,site_71,NotTagged_0106,None,NOWAY,32.3,31.9,NOWAY,Unknown,1 LLS 1 b+ 3LM 1 b+ 2 LM 2 small b's+ 2 CS 2 small b's+ 3 Rls 1 small b+ 1 large cluster of b's on LFF+ a few small b's on both FF+ RFF has a small hook wound+ the head has 2 small b's on prefronal scutes+ a few small b's on rear flippers+ small cut super,Released,2/12/2002,the turtle swam slowly and it didn't go far.,"The turtle was released the next day after feeding but the turtle didn't swim away, it floated - it did some light swimming with the current. It looked very sick and weak although it wasn't emaciated - possibly severely stressed from capture",NotTagged_,0106
1719,2005_RE_0031,2/8/2005,researcher_9,site_120,ocean,net,fisher_1053,site_120,species_1,not_recorded,NotTagged_0158,None,NOWAY,50.4,46.3,NOWAY,Unknown,Fibropapillomatosis tumours on neck& shoulder and eyes.green algae on carapace . Few patches of pink calcereous algae on carapace. Numereous Bs on flippers,Not_Recorded,NOWAY,died,Fibropapillomatosis,NotTagged_,0158
2044,2005_RE_0356,10/25/2005,researcher_9,site_28,ocean,net,fisher_997,site_120,species_1,site_80,NotTagged_0166,None,NOWAY,52.5,47.3,NOWAY,Unknown,Fibropapillomas tumours on shoulder& Shell flaking. A small additional scute in between 4th and 5th = 6 CS. Small white patches of calcereous algea on 1st and 7th RMS& 4th RLS and 5th CS. Cautorized marks on both shoulders and LFF.,Released,10/29/2005,NOWAY,Fibropapillomatosis,NotTagged_,0166
2293,2006_RE_0163,7/5/2006,researcher_9,site_23,ocean,net,fisher_424,site_120,species_1,not_recorded,NotTagged_0167,None,NOWAY,48.5,46.7,NOWAY,Unknown,Lots of tumours on soft tissues and oculated. Sticky sand on rear shell. Green algae on RFs and brown algae on neck and flaking shell.,Admitted,NOWAY,Died on 05 July 2006,Fibropapillomatosis,NotTagged_,0167
2987,2007_RE_0452,10/24/2007,researcher_9,site_15,creek,net,fisher_879,site_8,species_1,not_recorded,NotTagged_0179,None,NOWAY,46,42.8,NOWAY,Unknown,Oculation of the whole right eye. Green algae on carapace. Small patches of calcereous algae on scutes. Fibropapillomatosis,Admitted,NOWAY,Euthanized,Fibropapillomatosis,NotTagged_,0179
2989,2007_RE_0454,10/25/2007,researcher_9,site_28,ocean,net,fisher_875,site_25,species_1,not_recorded,NotTagged_0180,None,NOWAY,61.9,56.9,NOWAY,Unknown,Lots of tumours around both eyes and soft parts of the body. Turtle still strong and active,Admitted,NOWAY,Euthanized,Fibropapillomatosis,NotTagged_,0180

In [20]:
test_data.loc[test_data.Tag_1.isin(SpecialRemark_Tag_1_with_value)].sort_values(by='Tag_1')

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Tag_3,Lost_Tags,T_Number,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks,PCVNumber,Expenditure,Tag_type,Tag_num
509,2011_RE_0510,6/25/2011,researcher_22,site_35,creek,net,fisher_466,site_58,species_1,not_recorded,KE6333,KE6444,NaN,NaN,NaN,44.1,43.0,7.60,NaN,A fresh through hole injury in 2nd RLS by the MS joint. Sounds the right lung is damaged as it is bubbling while tilting the turtle. Loss of weight.,NaN,NaN,Sent to rehab (Referenda),NaN,NaN,NaN,KE,6333
42,2011_RE_0043,1/12/2011,researcher_4,site_38,ocean,net,fisher_530,site_118,species_2,site_62,KE7799,None,NaN,NaN,NaN,35.4,30.1,5.50,NaN,Pinkish algea around neck and flippers.Thick green algea on the carapace.Patches of calcareous algea on the shell.,NaN,NaN,NaN,NaN,NaN,NaN,KE,7799
263,2011_RE_0264,4/12/2011,researcher_4,site_41,creek,net,fisher_128,site_118,species_2,not_recorded,KE7799,None,NaN,NaN,NaN,36.3,31.5,6.00,NaN,Carapace covered with green algae thicker towards rear. Patches of pink calcareous algae on carapace.Green algae on plasstron. Barnacles (Removed) on plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,7799
348,2011_RE_0349,5/10/2011,researcher_4,site_41,creek,net,fisher_1056,site_118,species_2,not_recorded,KE7799,None,NaN,NaN,NaN,37.5,31.5,6.00,NaN,Thick green algae on the carapace. Patches of pinkish calcareous algae on the shell. Green algae with pinkish algae on the plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,7799
360,2011_RE_0361,5/11/2011,researcher_4,site_41,creek,net,fisher_583,site_118,species_2,not_recorded,KE7799,None,NaN,NaN,NaN,37.5,31.5,6.00,NaN,Thick green algae on the carapace. Patches of pinkish calcareous algae on the shell. Green algae with pinkish algae on the plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,7799
508,2011_RE_0509,6/25/2011,researcher_22,site_41,creek,net,fisher_192,site_118,species_2,site_62,KE7799,None,NaN,NaN,NaN,37.4,31.4,6.50,NaN,Green and brown algae on carapace& RF and shoulders. Few barnacles on the plastron.,NaN,NaN,NaN,NaN,NaN,NaN,KE,7799
601,2011_RE_0602,7/23/2011,researcher_9,site_24,creek,net,fisher_791,site_118,species_2,site_62,KE7799,None,NaN,NaN,NaN,37.5,32.3,9.00,NaN,lots of algae covering the carapace,NaN,NaN,NaN,NaN,NaN,NaN,KE,7799
668,2011_RE_0670,8/11/2011,researcher_4,site_41,creek,net,fisher_892,site_118,species_2,site_108,KE7799,None,NaN,NaN,NaN,37.7,32.5,6.50,NaN,several small barnacles on the plastron(removed)&green algae/ pink algae on the plastron too& thick green algae on on carapace,NaN,NaN,NaN,NaN,NaN,NaN,KE,7799
1064,2011_RE_1068,11/5/2011,researcher_9,site_115,ocean,net,fisher_1048,site_118,species_2,site_62,KE7799,None,NaN,NaN,NaN,39.4,34.3,7.50,NaN,Thick green and brown algae on the carapace and plastron.Brown patches of calcareous algae on the scutes.,Released,11/5/2011,NaN,NaN,NaN,NaN,KE,7799
1088,2011_RE_1092,11/11/2011,researcher_4,site_53,ocean,net,fisher_1278,site_6,species_2,site_73,KE7799,None,NaN,NaN,NaN,39.4,34.1,7.25,NaN,Green algae and brown algae on the scutes.Few patches of calcareous algae on the scutes.Green algae on the plastron.,Released,11/11/2011,NaN,NaN,NaN,NaN,KE,7799
1139,2011_RE_1143,11/21/2011,researcher_4,site_38,ocean,net,fisher_777,site_118,species_2,site_62,KE7799,None,NaN,NaN,NaN,39.4,34.6,7.50,NaN,"Pink calcareou algae on carapace.Very thick green algae on carapace.few barnacles on rear flippers.Medium thick green algae,pink and white calcareous algae on the plastron.Few barnacles on the plastron.Bruising on both front flippers near shoulder.",Released,11/21/2011,NaN,NaN,NaN,NaN,KE,7799
1223,2011_RE_1227,12/3/2011,researcher_4,site_41,creek,net,fisher_1051,site_118,species_2,site_62,KE7799,None,NaN,NaN,NaN,39.7,33.7,7.50,NaN,Green algae on the carapace. Patches of white calcareous algae on the carapace.,Released,12/3/2011,NaN,NaN,NaN,NaN,KE,7799

In [61]:
variable_definitions

,Variables,Description
0,Rescue_ID,"It’s an individual bycatch incidence identity number. The numbers are consecutive, for each year e.g. 2018_RE_0732 means rescue number 732 in year 2018"
1,Date_Caught,Date and time the turtle is captured e.g. 06/01/2018 17:00pm
2,Researcher,Name of bycatch officer(s) involved with specific rescue
3,Capture Site,"Area where turtle was captured, as reported by the fisher."
4,Foraging Ground,General area of ocean area where turtle was captured. The assumption is that the turtle was foraging where it was captured. The foraging area is broadly classified either as the open ocean or creek section
5,Capture Method,Fishing gear or method used by fishers to capture the turtle
6,Fisher,Name of the fisher who captured the turtle
7,Landing_Site,Section of beach where turtle is landed.
8,Species,"Species of turtle (e.g. green turtle, hawksbill, loggerhead etc.)"
9,Tag_1,"Individual / unique number used to identify a turtle. Each turtle that is captured is tagged. Formats of tag numbers have been changed over years, although turtles retain their old tags even when recaptured (unless the tags are about to fall or are too tight, then they are replaced)."
10,Tag_2,Second tag added to large turtles. Turtles with two tags: tag 1 is an odd number e.g. KEL0169 and tag 2 is even and consequent e.g. KEL0170
11,Lost_Tags,"Replaced tags. If a turtle has outgrown its tag, the tag is removed and replaced with a bigger one, with a different number"
12,T_Number,"It a number given to a turtle that has been taken to the rehabilitation facility (TRC) for treatment. TRC identifies patients using T number, instead of “Rescue ID”. Thus, “T number” is the link between bycatch and TRC"
13,CCL_cm,Central Carapace Length (Biometric measurement). Measured in centimetres
14,CCW_cm,Central Carapace Width (Biometric measurement). Measured in centimetres
15,Weight_Kg,(Biometric measurement). Measured in Kgs
16,Sex,Gender of the turtle.
17,Turtle Characteristics,"Description of turtles (mostly unusual occurrences e.g. disease, injury, parasites etc. Usually as short textual description"
18,Status,Indicates whether the turtle is released or admitted to TRC
19,Release Site,Site where the turtle is released
20,Date_Release,Date turtle is released
21,Release_Admiss_Notes,Additional information about release
22,SpecialRemarks,Additional info (General) about turtle

In [46]:
test_data.SpecialRemarks.value_counts()

Fibropapillomatosis    5
Name: SpecialRemarks, dtype: int64

In [47]:
dirty_data.SpecialRemarks.value_counts()

NOWAY                                                                                                                                               4244
Fibropapillomatosis                                                                                                                                 22
NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.    15
NOTE (06/10/2017): Lost tags KE1839, KE1966 and 3264.                                                                                               7
NOTE (06/10/2017): tag KE1510 was removed & replaced by 3525 on 10/06/2008..                                                                        1
NOTE 06/10/2017): CCL too large compared to other measurements! CAUTION!                                                                            1
NOTE (06/10/2017): tag KE1510 was deplyed on a hawksbill                                                                                            1
NOTE (05/10/2017) tag 3231 lost between 10/05/2008-18/11/2008                                                                                       1
Name: SpecialRemarks, dtype: int64

In [48]:
cleaned_data.SpecialRemarks.value_counts()

NOWAY                                                                                                                                                                                                                                                4223
Fibropapillomatosis                                                                                                                                                                                                                                  20
NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.                                                                                                     15
NOTE (06/10/2017): Lost tags KE1839, KE1966 and 3264.                                                                                                                                                                                                7
NOTE 09/04/2018: Check with TRC records                                                                                                                                                                                                              2
Fibropapillomatosis. NOTE 05/04/2018: turtle released? Or died? Check with TRC records                                                                                                                                                               1
Polly                                                                                                                                                                                                                                                1
NOTE 09/04/2018: tag number in dta book recorded wrong. Correct tag number unknown                                                                                                                                                                   1
Hatchling                                                                                                                                                                                                                                            1
Tag removed, too small. 4879 replaced by KE7514. NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used.                                                                                           1
NOTE 09/04/2018: Check with TRC records. Strange tag numbersäó_                                                                                                                                                                                      1
NOTE (05/10/2017) tag 3231 lost between 10/05/2008-18/11/2008                                                                                                                                                                                        1
NOTE (06/10/2017): tag KE1510 was deplyed on a hawksbill                                                                                                                                                                                             1
NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used. Tag KE7508 broke during application.                                                                                                       1
Found dying on the beach the next day & put out of its misery.                                                                                                                                                                                       1
Found dead on 15/10/1999.                                                                                                                                                                                                                            1
Tag replaced today: KE5565 on LRF replaced with KE5675 on RRF.                                                                                                                                                                                       1
NOTE 12/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used. Tag KE7505 broke during application.                                                                                                       1
NOTE 09/04/2018: Overlapping tag numbers --> a 681IC and a 49 Monel version of this tag number were used.                                                                                                                                            1
NOTE 25/04/2018: Tag KE5903 lost, replaced with KE8119 (large tag) on 27/09/2012.                                                                                                                                                                    1
NOTE 05/04/2018: no release date or time recorded                                                                                                                                                                                                    1
NOTE 05/04/2018: Fibropapillomatosis? Unsure if admitted --> check with TRC records.                                                                                                                                                                 1
NOTE 06/10/2017): CCL too large compared to other measurements! CAUTION!                                                                                                                                                                             1
NOTE 25/04/2018: No record of this in any data book but may be a "straight to TRC" case, check with TRC records.                                                                                                                                     1
NOTE 05/04/2018: Strange notes about turtle dying, no record of that in BCRP data book. Check with mortality records.                                                                                                                                1
NOTE 09/04/2018: Check on release date with TRC records!                                                                                                                                                                                             1
The turtle was released the next day after feeding but the turtle didn't swim away, it floated - it did some light swimming with the current. It looked very sick and weak although it wasn't emaciated - possibly severely stressed from capture    1
NOTE (06/10/2017): tag KE1510 was removed & replaced by 3525 on 10/06/2008..                                                                                                                                                                         1
NOTE 25/04/2018: Overlapping tag numbers, this tag is actually "KE7515"                                                                                                                                                                              1
NOTE 05/04/2018: FP Patient, check TRC number in records                                                                                                                                                                                             1
Name: SpecialRemarks, dtype: int64

In [25]:
# Pause SpecialRemarks and work on Lost_Tag

#### Lost_Tags

In [72]:
Tag_1

     dirt          clean
id
0     Missing data  NotTagged_0001
121   CC00192       KE0768
136   CC00198       KE0371
183   301           KE0301
189   KE0314        KE0304
545   KES 0838      KE0838
3217  4879          KEB7514
3579  KE5565        KE5675
3733  5549          KE5549
3736  6648          KE5548
3764  KE5565        Missing Data
3794  KEB7504       KEB7503
3795  KE5577        KE7799
3802  KE5081        5081
3808  KE5653        KE5663
3818  KE5617        KE5717
3929  KE7514        KEB7514
3958  KE7515        KEB7515
4002  KE5419        5419
4039  KE4108        4108
4054  5708          KE5708
4055  KE5397        5397
4075  KE7520        KEB7520
4115  KE4894        4894
4131  KE8119        KEB8119
4182  KE5956        missing data
4185  KE7533        KEB7533
4200  KE5397        5397
4232  KE5950        KEB7584
4255  KE5963        KE6451
4261  KE5963        KE6451
4287  KE6161        missing data

In [33]:
## Find Tag_1 with  Lost_Tag value in the clean data
## Ensure that this Tag_1 have Lost_Tag value in test, else fish those without as a wrong value
# Get 
Lost_clean = cleaned_data.loc[cleaned_data.Lost_Tags != 'NOWAY'].Tag_1.tolist()
Lost_test = test_data.loc[test_data.Lost_Tags != 'NOWAY'].Tag_1.tolist()

In [34]:
# Tag_1 value with a valid Lost_tag in test and clean
intercept_of_Lost_test_clean = [x for x in set(Lost_test) if  x in set(Lost_clean)]
# only 3 Tag_1 intercepts with just 2 Tag_1 with wrong values

#### Check if Lost_Tag 's value in test is different from value in clean

In [37]:
# check for tag_1 of clean and test lost_tag intercept
df_intercept_Lost_Tag_test_clean = test_data.loc[test_data.Tag_1.isin(intercept_of_Lost_test_clean)].sort_values(by='Tag_1')
# Get Dataframe of lost_Tag with null values in test and valid value in clean
df_wrong_Lost_Tag_nan = df_intercept_Lost_Tag_test_clean.loc[df_intercept_Lost_Tag_test_clean.Lost_Tags.isnull()]

### Check through Tag_1 in test that uses Lost_Tag as Tag_1

In [107]:
## from the cleaned , rows that uses Lost_tag as Tag_1 all seems to have a wrong tag_1 value

In [108]:
# Give those values wrong tag
df_wrong_Lost_Tag_in_Tag_1 = df_wrong_Tag_1_in_Lost_Tag.copy()

In [15]:
Species

     dirt       clean
id
354   species_1  species_2
366   species_1  species_2
488   species_1  species_2
743   species_2  species_1
1008  species_1  not_recorded
1115  species_1  species_2
1509  species_1  not_recorded
1700  species_1  species_2
1762  species_1  species_2
2027  species_1  not_recorded
2300  species_1  species_2
2911  species_1  species_2
3019  species_1  species_2
3020  species_1  species_2
3143  species_1  species_2
3490  species_1  species_2
3844  species_1  species_2
4100  species_1  species_2

###### Species

In [14]:
Species
# Most dirty species value are Species_1
# how do i clean this value
# Check for Tag_1 values that intercept in clean and test
# check if the value the species value in clean is same as test
cleaned_data.loc[Species.index]

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Lost_Tags,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks
id,,,,,,,,,,,,,,,,,,,,,,
354,2001_RE_0235,12/6/2001,researcher_17,site_38,ocean,net,fisher_1270,site_118,species_2,site_108,KE0701,None,NOWAY,33.9,39.5,NOWAY,Unknown,calcerous +green algae to centre +rear,Released,12/6/2001,NOWAY,NOWAY
366,2001_RE_0247,12/15/2001,researcher_9,site_120,ocean,net,fisher_1119,site_120,species_2,site_81,KE0710,None,NOWAY,41.5,38.2,NOWAY,Unknown,calcerous +green algae patches especially to rear,Released,12/15/2001,NOWAY,NOWAY
488,2002_RE_0097,7/9/2002,researcher_14,site_33,creek,net,fisher_644,site_110,species_2,site_80,KE0785,None,NOWAY,75.5,69,NOWAY,Unknown,very beautiful shell+ clean+ 2 LMS has a couple of very small b's,Released,7/9/2002,NOWAY,NOWAY
743,2003_RE_0056,3/6/2003,researcher_17,site_13,ocean,net,fisher_953,site_120,species_1,site_116,KE1038,None,NOWAY,52.6,49,NOWAY,Unknown,2RLS 2 large bs and severla small bs; scratshed 2+3LLS; 9+11RMS small chips; sm bs on flips,Released,NOWAY,NOWAY,NOWAY
1008,2003_RE_0321,8/11/2003,researcher_17,site_20,creek,net,fisher_181,site_118,not_recorded,site_80,KE1288,None,NOWAY,45,44.5,NOWAY,Unknown,a few sm bs scattered on shell; 1Green Turtle superficila scute damage 4RLS; sm scale missingRFF shoulder,Released,NOWAY,NOWAY,NOWAY
1115,2003_RE_0428,9/29/2003,researcher_17,site_92,ocean,beached,fisher_828,site_120,species_2,not_recorded,NotTagged_0152,None,NOWAY,41.7,38.2,NOWAY,Unknown,heavy cobverings of algaes on shell and flips& very emcaiated& DIED 1/10,NOWAY,NOWAY,not released,NOWAY
1509,2004_RE_0278,9/22/2004,researcher_9,not_recorded,ocean,net,not_recorded,site_120,not_recorded,site_80,NotTagged_0156,None,NOWAY,25.4,23.5,NOWAY,Unknown,Turtle sent to Rehab& later released. Flippers to small to tag1/3 of RFFfrom the tip is damaged from entangled in sack& swollen + pale in color& Black tar on 5th + 6th RMS + 2nd RLS + on the rear part of the plastron.,Released,9/23/2004,NOWAY,NOWAY
1700,2005_RE_0012,1/15/2005,researcher_9,site_7,ocean,net,fisher_1345,site_120,species_2,site_5,KE1693,None,NOWAY,73,67.1,NOWAY,Unknown,Pink calcereous algae on both 9th MS& white calcereou algae on 4th LLS and on 5th CS& small Bs on FFs and RF& Neck and shoulders&some calcereous algae on plastron& brown algae on 5th CS& both 11th MS and both SC.,Released,NOWAY,NOWAY,NOWAY
1762,2005_RE_0074,3/19/2005,researcher_9,site_35,creek,net,fisher_1287,site_58,species_2,site_80,NotTagged_0159,None,NOWAY,5.6,5.2,NOWAY,Unknown,"Healthy, post hatchling",Released,NOWAY,NOWAY,NOWAY
2027,2005_RE_0339,10/10/2005,researcher_9,site_53,creek,net,fisher_861,site_8,not_recorded,site_80,KE1853,None,NOWAY,42.5,41.9,NOWAY,Unknown,Small notch in No. 8 LM. 1 B on carapace. Flaking on all Scutes.,Released,NOWAY,NOWAY,NOWAY
2300,2006_RE_0170,7/8/2006,researcher_9,site_33,creek,net,fisher_930,site_58,species_2,site_80,KE3030,None,NOWAY,33,30.5,NOWAY,Unknown,Cut LRF,Released,NOWAY,NOWAY,NOWAY
2911,2007_RE_0376,9/9/2007,researcher_9,site_13,ocean,net,fisher_848,site_120,species_2,site_73,3263,None,NOWAY,34.8,32.3,NOWAY,Unknown,Pinkish patches of calcereous algae on shell. Barnacles on plastron.,Released,NOWAY,NOWAY,NOWAY
3019,2007_RE_0484,11/9/2007,researcher_9,site_38,ocean,net,fisher_400,site_118,species_2,site_80,3315,None,NOWAY,35.7,32.5,NOWAY,Unknown,Grey algae on rear shell. The 8th RMS is small.,Released,NOWAY,NOWAY,NOWAY
3020,2007_RE_0485,11/9/2007,researcher_9,site_38,ocean,net,fisher_400,site_118,species_2,site_80,3316,None,NOWAY,36.7,35.1,NOWAY,Unknown,6CS. Pale carapace. Pinkish calcereous algae on rear scutes.,Released,NOWAY,NOWAY,NOWAY
3143,2007_RE_0608,12/22/2007,researcher_23,site_119,ocean,net,fisher_377,site_118,species_2,site_80,3374,None,NOWAY,40.4,38.6,NOWAY,Unknown,Notch in No. 9+10 RM. Notch between No. 11 RM + RSC. Notch in No. 10 + 11 LM. Pink calcereous algae on carapace. Red algae turf on carapace.,Released,NOWAY,NOWAY,NOWAY
3490,2010_RE_0333,4/15/2010,researcher_4,site_38,ocean,net,fisher_570,site_118,species_2,site_62,KE5516,None,NOWAY,36.4,35.5,NOWAY,NOWAY,Flaking tips of scutes& green algae on carapace& muddy towards rear shell& numerous small barnacles around neck and shoulders& patch of whitish algae on 3rd LR scute& tips of both FFs missing& greenish algae and barnacles on plastron,NOWAY,NOWAY,NOWAY,NOWAY
3844,2010_RE_0687,8/30/2010,researcher_4,site_7,ocean,net,fisher_1313,site_120,species_2,site_80,KE5733,None,NOWAY,34.8,35,5,NOWAY,Green algea on the rear shell.Green algea on the plastron.Few barnacles on the plastron(removed).,NOWAY,NOWAY,NOWAY,NOWAY
4100,2010_RE_0949,11/19/2010,researcher_4,site_115,ocean,net,fisher_1142,site_118,species_2,site_73,KE5645,None,NOWAY,34.4,32.1,5.5,NOWAY,thick green algae on carapace. Calcereous algae on carapace. Light green algae on plastron. Reddish brown algae on neck and carapace.,NOWAY,NOWAY,NOWAY,NOWAY

In [17]:
intercept_tag_1_clean_test = [x for x in set(cleaned_data.loc[cleaned_data.Tag_1!= 'NOWAY'].Tag_1.tolist())if x in set(test_data.loc[test_data.Tag_1 != 'None'].Tag_1.tolist())]

In [27]:
cleaned_data[cleaned_data.Tag_1.isin(intercept_tag_1_clean_test)].Tag_1.sort_values()

3618    3325
3041    3325
3321    3344
4238    3344
3083    3344
3393    3351
3093    3351
3117    3360
3663    3374
3143    3374
3149    3375
3155    3382
3196    3393
3314    3591
3201    3612
4053    3612
3464    3828
4028    3828
3515    3828
3348    3828
4036    3828
3613    3828
3454    3828
3396    3828
3641    3828
3854    3828
3894    3828
3801    3828
3987    3828
2908    3848
        ...
4174    KE5924
4201    KE5936
4206    KE5938
4205    KE5939
4278    KE5939
4210    KE5941
4277    KE5941
4224    KE5948
4228    KE5949
4233    KE5951
4239    KE5955
4252    KE5960
4248    KE5961
4273    KE5968
3751    KE6333
4255    KE6451
4261    KE6451
4098    KE7523
3611    KE7799
3795    KE7799
3850    KE7799
3759    KE7799
3630    KE7799
3887    KE7799
4213    KE7799
4229    KE7799
3589    KE7799
3647    KE7799
4274    KEB7535
4197    KEB7535
Name: Tag_1, Length: 279, dtype: object

In [28]:
test_data[test_data.Tag_1.isin(intercept_tag_1_clean_test)].Tag_1.sort_values()

1267    3325
125     3344
1004    3344
433     3351
72      3360
1217    3374
190     3375
224     3382
71      3382
311     3382
304     3393
800     3591
53      3612
1066    3612
1224    3828
227     3828
149     3828
41      3828
347     3828
13      3848
124     3991
974     3991
383     4013
1234    4013
533     4026
151     4061
518     4082
219     4082
215     4087
413     4858
        ...
419     KE5941
1190    KE5948
380     KE5948
326     KE5949
1033    KE5949
1259    KE5949
111     KE5951
136     KE5955
616     KE5960
423     KE5960
808     KE5960
88      KE5961
598     KE5961
1242    KE5968
175     KE5968
509     KE6333
960     KE6451
94      KE7523
263     KE7799
601     KE7799
1139    KE7799
668     KE7799
508     KE7799
1223    KE7799
348     KE7799
1064    KE7799
360     KE7799
1088    KE7799
42      KE7799
12      KEB7535
Name: Tag_1, Length: 254, dtype: object

In [14]:
# Get all values of Date_Caught in both train an test
  
# lemme check the difference in between the two columns
# in order to check the difference, i need to convert the datatype to datetime64  inorder to perform operation on it.
Date_Caught.dirt = pd.to_datetime(Date_Caught.dirt)
Date_Caught.clean = pd.to_datetime(Date_Caught.clean)

# After converting, leme check the differece and store in a column
Date_Caught['difference'] = Date_Caught.clean - Date_Caught.dirt


# Check yur new df now
Date_Caught.sort_values(by='difference')

C:\Users\Bless\Anaconda3\lib\site-packages\pandas\core\generic.py:4405: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value
C:\Users\Bless\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.

     dirt       clean      difference
id
2013 2005-10-01 2005-09-29 -2 days
2668 2007-03-27 2007-03-25 -2 days
2188 2006-02-21 2006-02-19 -2 days
620  2002-11-01 2002-10-30 -2 days
2031 2005-10-11 2005-10-10 -1 days
2527 2006-12-28 2006-12-27 -1 days
2515 2006-12-23 2006-12-22 -1 days
2514 2006-12-23 2006-12-22 -1 days
2513 2006-12-22 2006-12-21 -1 days
2510 2006-12-21 2006-12-20 -1 days
2508 2006-12-21 2006-12-20 -1 days
2507 2006-12-21 2006-12-20 -1 days
2506 2006-12-21 2006-12-20 -1 days
2504 2006-12-20 2006-12-19 -1 days
2501 2006-12-19 2006-12-18 -1 days
2475 2006-12-06 2006-12-05 -1 days
2474 2006-12-06 2006-12-05 -1 days
2473 2006-12-06 2006-12-05 -1 days
2455 2006-11-28 2006-11-27 -1 days
2446 2006-11-21 2006-11-20 -1 days
2445 2006-11-21 2006-11-20 -1 days
2444 2006-11-20 2006-11-19 -1 days
2443 2006-11-20 2006-11-19 -1 days
2442 2006-11-20 2006-11-19 -1 days
2528 2006-12-29 2006-12-28 -1 days
2529 2006-12-29 2006-12-28 -1 days
2539 2007-01-03 2007-01-02 -1 days
2433 2006-11-17 2006-11-16 -1 days
2619 2007-02-24 2007-02-23 -1 days
2618 2007-02-23 2007-02-22 -1 days
...         ...        ...     ...
1769 2005-03-20 2005-03-19 -1 days
1815 2005-04-17 2005-04-16 -1 days
1644 2004-12-15 2004-12-14 -1 days
1645 2004-12-15 2004-12-14 -1 days
1814 2005-04-17 2005-04-16 -1 days
1812 2005-04-17 2005-04-16 -1 days
1811 2005-04-17 2005-04-16 -1 days
1806 2005-04-16 2005-04-15 -1 days
1805 2005-04-15 2005-04-14 -1 days
1804 2005-04-15 2005-04-14 -1 days
1658 2004-12-19 2004-12-18 -1 days
1803 2005-04-14 2005-04-13 -1 days
1801 2005-04-14 2005-04-13 -1 days
1800 2005-04-14 2005-04-13 -1 days
1786 2005-04-01 2005-03-31 -1 days
1785 2005-04-01 2005-03-31 -1 days
1646 2004-12-15 2004-12-14 -1 days
1784 2005-04-01 2005-03-31 -1 days
1782 2005-03-30 2005-03-29 -1 days
1647 2004-12-16 2004-12-15 -1 days
1770 2005-03-20 2005-03-19 -1 days
1802 2005-04-14 2005-04-13 -1 days
1652 2004-12-17 2004-12-16 -1 days
3222 2010-01-23 2010-01-24 1 days
1868 2005-05-16 2005-05-17 1 days
2441 2006-11-18 2006-11-19 1 days
2440 2006-11-18 2006-11-19 1 days
3866 2010-09-08 2010-09-09 1 days
0    1998-04-14 1998-04-17 3 days
920  2003-07-01 2003-07-30 29 days

[407 rows x 3 columns]

In [111]:
df_no_wong_cols

   column                  num_of_dirty
10  Tag_2                  5
7   Species                18
19  Release_Admiss_Notes   23
11  Lost_Tags              24
20  SpecialRemarks         25
9   Tag_1                  32
14  Weight_Kg              47
1   Researcher             58
6   LandingSite            69
4   CaptureMethod          132
2   CaptureSite            154
3   ForagingGround         193
12  CCL_cm                 243
8   ReleaseSite            245
13  CCW_cm                 316
5   Fisher                 392
0   Date_Caught            407
16  TurtleCharacteristics  574
18  Date_Release           681
17  Status                 2990
15  Sex                    3166

In [156]:
# Get all values of Date_Caught in both train an test
# Check yur new df now
print ('Wrong values in Date_Released', len(Date_Released))

Wrong values in Date_Released 681

###### Researcher

In [16]:
# most incorrect research values are researcher_14, 4 and 17 12, 1, 1
# most corrected values ar 15, 9, 18
Researcher.clean.value_counts()
# what causes this discrepancies in this value. why did it happen?
print ('Wrong values in Researcher', len(Researcher))

Wrong values in Researcher 58

###### CaptureSite

In [17]:
# Site_53 and not_recorded is toping this chat.
CaptureSite.dirt.value_counts()
# i can investigate 'not_recorded' further more 
# not_recorded is mostly replaced by 8 and 58
# CaptureSite.loc[CaptureSite.dirt == 'not_recorded']
print ('Wrong values in CaptureSite', len(CaptureSite))

Wrong values in CaptureSite 154

###### ForagingGround

In [18]:
ForagingGround.dirt.value_counts()
# Most wrong values are 'ocean'
print ('Wrong values in ForagingGround', len(ForagingGround))

Wrong values in ForagingGround 193

###### CaptureMethod

In [19]:
CaptureMethod.dirt.value_counts()
# Most wrong values are 'net'
# CaptureMethod
print ('Wrong values in CaptureMethod', len(CaptureMethod))

Wrong values in CaptureMethod 132

###### Fisher

In [13]:
Fisher.dirt.value_counts()
# Most wrong values are 'fisher_1385' and 'fisher_815'
# Fisher
print ('Wrong values in Fisher', len(Fisher))

Wrong values in Fisher 392

###### LandingSite

In [14]:
LandingSite.dirt.value_counts()
# LandingSite.clean.value_counts()
# Most wrong values are 'Site_8' 
# LandingSite
print ('Wrong values in LandingSite', len(LandingSite))

Wrong values in LandingSite 69

###### Species

Wrong values in Species 18

###### ReleaseSite

In [26]:
ReleaseSite.dirt.value_counts()
ReleaseSite.clean.value_counts()
print ('Wrong values in ReleaseSite', len(ReleaseSite))
# Most wrong values are 'fisher_1385' and 'fisher_815'
# ReleaseSite

Wrong values in ReleaseSite 245

###### Tag_1

In [20]:
Tag_1.dirt.value_counts()
# Tag_1.clean.value_counts()
# Most wrong values are 'fisher_1385' and 'fisher_815'
Tag_1
print ('Wrong values in Tag_1', len(Tag_1))

Wrong values in Tag_1 32

###### Tag_2

###### Lost_Tags

In [21]:
Lost_Tags.dirt.value_counts()
# Lost_Tags.clean.value_counts()
# Most wrong values are 'fisher_1385' and 'fisher_815'
print ('Wrong values in Lost_Tags', len(Lost_Tags))

Wrong values in Lost_Tags 24

###### CCL_cm

In [22]:
CCL_cm.dirt.value_counts()
# CCL_cm.clean.value_counts()

# Most wrong values are 'fisher_1385' and 'fisher_815'
print ('Wrong values in CCL_cm', len(CCL_cm))

Wrong values in CCL_cm 243

###### CCW_cm

In [23]:
CCW_cm.dirt.value_counts()
CCW_cm.clean.value_counts()

# Most wrong values are 'fisher_1385' and 'fisher_815'
# CCW_cm
print ('Wrong values in CCW_cm', len(CCW_cm))

Wrong values in CCW_cm 316

###### Weight__Kg

In [24]:
Weight_Kg.dirt.value_counts()
Weight_Kg.clean.value_counts()

# Most wrong values are 'fisher_1385' and 'fisher_815'
print ('Wrong values in Weight_Kg', len(Weight_Kg))

Wrong values in Weight_Kg 47

###### Sex

In [25]:
Sex.dirt.value_counts()
Sex.clean.value_counts()

# Most wrong values are 'fisher_1385' and 'fisher_815'
# Sex
print ('Wrong values in Sex', len(Sex))

Wrong values in Sex 3166

###### TurtleCharacteristics

In [23]:
TurtleCharacteristics.dirt.value_counts()
# TurtleCharacteristics.clean.value_counts()

# Most wrong values are 'fisher_1385' and 'fisher_815'
TurtleCharacteristics
print ('Wrong values in TurtleCharacteristics', len(TurtleCharacteristics))

Wrong values in TurtleCharacteristics 611

###### Status

In [19]:
# Status.dirt.value_counts()
Status.clean.value_counts()

# Most wrong values are 'NA'
# Status
print ('Wrong values in Status', len(Status))
Status.dirt.value_counts()

Wrong values in Status 2990

NOWAY    2990
Name: dirt, dtype: int64

###### Date_Release

In [26]:
Date_Release.dirt.value_counts()
# Date_Release.clean.value_counts()

# Most wrong values are 'fisher_1385' and 'fisher_815'
# Date_Release
print ('Wrong values in Date_Release', len(Date_Release))

Wrong values in Date_Release 681

###### Release_Admiss_Notes

In [15]:
Release_Admiss_Notes.dirt.value_counts()
Release_Admiss_Notes.clean.value_counts()

# Most wrong values are 'fisher_1385' and 'fisher_815'
# Release_Admiss_Notes
print ('Wrong values in Release_Admiss_Notes', len(Release_Admiss_Notes))

Wrong values in Release_Admiss_Notes 23

In [25]:
Date_Caught.difference.value_counts()
# Most date are actually recorded the day after the actual date
Date_Caught.loc[Date_Caught.difference != '-1 days']

# why is this so??? 
# How do this guys know that the date caught is not correct.

     dirt       clean      difference
id
0    1998-04-14 1998-04-17 3 days
620  2002-11-01 2002-10-30 -2 days
920  2003-07-01 2003-07-30 29 days
1868 2005-05-16 2005-05-17 1 days
2013 2005-10-01 2005-09-29 -2 days
2188 2006-02-21 2006-02-19 -2 days
2440 2006-11-18 2006-11-19 1 days
2441 2006-11-18 2006-11-19 1 days
2668 2007-03-27 2007-03-25 -2 days
3222 2010-01-23 2010-01-24 1 days
3866 2010-09-08 2010-09-09 1 days

In [29]:
cleaned_data.loc[Date_Caught.loc[Date_Caught.difference != '-1 days'].index]

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Lost_Tags,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks
id,,,,,,,,,,,,,,,,,,,,,,
0,1998_RE_0001,4/17/1998,researcher_19,site_110,creek,net,fisher_619,site_58,species_1,site_80,NotTagged_0001,None,NOWAY,63.5,58.42,NOWAY,Unknown,NOWAY,Released,4/17/1998,NOWAY,NOWAY
620,2002_RE_0229,10/30/2002,researcher_18,site_33,creek,net,fisher_150,site_8,species_1,site_87,KA476,None,NOWAY,40.4,38.8,NOWAY,Unknown,B's: 2- 3 CS+ 1- 4RLS+ 1 (small)- 5 CS+ 1 (small) 2 LLS. Old b scar 9 LMS and between 11 RMS + right supra. RRF has notch out of it.,Released,11/1/2002,NOWAY,NOWAY
920,2003_RE_0233,7/30/2003,researcher_14,site_53,creek,net,fisher_341,site_8,species_1,site_116,KA453,None,NOWAY,44.5,42.1,NOWAY,Unknown,small b on the 2RLS &3CS&a notch on the RRF&1 small b on the left side of the prefrontal scale & left side of the mouth&light green algae smear on the 3RLS,Released,NOWAY,NOWAY,NOWAY
1868,2005_RE_0180,5/17/2005,researcher_9,site_33,creek,net,fisher_624,site_12,species_1,site_80,KE1749,None,NOWAY,48.4,45.5,NOWAY,Unknown,3 Bs on the plastron + huge colony of Bs on L part of the carapace.,Released,NOWAY,NOWAY,NOWAY
2013,2005_RE_0325,9/29/2005,researcher_9,site_53,creek,net,fisher_861,site_8,species_1,site_87,3398,None,KE1805,40.4,40.4,NOWAY,Unknown,Shell begins to flake. Few Bs on plastron.,Released,NOWAY,NOWAY,"NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398."
2188,2006_RE_0058,2/19/2006,researcher_7,site_35,creek,longline,fisher_629,site_58,species_1,not_recorded,3579,None,KE1845,41.7,40.2,NOWAY,Unknown,B on both 10th MS& 6th RMS + Head Right Side. Notches 5th + 6th RMS& Notches 5th and 5th LMS + SCL. B scars on 3rd RMS and on 4th CS. Flaking on 2nd CS.,Not_Recorded,NOWAY,NOWAY,NOWAY
2440,2006_RE_0310,11/19/2006,researcher_23,site_53,creek,net,fisher_861,site_8,species_1,site_80,KE2922,None,NOWAY,40.9,38.4,NOWAY,Unknown,Deep notch at centre of RRF. Notch in LSC. Flaking on all scutes.,Released,NOWAY,NOWAY,NOWAY
2441,2006_RE_0311,11/19/2006,researcher_23,site_53,creek,net,fisher_861,site_8,species_1,site_80,3579,None,KE1845,44.2,41.7,NOWAY,Unknown,Notch between No. 9 and 10 LM. 2 small barnacles on carapace. Notch between No. 10 and 11 RM. Hook lodged at shoulder joint of LFF. Hook already there when netted.,Released,NOWAY,NOWAY,NOWAY
2668,2007_RE_0133,3/25/2007,researcher_9,site_36,creek,longline,fisher_669,site_58,species_1,site_80,KE1937,None,NOWAY,51.1,46.1,NOWAY,Unknown,Loss of 1/2 RF flipper + tip of LFF. Notch on middle of RF.,Released,NOWAY,NOWAY,NOWAY
3222,2010_RE_0065,1/24/2010,researcher_4,site_53,creek,net,fisher_703,site_8,species_1,site_80,NotTagged_0291,None,NOWAY,41.7,41.4,NOWAY,NOWAY,Small barnacles on carapace and plastron. Tip of LFF and RRF missing. Flake btw 1st and 2nd& 2nd and 3rd RLS.,NOWAY,1/25/2010,NOWAY,NOWAY
3866,2010_RE_0709,9/9/2010,researcher_4,site_33,creek,net,fisher_1007,site_8,species_1,site_81,KE5746,None,NOWAY,70,61.6,38.5,NOWAY,Small additional scute between 1st and 2nd Cs.Several barnacles on the carapace(removed).Flakings in the 2nd&4th&5th Cs & 2nd LLS 10th and 11th LMS.Small tagrip in the RRF.Green algea on the carapace.Flaking plastron but generally clean.Hole in the LRF.,NOWAY,NOWAY,Caught the day before,NOWAY

In [30]:
cleaned_data.Researcher.value_counts()

researcher_9     1930
researcher_4     993
researcher_17    504
researcher_23    330
researcher_14    233
researcher_18    131
researcher_15    40
researcher_7     35
researcher_8     32
researcher_6     19
not_recorded     15
researcher_5     10
researcher_1     7
researcher_2     3
researcher_10    2
researcher_3     2
researcher_19    2
researcher_11    1
researcher_12    1
researcher_20    1
researcher_13    1
Name: Researcher, dtype: int64

In [31]:
cleaned_data.head(621)

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Lost_Tags,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks
0,1998_RE_0001,4/17/1998,researcher_19,site_110,creek,net,fisher_619,site_58,species_1,site_80,NotTagged_0001,None,NOWAY,63.5,58.42,NOWAY,Unknown,NOWAY,Released,4/17/1998,NOWAY,NOWAY
1,1998_RE_0002,7/7/1998,researcher_15,site_15,creek,longline,fisher_522,site_22,species_1,not_recorded,NotTagged_0002,None,NOWAY,48.26,36.83,NOWAY,Unknown,1B-1LLS,NOWAY,NOWAY,NOWAY,NOWAY
2,1998_RE_0003,8/3/1998,not_recorded,site_12,creek,not_recorded,fisher_1254,not_recorded,species_1,site_109,NotTagged_0003,None,NOWAY,44.45,33,NOWAY,Unknown,NOWAY,Released,8/3/1998,NOWAY,NOWAY
3,1998_RE_0004,8/7/1998,researcher_19,site_110,creek,not_recorded,fisher_360,not_recorded,species_2,site_108,NotTagged_0004,None,NOWAY,34.29,31.75,NOWAY,Unknown,There was pillings on carapace.,Released,8/7/1998,NOWAY,NOWAY
4,1998_RE_0005,9/25/1998,researcher_17,site_8,creek,collected floater,fisher_865,site_8,species_3,site_121,NotTagged_0005,None,NOWAY,68.58,63.5,NOWAY,Unknown,Bs on C+ old panga wounds,Released,9/25/1998,Found trapped in mangroves,NOWAY
5,1998_RE_0006,9/26/1998,researcher_17,site_8,creek,not_recorded,fisher_130,site_8,species_1,site_90,NotTagged_0006,None,NOWAY,34.29,30.5,NOWAY,Unknown,3 barnacles on plastron,Released,9/26/1998,NOWAY,NOWAY
6,1998_RE_0007,10/20/1998,researcher_15,site_8,creek,not_recorded,fisher_619,site_8,species_1,site_109,NotTagged_0007,None,NOWAY,47,43.18,NOWAY,Unknown,1B Lside,Released,10/20/1998,NOWAY,NOWAY
7,1998_RE_0008,11/7/1998,not_recorded,site_8,creek,not_recorded,fisher_217,site_8,species_1,not_recorded,NotTagged_0008,None,NOWAY,39.37,35.56,NOWAY,Unknown,NOWAY,NOWAY,NOWAY,NOWAY,NOWAY
8,1998_RE_0009,11/12/1998,not_recorded,site_8,creek,not_recorded,fisher_217,site_8,species_1,not_recorded,NotTagged_0009,None,NOWAY,45.72,43.18,NOWAY,Unknown,9 Bs,Released,11/12/1998,NOWAY,NOWAY
9,1998_RE_0010,11/12/1998,not_recorded,site_8,creek,not_recorded,fisher_929,site_8,species_1,not_recorded,NotTagged_0010,None,NOWAY,38.1,35.56,NOWAY,Unknown,LRF-piece missing,Released,11/12/1998,NOWAY,NOWAY
10,1998_RE_0011,11/18/1998,not_recorded,site_33,creek,not_recorded,fisher_529,not_recorded,species_1,not_recorded,NotTagged_0011,None,NOWAY,43.18,38.1,NOWAY,Unknown,top centre of C-crack+ 3Bs on C,NOWAY,NOWAY,NOWAY,NOWAY
11,1998_RE_0012,11/19/1998,not_recorded,site_33,creek,not_recorded,fisher_867,not_recorded,species_1,not_recorded,NotTagged_0012,None,NOWAY,NOWAY,NOWAY,NOWAY,Unknown,sm Bs on rear of C,NOWAY,NOWAY,NOWAY,NOWAY
12,1998_RE_0013,11/24/1998,researcher_11,site_113,creek,not_recorded,fisher_90,not_recorded,species_1,site_110,NotTagged_0013,None,NOWAY,43.18,40.64,NOWAY,Unknown,NOWAY,Released,11/24/1998,NOWAY,NOWAY
13,1998_RE_0014,11/25/1998,researcher_15,site_33,creek,not_recorded,fisher_85,not_recorded,species_1,not_recorded,NotTagged_0014,None,NOWAY,45.72,43.18,NOWAY,Unknown,Bs-2RLS & 4LLS,NOWAY,NOWAY,NOWAY,NOWAY
14,1998_RE_0015,12/5/1998,researcher_12,site_110,creek,not_recorded,fisher_861,not_recorded,species_1,not_recorded,NotTagged_0015,None,NOWAY,44.45,43.18,NOWAY,Unknown,NOWAY,Released,12/5/1998,NOWAY,NOWAY
15,1998_RE_0016,12/10/1998,researcher_6,site_58,creek,not_recorded,fisher_696,not_recorded,species_1,site_110,NotTagged_0016,None,NOWAY,43.18,38.1,NOWAY,Unknown,"R2 small puncture wounds, R3 small crack, rear central 2 cracks on scute.",Released,12/10/1998,NOWAY,NOWAY
16,1999_RE_0001,3/8/1999,researcher_6,site_58,creek,not_recorded,fisher_929,not_recorded,species_1,site_116,NotTagged_0017,None,NOWAY,55.88,53.34,NOWAY,Unknown,2 barnacles on plastron,Released,3/8/1999,NOWAY,NOWAY
17,1999_RE_0002,3/14/1999,researcher_17,site_58,creek,not_recorded,fisher_1182,not_recorded,species_1,site_110,NotTagged_0018,None,NOWAY,36.83,35.56,NOWAY,Unknown,2Bs front scute& 2Bs-4LLS& 1B each rear flips,Released,3/14/1999,NOWAY,NOWAY
18,1999_RE_0003,3/16/1999,researcher_6,site_110,creek,not_recorded,fisher_751,not_recorded,species_1,site_110,NotTagged_0019,None,NOWAY,43.18,40.64,NOWAY,Unknown,1B-head& 2Bs-1CS& Bs-1LLS & 2LLS& 2Bs-Lflip,Released,3/16/1999,NOWAY,NOWAY
19,1999_RE_0004,3/16/1999,researcher_17,site_12,creek,not_recorded,fisher_122,not_recorded,species_1,site_97,NotTagged_0020,None,NOWAY,41.91,38.1,NOWAY,Unknown,"Many small barnacles, dents/graze on plastron near neck",Released,3/16/1999,NOWAY,NOWAY
20,1999_RE_0005,3/24/1999,researcher_6,site_58,creek,not_recorded,fisher_1380,not_recorded,species_1,not_recorded,NotTagged_0021,None,NOWAY,48.89,39.37,NOWAY,Unknown,1B-1LLS & 1RLS & 3LLS& 2Bs-5CS,Released,3/24/1999,NOWAY,NOWAY
21,1999_RE_0006,4/3/1999,researcher_17,site_110,creek,not_recorded,fisher_122,not_recorded,species_1,not_recorded,NotTagged_0022,None,NOWAY,38.1,36.83,NOWAY,Unknown,Bs-2RLS& smBs-4CS& FRflip bent&,Released,4/3/1999,NOWAY,NOWAY
22,1999_RE_0007,4/28/1999,researcher_4,site_8,creek,not_recorded,fisher_98,not_recorded,species_1,site_88,NotTagged_0023,None,NOWAY,55.88,43.18,NOWAY,Unknown,NOWAY,Released,4/28/1999,NOWAY,NOWAY
23,1999_RE_0008,5/3/1999,researcher_17,site_110,creek,not_recorded,fisher_122,site_8,species_1,not_recorded,NotTagged_0024,None,NOWAY,49.53,43.18,NOWAY,Unknown,Bs on shell,Released,5/3/1999,NOWAY,NOWAY
24,1999_RE_0009,5/8/1999,researcher_17,site_58,creek,not_recorded,fisher_202,not_recorded,species_1,site_87,NotTagged_0025,None,NOWAY,43.18,40.64,NOWAY,Unknown,B-Lside head& 5Bs on shell,Released,5/8/1999,NOWAY,NOWAY
25,1999_RE_0010,5/14/1999,researcher_4,site_8,creek,not_recorded,fisher_619,not_recorded,species_1,site_90,NotTagged_0026,None,NOWAY,43.18,38.1,NOWAY,Unknown,Bs-1CS & 2CS,Released,5/14/1999,NOWAY,NOWAY
26,1999_RE_0011,5/22/1999,researcher_17,site_110,creek,not_recorded,fisher_122,not_recorded,species_1,site_110,H381,None,NOWAY,40.64,40.64,NOWAY,Unknown,Bs on shell& B-Lside of jaw,Released,5/22/1999,NOWAY,NOWAY
27,1999_RE_0012,5/24/1999,researcher_17,site_110,creek,not_recorded,fisher_153,not_recorded,species_2,site_110,NotTagged_0027,None,NOWAY,6.35,6.35,NOWAY,Unknown,RRflip 2 chunks missing,Released,5/24/1999,NOWAY,NOWAY
28,1999_RE_0013,5/24/1999,not_recorded,site_8,creek,not_recorded,fisher_929,site_58,species_2,site_108,H382,None,NOWAY,27.94,27.3,NOWAY,Unknown,NOWAY,Released,5/24/1999,NOWAY,NOWAY
29,1999_RE_0014,6/24/1999,researcher_17,site_8,creek,not_recorded,fisher_266,not_recorded,species_1,site_108,H383,None,NOWAY,39.17,39.17,NOWAY,Unknown,SmBs-2LLS& 3Bs Lprefrontal& 1B-each rear flip& 1B-9Lmarginal& 3B- rear marginal,Released,6/24/1999,NOWAY,Found dead on 15/10/1999.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,2002_RE_0200,10/18/2002,researcher_17,site_15,creek,beached,fisher_374,site_15,species_1,site_80,NotTagged_0120,None,NOWAY,39.1,39.1,NOWAY,Unknown,not tagged due to injuries+ turtle has been entangled in netting for a long period of time. RFF cut into near to shoulder-no bleeding+some scar tissue on surface+ LFF very swollen with bleeding near shoulder area+ blood has been cut off to the flipper+,Released,10/18/2002,NOWAY,NOWAY
592,2002_RE_0201,10/19/2002,researcher_17,site_53,creek,net,fisher_861,site_8,species_1,site_116,KA459,None,NOWAY,40.2,39.1,NOWAY,Unknown,4 small b's 2 LLS+ 1 b 3 CS + 3 LLS+ 2 b's 5 CS+ 2 b's 11 LMS+ chip out of end of LFF and net damage,Released,10/19/2002,NOWAY,NOWAY
593,2002_RE_0202,10/19/2002,researcher_17,site_120,ocean,collected floater,fisher_1256,site_13,species_1,site_80,NotTagged_0121,None,NOWAY,40,38,NOWAY,Unknown,has 5 lateral scutes to the left+ small b on 5 LLS+ turtle was too small to tag,Released,10/19/2002,NOWAY,NOWAY
594,2002_RE_0203,10/19/2002,researcher_17,site_119,ocean,net,fisher_588,site_118,species_1,site_80,KA461,None,NOWAY,43.3,40,NOWAY,Unknown,piece missing from RRF,Released,10/19/2002,NOWAY,NOWAY
595,2002_RE_0204,10/19/2002,researcher_17,site_119,ocean,net,fisher_588,site_118,species_2,site_80,KA460,None,NOWAY,36.8,33.7,NOWAY,Unknown,covered in white calcerous algae+ small b's on all flippers+ small scar on center of head,Released,10/19/2002,NOWAY,NOWAY
596,2002_RE_0205,10/19/2002,researcher_17,site_58,creek,net,fisher_1206,site_8,species_1,site_116,KE0843,None,NOWAY,41.5,40.9,NOWAY,Unknown,1 small b LFF and some damage at flipper top edge near end+ 1 small b 1 CS,Released,10/19/2002,NOWAY,NOWAY
597,2002_RE_0206,10/19/2002,researcher_17,site_53,creek,net,fisher_769,site_12,species_1,site_116,KA458,None,NOWAY,47.4,45,NOWAY,Unknown,1 b 4 LLS + 5 CS-killed+ chip between supra.+ 8 RMS + 2 RLS- superficial damage a small piece to scute+ 1 small b back and left side of head+ a few small b's to rear flippers+ RFF has a square end,Released,10/19/2002,NOWAY,NOWAY
598,2002_RE_0207,10/19/2002,researcher_17,site_120,ocean,collected floater,fisher_27,site_120,species_1,site_116,KA463,None,NOWAY,53.4,49.6,NOWAY,Unknown,white calcerous growth on supra.,Released,10/19/2002,NOWAY,NOWAY
599,2002_RE_0208,10/19/2002,researcher_17,site_120,ocean,collected floater,fisher_27,site_120,species_1,site_116,KA462,None,NOWAY,54.3,53.2,NOWAY,Unknown,chip between 11 RM and right supra.,Released,10/19/2002,NOWAY,NOWAY
600,2002_RE_0209,10/20/2002,researcher_17,site_6,ocean,collected floater,fisher_1309,site_120,species_1,site_80,NotTagged_0122,None,NOWAY,4.5,4.4,NOWAY,Unknown,hatchling- pretty fresh out of nest was found by a young man who saw children playing with it at the beach when it was trying to go to the water on Blue Bay Beach.,Released,10/20/2002,NOWAY,NOWAY
601,2002_RE_0210,10/20/2002,researcher_17,site_6,ocean,collected floater,fisher_1309,site_120,species_1,site_80,NotTagged_0123,None,NOWAY,4.5,4.4,NOWAY,Unknown,hatchling- pretty fresh out of nest was found by a young man who saw children playing with it at the beach when it was trying to go to the water on Blue Bay Beach.,Released,10/20/2002,NOWAY,NOWAY
602,2002_RE_0211,10/20/2002,researcher_6,site_58,creek,uzio,fisher_1118,site_58,species_1,site_116,KE0823,None,NOWAY,40,37,NOWAY,Unknown,no descriptions taken,Released,10/20/2002,NOWAY,NOWAY
603,2002_RE_0212,10/19/2002,researcher_17,site_58,creek,net,fisher_333,site_8,species_1,site_80,KA464,None,NOWAY,44.2,43,NOWAY,Unknown,b's caused problems in measuring+ large b's (38) all over shell- all were killed+ chip between 7-8 RMS+ large b on head-killed+ b's on underside-all killed+ flaking of scutes near edges,Released,10/20/2002,NOWAY,NOWAY
604,2002_RE_0213,10/21/2002,researcher_17,site_120,ocean,beached,fisher_1193,site_120,species_2,site_80,KA465,None,NOWAY,60.9,54.7,NOWAY,Unknown,They watched it for a while and they decided to bring it to the office. 3 CS has large b; many b's at joint between 1 LLS and marginals + 1 RLS and marginals. Many barnacles across carpace and flippers,Released,10/21/2002,NOWAY,NOWAY
605,2002_RE_0214,10/21/2002,researcher_17,site_54,ocean,net,fisher_97,site_120,species_2,site_80,KA460,None,NOWAY,37.4,33.5,NOWAY,Unknown,green and whitish-pink calcerous algae growth towards rear end of shell+ small mark on top of head+ small scar on nuchal+ small b's on flippers and neck.,Released,10/21/2002,NOWAY,NOWAY
606,2002_RE_0215,10/21/2002,researcher_17,site_54,ocean,net,fisher_973,site_54,species_2,site_116,KA442,None,NOWAY,40.3,37.2,NOWAY,Unknown,calcerous algae growth-especially rear end and some red algae+ 1 RMS is split+ 7 RMS has a chip+ 8 LMS has a chip+ 10 RMS has a hole+ 10 LMS has a small chip+ small hole 2 CS,Released,10/21/2002,NOWAY,NOWAY
607,2002_RE_0216,10/22/2002,researcher_17,site_13,ocean,net,fisher_103,site_120,species_2,site_116,KA467,None,NOWAY,37.4,36.3,NOWAY,Unknown,very little red algae over rear marginals,Released,10/22/2002,NOWAY,NOWAY
608,2002_RE_0217,10/22/2002,researcher_9,site_122,ocean,net,fisher_1070,site_118,species_2,site_80,KA475,None,NOWAY,54.4,48.6,NOWAY,Unknown,small chip between 8-9 RMS+ large chip on the R supra.+ whitish-pink calcerous algae slightly covering the shell+ small b's on the rear flippers and around the neck.,Released,10/22/2002,NOWAY,NOWAY
609,2002_RE_0218,10/22/2002,researcher_9,site_54,ocean,net,fisher_973,site_120,species_1,site_116,KA466,None,NOWAY,44,43.2,NOWAY,Unknown,clean shell,Released,10/22/2002,NOWAY,NOWAY
610,2002_RE_0219,10/24/2002,researcher_9,site_33,creek,net,fisher_1112,site_8,species_1,site_116,KA468,None,NOWAY,40.5,39.6,NOWAY,Unknown,bad scarring (superficial) on left side of turtle from 2 LLS/2 CS - downwards+ 10 + 11 LMS and bottom part of 5 CS and 4 LLS is mising+ all LMS from 2 CS down are chipped and worn+ 9-10 RMS is chipped. Looks like boat propellor damage,Released,10/24/2002,NOWAY,NOWAY
611,2002_RE_0220,10/25/2002,researcher_17,site_33,creek,net,fisher_1373,site_58,species_1,site_116,KE0733,None,NOWAY,51,50.5,NOWAY,Unknown,1 small b 5 CS,Released,10/25/2002,NOWAY,NOWAY
612,2002_RE_0221,10/27/2002,researcher_17,site_33,creek,net,fisher_694,site_58,species_1,site_80,NotTagged_0124,None,NOWAY,32.2,28.8,NOWAY,Unknown,sparsely covered in thick algae+ very inactive+ small superficial damage right prefrontal and top left on head+ some red algae under neck+ not emaciated+ small chip at end of LFF- Swam away very weakly and slowly. Had difficulty diving down (probably sic,Released,10/27/2002,NOWAY,NOWAY
613,2002_RE_0222,10/27/2002,researcher_17,site_120,ocean,net,fisher_994,site_120,species_2,not_recorded,KA470,None,NOWAY,39,36.5,NOWAY,Unknown,red/green + whitish calcerous algae covering shell+ small b's on all flippers,NOWAY,NOWAY,NOWAY,NOWAY
614,2002_RE_0223,10/27/2002,researcher_9,site_53,creek,net,fisher_977,site_110,species_1,site_80,KA469,None,NOWAY,39.2,38.1,NOWAY,Unknown,2 CS has 2 scars into shell,Released,10/27/2002,NOWAY,NOWAY
615,2002_RE_0224,10/29/2002,researcher_14,site_33,creek,net,fisher_862,site_8,species_1,site_80,KA471,None,NOWAY,41.5,40.1,NOWAY,Unknown,most of 7 and part of 8 LMS is missing+ probably old shark attack+ several old b scars on 1 CS+ some flaking off of 4 L + RLS's+ some small b's on flippers+ right rear flipper has small notch+ some pinkish-white calcerous algae growth over shell,Released,10/29/2002,NOWAY,NOWAY
616,2002_RE_0225,10/29/2002,researcher_14,site_53,creek,net,fisher_109,site_58,species_1,site_80,KA472,None,NOWAY,42.5,40.3,NOWAY,Unknown,2 CS has 1 b and old b scars+ between 4 RLS + 5 CS has large b+ 2 small b's on 11 LMS+ 2 small b's on left supra.- all b's killed+ small notch between 10-11 RMS+ old b scar on 2 LLS+ left rear flipper has a notch+ right rear flipper also has a notch+ 4 LL,Released,10/29/2002,NOWAY,NOWAY
617,2002_RE_0226,10/30/2002,researcher_18,site_53,creek,net,fisher_56,site_12,species_1,site_80,KA474,None,NOWAY,39.3,38.1,NOWAY,Unknown,very beautiful shell+ 9 RMS has a small indentation+ 11 RMS has a small chip+ 5 CS has what appears to be an old b scar+ 4 RLS has some flaking+ both front flippers have slightly jagged edges+ right rear flipper has a notch,Released,10/30/2002,NOWAY,NOWAY
618,2002_RE_0227,10/30/2002,researcher_18,site_53,creek,net,fisher_87,site_12,species_1,site_80,KA473,None,NOWAY,40.7,39.8,NOWAY,Unknown,1 CS has a lump+ 6-8 RMS has very small chips,Released,10/30/2002,NOWAY,NOWAY
619,2002_RE_0228,11/1/2002,researcher_18,site_33,creek,net,fisher_362,site_110,species_1,site_80,KA477,None,NOWAY,44.4,41.5,NOWAY,Unknown,beautiful shell+ small hump towards rear-end of 5 CS's+ very small b's on flippers.,Released,11/1/2002,NOWAY,NOWAY
620,2002_RE_0229,10/30/2002,researcher_18,site_33,creek,net,fisher_150,site_8,species_1,site_87,KA476,None,NOWAY,40.4,38.8,NOWAY,Unknown,B's: 2- 3 CS+ 1- 4RLS+ 1 (small)- 5 CS+ 1 (small) 2 LLS. Old b scar 9 LMS and between 11 RMS + right supra. RRF has notch out of it.,Released,11/1/2002,NOWAY,NOWAY

In [340]:
dirty_data.head(621)

,Rescue_ID,Date_Caught,Researcher,CaptureSite,ForagingGround,CaptureMethod,Fisher,LandingSite,Species,ReleaseSite,Tag_1,Tag_2,Lost_Tags,CCL_cm,CCW_cm,Weight_Kg,Sex,TurtleCharacteristics,Status,Date_Release,Release_Admiss_Notes,SpecialRemarks
0,1998_RE_0001,4/14/1998,researcher_12,site_110,creek,net,fisher_619,site_58,species_1,site_80,Missing data,None,NaN,63.50,58.50,NaN,Unknown,NaN,Released,4/14/1998,NaN,NaN
1,1998_RE_0002,7/7/1998,researcher_4,not_recorded,ocean,longline,fisher_522,site_22,species_1,not_recorded,NotTagged_0002,None,NaN,48.50,37.00,NaN,NaN,1B-1LLS,NaN,NaN,NaN,NaN
2,1998_RE_0003,8/3/1998,NaN,site_12,creek,net,fisher_1254,not_recorded,species_1,site_109,NotTagged_0003,None,NaN,44.50,33.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1998_RE_0004,8/7/1998,researcher_12,site_110,creek,net,fisher_360,not_recorded,species_2,site_113,NotTagged_0004,None,NaN,34.50,31.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1998_RE_0005,9/25/1998,researcher_17,not_recorded,creek,collected floater,fisher_865,site_8,species_3,site_109,NotTagged_0005,None,NaN,68.50,63.50,NaN,NaN,Bs on C+ old panga wounds,NaN,NaN,Found trapped in mangroves,NaN
5,1998_RE_0006,9/26/1998,researcher_17,not_recorded,creek,net,fisher_130,site_8,species_1,not_recorded,NotTagged_0006,None,NaN,34.00,30.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1998_RE_0007,10/20/1998,researcher_17,not_recorded,creek,net,fisher_619,site_8,species_1,not_recorded,NotTagged_0007,None,NaN,47.00,43.00,NaN,NaN,1B Lside,NaN,NaN,NaN,NaN
7,1998_RE_0008,11/7/1998,not_recorded,site_58,creek,net,fisher_217,site_8,species_1,not_recorded,NotTagged_0008,None,NaN,39.50,35.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1998_RE_0009,11/12/1998,not_recorded,not_recorded,creek,net,fisher_217,site_8,species_1,not_recorded,NotTagged_0009,None,NaN,46.00,43.00,NaN,NaN,9 Bs,NaN,NaN,NaN,NaN
9,1998_RE_0010,11/12/1998,not_recorded,not_recorded,creek,net,fisher_929,site_8,species_1,not_recorded,NotTagged_0010,None,NaN,38.00,35.50,NaN,NaN,LRF-piece missing,NaN,NaN,NaN,NaN
10,1998_RE_0011,11/18/1998,not_recorded,site_33,creek,net,fisher_529,not_recorded,species_1,not_recorded,NotTagged_0011,None,NaN,43.00,38.00,NaN,NaN,top centre of C-crack+ 3Bs on C,NaN,NaN,NaN,NaN
11,1998_RE_0012,11/19/1998,not_recorded,site_33,creek,net,fisher_867,not_recorded,species_1,not_recorded,NotTagged_0012,None,NaN,NaN,NaN,NaN,NaN,sm Bs on rear of C,NaN,NaN,NaN,NaN
12,1998_RE_0013,11/24/1998,researcher_11,site_113,ocean,net,fisher_90,not_recorded,species_1,site_110,NotTagged_0013,None,NaN,43.00,40.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1998_RE_0014,11/25/1998,researcher_17,site_33,creek,net,fisher_85,not_recorded,species_1,not_recorded,NotTagged_0014,None,NaN,46.00,43.00,NaN,NaN,Bs-2RLS & 4LLS,NaN,NaN,NaN,NaN
14,1998_RE_0015,12/5/1998,researcher_12,site_110,creek,net,fisher_861,not_recorded,species_1,not_recorded,NotTagged_0015,None,NaN,44.50,43.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1998_RE_0016,12/10/1998,researcher_6,not_recorded,creek,net,fisher_696,not_recorded,species_1,not_recorded,NotTagged_0016,None,NaN,43.00,38.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1999_RE_0001,3/8/1999,researcher_6,site_58,creek,net,fisher_929,not_recorded,species_1,site_116,NotTagged_0017,None,NaN,56.00,51.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1999_RE_0002,3/14/1999,researcher_17,site_58,creek,net,fisher_1182,not_recorded,species_1,site_110,NotTagged_0018,None,NaN,37.00,35.50,NaN,NaN,2Bs front scute& 2Bs-4LLS& 1B each rear flips,NaN,NaN,NaN,NaN
18,1999_RE_0003,3/16/1999,researcher_6,site_110,creek,net,fisher_751,not_recorded,species_1,site_110,NotTagged_0019,None,NaN,43.00,40.50,NaN,NaN,1B-head& 2Bs-1CS& Bs-1LLS & 2LLS& 2Bs-Lflip,NaN,NaN,NaN,NaN
19,1999_RE_0004,3/16/1999,researcher_17,site_12,creek,net,fisher_122,not_recorded,species_1,site_97,NotTagged_0020,None,NaN,42.00,38.00,NaN,NaN,many smBs,NaN,NaN,NaN,NaN
20,1999_RE_0005,3/24/1999,researcher_6,site_58,creek,net,fisher_1380,not_recorded,species_1,not_recorded,NotTagged_0021,None,NaN,48.00,39.50,NaN,NaN,1B-1LLS & 1RLS & 3LLS& 2Bs-5CS,NaN,NaN,NaN,NaN
21,1999_RE_0006,4/3/1999,researcher_17,site_110,creek,net,fisher_122,not_recorded,species_1,site_110,NotTagged_0022,None,NaN,38.00,37.00,NaN,NaN,Bs-2RLS& smBs-4CS& FRflip bent&,NaN,NaN,NaN,NaN
22,1999_RE_0007,4/28/1999,researcher_4,not_recorded,not_recorded,net,fisher_98,site_8,species_1,site_88,NotTagged_0023,None,NaN,56.00,43.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1999_RE_0008,5/3/1999,researcher_17,site_110,creek,net,fisher_122,site_8,species_1,site_110,NotTagged_0024,None,NaN,48.00,43.00,NaN,NaN,Bs on shell,NaN,NaN,NaN,NaN
24,1999_RE_0009,5/8/1999,researcher_17,site_58,creek,net,fisher_202,not_recorded,species_1,site_87,NotTagged_0025,None,NaN,43.00,40.50,NaN,NaN,B-Lside head& 5Bs on shell,NaN,NaN,NaN,NaN
25,1999_RE_0010,5/14/1999,researcher_4,not_recorded,not_recorded,net,fisher_619,site_8,species_1,site_90,NotTagged_0026,None,NaN,43.00,38.00,NaN,NaN,Bs-1CS & 2CS,NaN,NaN,NaN,NaN
26,1999_RE_0011,5/22/1999,researcher_17,site_58,creek,net,fisher_122,not_recorded,species_1,site_110,H381,None,NaN,40.50,40.50,NaN,NaN,Bs on shell& B-Lside of jaw,NaN,NaN,NaN,NaN
27,1999_RE_0012,5/24/1999,researcher_17,site_110,creek,not_recorded,fisher_153,not_recorded,species_2,site_110,NotTagged_0027,None,NaN,6.25,6.25,NaN,NaN,RRflip 2 chunks missing,NaN,NaN,NaN,NaN
28,1999_RE_0013,5/24/1999,researcher_17,site_58,creek,net,fisher_929,site_8,species_2,site_113,H382,None,NaN,28.00,28.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1999_RE_0014,6/24/1999,researcher_17,site_8,creek,net,fisher_266,not_recorded,species_1,site_113,H383,None,NaN,39.00,39.00,NaN,NaN,SmBs-2LLS& 3Bs Lprefrontal& 1B-each rear flip& 1B-9Lmarginal& 3B- rear marginal,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
591,2002_RE_0200,10/18/2002,researcher_17,site_15,creek,beached,fisher_374,site_15,species_1,site_80,NotTagged_0120,None,NaN,39.10,39.10,NaN,NaN,not tagged due to injuries+ turtle has been entangled in netting for a long period of time. RFF cut into near to shoulder-no bleeding+some scar tissue on surface+ LFF very swollen with bleeding near shoulder area+ blood has been cut off to the flipper+,NaN,NaN,NaN,NaN
592,2002_RE_0201,10/19/2002,researcher_17,site_53,creek,net,fisher_861,site_8,species_1,site_116,KA459,None,NaN,40.20,39.10,NaN,NaN,4 small b's 2 LLS+ 1 b 3 CS + 3 LLS+ 2 b's 5 CS+ 2 b's 11 LMS+ chip out of end of LFF and net damage,NaN,NaN,NaN,NaN
593,2002_RE_0202,10/19/2002,researcher_17,site_120,ocean,collected floater,fisher_1256,site_13,species_1,site_80,NotTagged_0121,None,NaN,40.00,38.00,NaN,NaN,has 5 lateral scutes to the left+ small b on 5 LLS+ turtle was too small to tag,NaN,NaN,NaN,NaN
594,2002_RE_0203,10/19/2002,researcher_17,site_119,ocean,net,fisher_67,site_118,species_1,site_80,KA461,None,NaN,43.30,40.00,NaN,NaN,piece missing from RRF,NaN,NaN,NaN,NaN
595,2002_RE_0204,10/19/2002,researcher_17,site_119,ocean,net,fisher_588,site_118,species_2,site_80,KA460,None,NaN,36.80,33.70,NaN,NaN,covered in white calcerous algae+ small b's on all flippers+ small scar on center of head,NaN,NaN,NaN,NaN
596,2002_RE_0205,10/19/2002,researcher_17,site_58,creek,net,fisher_1206,site_8,species_1,site_116,KE0843,None,NaN,41.50,40.90,NaN,NaN,1 small b LFF and some damage at flipper top edge near end+ 1 small b 1 CS,NaN,NaN,NaN,NaN
597,2002_RE_0206,10/19/2002,researcher_17,site_53,creek,net,fisher_769,site_12,species_1,site_116,KA458,None,NaN,47.40,45.00,NaN,NaN,1 b 4 LLS + 5 CS-killed+ chip between supra.+ 8 RMS + 2 RLS- superficial damage a small piece to scute+ 1 small b back and left side of head+ a few small b's to rear flippers+ RFF has a square end,NaN,NaN,NaN,NaN
598,2002_RE_0207,10/19/2002,researcher_17,site_120,ocean,collected floater,fisher_27,site_120,species_1,site_116,KA463,None,NaN,53.40,49.60,NaN,NaN,white calcerous growth on supra.,NaN,NaN,NaN,NaN
599,2002_RE_0208,10/19/2002,researcher_17,site_120,ocean,collected floater,fisher_27,site_120,species_1,site_116,KA462,None,NaN,54.30,53.20,NaN,NaN,chip between 11 RM and right supra.,NaN,NaN,NaN,NaN
600,2002_RE_0209,10/20/2002,researcher_17,site_6,ocean,collected floater,fisher_1309,site_120,species_1,site_80,NotTagged_0122,None,NaN,4.50,4.40,NaN,NaN,hatchling- pretty fresh out of nest was found by a young man who saw children playing with it at the beach when it was trying to go to the water on Blue Bay Beach. This hatchling and number 212 were caught together,NaN,NaN,NaN,NaN
601,2002_RE_0210,10/20/2002,researcher_17,site_6,ocean,collected floater,fisher_1309,site_120,species_1,site_80,NotTagged_0123,None,NaN,4.50,4.40,NaN,NaN,hatchling- pretty fresh out of nest was found by a young man who saw children playing with it at the beach when it was trying to go to the water on Blue Bay Beach. This hatchling and number 212 were caught together,NaN,NaN,NaN,NaN
602,2002_RE_0211,10/20/2002,researcher_6,site_58,creek,uzio,fisher_1118,site_58,species_1,site_116,KE0823,None,NaN,40.00,37.00,NaN,NaN,no descriptions taken,NaN,NaN,NaN,NaN
603,2002_RE_0212,10/20/2002,researcher_17,site_58,creek,net,fisher_333,site_8,species_1,site_80,KA464,None,NaN,44.20,43.00,NaN,NaN,b's caused problems in measuring+ large b's (38) all over shell- all were killed+ chip between 7-8 RMS+ large b on head-killed+ b's on underside-all killed+ flaking of scutes near edges,NaN,NaN,NaN,NaN
604,2002_RE_0213,10/21/2002,researcher_17,site_120,ocean,beached,fisher_1193,site_120,species_2,site_80,KA465,None,NaN,60.90,54.70,NaN,NaN,They said they found the turtle crawling parallel along the beach at Garoda at around 6:30 am. They watched it for a while and they decided to bring it to the office. 3 CS has large b; many b's at joint between 1 LLS and marginals + 1 RLS and marginals a,NaN,NaN,NaN,NaN
605,2002_RE_0214,10/21/2002,researcher_17,site_54,ocean,net,fisher_97,site_120,species_2,site_80,KA460,None,NaN,37.40,33.50,NaN,NaN,green and whitish-pink calcerous algae growth towards rear end of shell+ small mark on top of head+ small scar on nuchal+ small b's on flippers and neck.,NaN,NaN,NaN,NaN
606,2002_RE_0215,10/21/2002,researcher_17,site_54,ocean,net,fisher_973,site_54,species_2,site_116,KA442,None,NaN,40.30,37.20,NaN,NaN,calcerous algae growth-especially rear end and some red algae+ 1 RMS is split+ 7 RMS has a chip+ 8 LMS has a chip+ 10 RMS has a hole+ 10 LMS has a small chip+ small hole 2 CS,NaN,NaN,NaN,NaN
607,2002_RE_0216,10/22/2002,researcher_17,site_13,ocean,net,fisher_103,site_120,species_2,site_116,KA467,None,NaN,37.40,36.30,NaN,NaN,very little red algae over rear marginals,NaN,NaN,NaN,NaN
608,2002_RE_0217,10/22/2002,researcher_9,site_122,ocean,net,fisher_1070,site_118,species_2,site_80,KA475,None,NaN,54.40,48.60,NaN,NaN,small chip between 8-9 RMS+ large chip on the R supra.+ whitish-pink calcerous algae slightly covering the shell+ small b's on the rear flippers and around the neck.,NaN,NaN,NaN,NaN
609,2002_RE_0218,10/22/2002,researcher_9,site_54,ocean,net,fisher_973,site_120,species_1,site_116,KA466,None,NaN,44.00,43.20,NaN,NaN,clean shell,NaN,NaN,NaN,NaN
610,2002_RE_0219,10/24/2002,researcher_9,site_33,creek,net,fisher_1125,site_8,species_1,site_116,KA468,None,NaN,40.50,39.60,NaN,NaN,bad scarring (superficial) on left side of turtle from 2 LLS/2 CS - downwards+ 10 + 11 LMS and bottom part of 5 CS and 4 LLS is mising+ all LMS from 2 CS down are chipped and worn+ 9-10 RMS is chipped. Looks like boat propellor damage,NaN,NaN,NaN,NaN
611,2002_RE_0220,10/25/2002,researcher_17,site_33,creek,net,fisher_1373,site_58,species_1,site_116,KE0733,None,NaN,51.00,50.50,NaN,NaN,1 small b 5 CS,NaN,NaN,NaN,NaN
612,2002_RE_0221,10/27/2002,researcher_17,site_33,creek,net,fisher_694,site_58,species_1,site_80,NotTagged_0124,None,NaN,32.20,28.80,NaN,NaN,sparsely covered in thick algae+ very inactive+ small superficial damage right prefrontal and top left on head+ some red algae under neck+ not emaciated+ small chip at end of LFF- Swam away very weakly and slowly. Had difficulty diving down (probably sic,NaN,NaN,NaN,NaN
613,2002_RE_0222,10/27/2002,researcher_17,site_120,ocean,net,fisher_994,site_120,species_2,not_recorded,KA470,None,NaN,39.00,36.50,NaN,NaN,red/green + whitish calcerous algae covering shell+ small b's on all flippers,NaN,NaN,NaN,NaN
614,2002_RE_0223,10/27/2002,researcher_9,site_53,creek,net,fisher_1187,site_110,species_1,site_80,KA469,None,NaN,39.20,38.10,NaN,NaN,2 CS has 2 scars into shell,NaN,NaN,NaN,NaN
615,2002_RE_0224,10/29/2002,researcher_14,site_33,creek,net,fisher_862,site_8,species_1,site_80,KA471,None,NaN,41.50,40.10,NaN,NaN,most of 7 and part of 8 LMS is missing+ probably old shark attack+ several old b scars on 1 CS+ some flaking off of 4 L + RLS's+ some small b's on flippers+ right rear flipper has small notch+ some pinkish-white calcerous algae growth over shell,NaN,NaN,NaN,NaN
616,2002_RE_0225,10/29/2002,researcher_14,site_53,creek,net,fisher_109,site_58,species_1,site_80,KA472,None,NaN,42.50,40.30,NaN,NaN,2 CS has 1 b and old b scars+ between 4 RLS + 5 CS has large b+ 2 small b's on 11 LMS+ 2 small b's on left supra.- all b's killed+ small notch between 10-11 RMS+ old b scar on 2 LLS+ left rear flipper has a notch+ right rear flipper also has a notch+ 4 LL,NaN,NaN,NaN,NaN
617,2002_RE_0226,10/30/2002,researcher_18,site_53,creek,net,fisher_56,site_12,species_1,site_80,KA474,None,NaN,39.30,38.10,NaN,NaN,very beautiful shell+ 9 RMS has a small indentation+ 11 RMS has a small chip+ 5 CS has what appears to be an old b scar+ 4 RLS has some flaking+ both front flippers have slightly jagged edges+ right rear flipper has a notch,NaN,NaN,NaN,NaN
618,2002_RE_0227,10/30/2002,researcher_18,site_53,creek,net,fisher_87,site_12,species_1,site_80,KA473,None,NaN,40.70,39.80,NaN,NaN,1 CS has a lump+ 6-8 RMS has very small chips,NaN,NaN,NaN,NaN
619,2002_RE_0228,11/1/2002,researcher_18,site_33,creek,net,fisher_362,site_110,species_1,site_80,KA477,None,NaN,44.40,41.50,NaN,NaN,beautiful shell+ small hump towards rear-end of 5 CS's+ very small b's on flippers.,NaN,NaN,NaN,NaN
620,2002_RE_0229,11/1/2002,researcher_18,site_8,creek,net,fisher_150,site_8,species_1,site_87,KA476,None,NaN,40.40,38.80,NaN,NaN,B's: 2- 3 CS+ 1- 4RLS+ 1 (small)- 5 CS+ 1 (small) 2 LLS. Old b scar 9 LMS and between 11 RMS + right supra. RRF has notch out of it.,NaN,NaN,NaN,NaN

In [11]:
dirty_data.SpecialRemarks.value_counts()

NOWAY                                                                                                                                               4244
Fibropapillomatosis                                                                                                                                 22
NOTE (05/10/2017): tag KE1805 was lost between April and July 2007. Replaced with 3209, which was lost in Jan to April 2008. Latest tag is 3398.    15
NOTE (06/10/2017): Lost tags KE1839, KE1966 and 3264.                                                                                               7
NOTE (06/10/2017): tag KE1510 was deplyed on a hawksbill                                                                                            1
NOTE 06/10/2017): CCL too large compared to other measurements! CAUTION!                                                                            1
NOTE (06/10/2017): tag KE1510 was removed & replaced by 3525 on 10/06/2008..                                                                        1
NOTE (05/10/2017) tag 3231 lost between 10/05/2008-18/11/2008                                                                                       1
Name: SpecialRemarks, dtype: int64

## Put all wrong values in a dataframe

In [38]:
# for Tag_1
# pd.concat([df_wrong_Tag_1_KE, df_wrong_Tag_1_KEB_KE, df_wrong_Tag_1_KE_KEB, df_wrong_Tag_1_KE_clean_KEB, df_wrong_Tag_1_KE_clean_noLetters,
#           df_wrong_Tag_1_basedon_Date, df_wrong_Tag_1_in_Lost_Tag, df_wrong_tag_1_multi_species, df_wrong_Tag_1_no_leter]).to_csv('wrong_Tag_1.csv',index=False)
# # for species
# pd.concat([df_wrong_species_multispecies]).to_csv('wrong_Species.csv',index=False)
# pd.concat([df_wrong_Lost_Tag_in_Tag_1, df_wrong_Lost_Tag_nan]).to_csv('wrong_Lost_Tag.csv',index=False)
pd.concat([df_wrong_Lost_Tag_nan]).to_csv('wrong_Lost_Tag2.csv',index=False)

In [61]:
# pd.concat([df_wrong_Tag_2]).to_csv('wrong_Tag_2.csv',index=False)