In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_colwidth', -1)
pd.set_option('display.colheader_justify', 'left')
submission_example = pd.read_csv('submission_example.csv')
test_data = pd.read_csv('test_data.csv')

In [4]:
sub_example = submission_example.copy()

In [5]:
# Split the data set 
# sub_example = sub_example.ID.str.split('x', expand=True, n=1)

In [6]:
sub_example['Rescue_ID'] = sub_example.ID.str.split('x', expand=True, n=1)[0]
sub_example['cols'] = sub_example.ID.str.split('x', expand=True, n=1)[1]

In [7]:
# Assign 0 to values with Date_caught 
sub_example.loc[sub_example['cols'] == ' Date_Caught', ['error']] = 0.0

In [8]:
# Assign 0 to expenditure,Tag_3 and  PVCNumber
sub_example.loc[sub_example['cols'].isin([' Expenditure',' PCVNumber', ' Tag_3']), ['error']] = 0.0

Working on the Tags now

In [9]:
sub_example

,ID,error,Rescue_ID,cols
0,2011_RE_0001 x Date_Caught,0.0,2011_RE_0001,Date_Caught
1,2011_RE_0001 x Researcher,1.0,2011_RE_0001,Researcher
2,2011_RE_0001 x CaptureSite,1.0,2011_RE_0001,CaptureSite
3,2011_RE_0001 x ForagingGround,0.0,2011_RE_0001,ForagingGround
4,2011_RE_0001 x CaptureMethod,1.0,2011_RE_0001,CaptureMethod
5,2011_RE_0001 x Fisher,1.0,2011_RE_0001,Fisher
6,2011_RE_0001 x LandingSite,1.0,2011_RE_0001,LandingSite
7,2011_RE_0001 x Species,0.0,2011_RE_0001,Species
8,2011_RE_0001 x ReleaseSite,0.0,2011_RE_0001,ReleaseSite
9,2011_RE_0001 x Tag_1,0.0,2011_RE_0001,Tag_1
10,2011_RE_0001 x Tag_2,0.0,2011_RE_0001,Tag_2
11,2011_RE_0001 x Tag_3,0.0,2011_RE_0001,Tag_3
12,2011_RE_0001 x Lost_Tags,1.0,2011_RE_0001,Lost_Tags
13,2011_RE_0001 x T_Number,1.0,2011_RE_0001,T_Number
14,2011_RE_0001 x CCL_cm,0.0,2011_RE_0001,CCL_cm
15,2011_RE_0001 x CCW_cm,1.0,2011_RE_0001,CCW_cm
16,2011_RE_0001 x Weight_Kg,0.0,2011_RE_0001,Weight_Kg
17,2011_RE_0001 x Sex,0.0,2011_RE_0001,Sex
18,2011_RE_0001 x TurtleCharacteristics,1.0,2011_RE_0001,TurtleCharacteristics
19,2011_RE_0001 x Status,0.0,2011_RE_0001,Status
20,2011_RE_0001 x Date_Release,1.0,2011_RE_0001,Date_Release
21,2011_RE_0001 x Release_Admiss_Notes,0.0,2011_RE_0001,Release_Admiss_Notes
22,2011_RE_0001 x SpecialRemarks,1.0,2011_RE_0001,SpecialRemarks
23,2011_RE_0001 x PCVNumber,0.0,2011_RE_0001,PCVNumber
24,2011_RE_0001 x Expenditure,0.0,2011_RE_0001,Expenditure
25,2011_RE_0002 x Date_Caught,0.0,2011_RE_0002,Date_Caught
26,2011_RE_0002 x Researcher,0.0,2011_RE_0002,Researcher
27,2011_RE_0002 x CaptureSite,1.0,2011_RE_0002,CaptureSite
28,2011_RE_0002 x ForagingGround,1.0,2011_RE_0002,ForagingGround
29,2011_RE_0002 x CaptureMethod,0.0,2011_RE_0002,CaptureMethod
...,...,...,...,...
34020,2011_RE_1364 x Date_Release,NaN,2011_RE_1364,Date_Release
34021,2011_RE_1364 x Release_Admiss_Notes,NaN,2011_RE_1364,Release_Admiss_Notes
34022,2011_RE_1364 x SpecialRemarks,NaN,2011_RE_1364,SpecialRemarks
34023,2011_RE_1364 x PCVNumber,0.0,2011_RE_1364,PCVNumber
34024,2011_RE_1364 x Expenditure,0.0,2011_RE_1364,Expenditure
34025,2011_RE_1365 x Date_Caught,0.0,2011_RE_1365,Date_Caught
34026,2011_RE_1365 x Researcher,NaN,2011_RE_1365,Researcher
34027,2011_RE_1365 x CaptureSite,NaN,2011_RE_1365,CaptureSite
34028,2011_RE_1365 x ForagingGround,NaN,2011_RE_1365,ForagingGround
34029,2011_RE_1365 x CaptureMethod,NaN,2011_RE_1365,CaptureMethod
34030,2011_RE_1365 x Fisher,NaN,2011_RE_1365,Fisher
34031,2011_RE_1365 x LandingSite,NaN,2011_RE_1365,LandingSite
34032,2011_RE_1365 x Species,NaN,2011_RE_1365,Species
34033,2011_RE_1365 x ReleaseSite,NaN,2011_RE_1365,ReleaseSite
34034,2011_RE_1365 x Tag_1,NaN,2011_RE_1365,Tag_1
34035,2011_RE_1365 x Tag_2,NaN,2011_RE_1365,Tag_2
34036,2011_RE_1365 x Tag_3,0.0,2011_RE_1365,Tag_3
34037,2011_RE_1365 x Lost_Tags,NaN,2011_RE_1365,Lost_Tags
34038,2011_RE_1365 x T_Number,NaN,2011_RE_1365,T_Number
34039,2011_RE_1365 x CCL_cm,NaN,2011_RE_1365,CCL_cm
34040,2011_RE_1365 x CCW_cm,NaN,2011_RE_1365,CCW_cm
34041,2011_RE_1365 x Weight_Kg,NaN,2011_RE_1365,Weight_Kg
34042,2011_RE_1365 x Sex,NaN,2011_RE_1365,Sex
34043,2011_RE_1365 x TurtleCharacteristics,NaN,2011_RE_1365,TurtleCharacteristics
34044,2011_RE_1365 x Status,NaN,2011_RE_1365,Status
34045,2011_RE_1365 x Date_Release,NaN,2011_RE_1365,Date_Release
34046,2011_RE_1365 x Release_Admiss_Notes,NaN,2011_RE_1365,Release_Admiss_Notes
34047,2011_RE_1365 x SpecialRemarks,NaN,2011_RE_1365,SpecialRemarks
34048,2011_RE_1365 x PCVNumber,0.0,2011_RE_1365,PCVNumber
34049,2011_RE_1365 x Expenditure,0.0,2011_RE_1365,Expenditure

In [10]:
# Add new cols to test data
# Split tag_1 into type and number
test_data['Tag_type'] = test_data.Tag_1.str.split('(\d+)', expand=True)[0]
test_data['Tag_num'] = test_data.Tag_1.str.split('(\d+)', expand=True)[1]

In [11]:
test_data.Tag_type.value_counts()

KE            1261
              55
KEB           23
NotTagged_    13
KES           6
CC            2
Ke            1
kE            1
Name: Tag_type, dtype: int64

In [12]:
# Get rescue_id of wrong tag_1 type
Rescue_Id_with_wrong_tag_type = test_data.loc[test_data['Tag_type'].isin(['kE','KES', 'Ke'])]['Rescue_ID'].tolist()

In [13]:
# remove white spaces in sub_example
sub_example.Rescue_ID= sub_example.Rescue_ID.str.strip()
sub_example.cols= sub_example.cols.str.strip()

In [14]:
sub_example.error = (0.0)

In [15]:
# Give  the above rescue_id values 1
sub_example.loc[sub_example['Rescue_ID'].isin(Rescue_Id_with_wrong_tag_type) &(sub_example.cols == 'Tag_1'), 'error'] = 1.0

In [16]:
#wrong values from the panother notebook after reading its csv
wrong_tag_1 = pd.read_csv('wrong_Tag_1.csv').Rescue_ID.tolist()
wrong_species = pd.read_csv('wrong_species.csv').Rescue_ID.tolist()
wrong_tag_2 = pd.read_csv('wrong_Tag_2.csv').Rescue_ID.tolist()
wrong_Lost_tag = pd.read_csv('wrong_Lost_Tag2.csv').Rescue_ID.tolist()

In [17]:
#Give the above values 1 
sub_example.loc[sub_example['Rescue_ID'].isin(wrong_tag_1) &(sub_example.cols == 'Tag_1'), 'error'] = 1.0
sub_example.loc[sub_example['Rescue_ID'].isin(wrong_species) &(sub_example.cols == 'Species'), 'error'] = 1.0
sub_example.loc[sub_example['Rescue_ID'].isin(wrong_tag_2) &(sub_example.cols == 'Tag_2'), 'error'] = 1.0
sub_example.loc[sub_example['Rescue_ID'].isin(wrong_Lost_tag) &(sub_example.cols == 'Lost_Tags'), 'error'] = 1.0

Fill  NAN with 0.0 .   
i want to test run submission

In [37]:
sub_example[['ID', 'error']]

      ID                                     error
0      2011_RE_0001 x Date_Caught            0.0
1      2011_RE_0001 x Researcher             0.0
2      2011_RE_0001 x CaptureSite            0.0
3      2011_RE_0001 x ForagingGround         0.0
4      2011_RE_0001 x CaptureMethod          0.0
5      2011_RE_0001 x Fisher                 0.0
6      2011_RE_0001 x LandingSite            0.0
7      2011_RE_0001 x Species                0.0
8      2011_RE_0001 x ReleaseSite            0.0
9      2011_RE_0001 x Tag_1                  0.0
10     2011_RE_0001 x Tag_2                  0.0
11     2011_RE_0001 x Tag_3                  0.0
12     2011_RE_0001 x Lost_Tags              0.0
13     2011_RE_0001 x T_Number               0.0
14     2011_RE_0001 x CCL_cm                 0.0
15     2011_RE_0001 x CCW_cm                 0.0
16     2011_RE_0001 x Weight_Kg              0.0
17     2011_RE_0001 x Sex                    0.0
18     2011_RE_0001 x TurtleCharacteristics  0.0
19     2011_RE_0001 x Status                 0.0
20     2011_RE_0001 x Date_Release           0.0
21     2011_RE_0001 x Release_Admiss_Notes   0.0
22     2011_RE_0001 x SpecialRemarks         0.0
23     2011_RE_0001 x PCVNumber              0.0
24     2011_RE_0001 x Expenditure            0.0
25     2011_RE_0002 x Date_Caught            0.0
26     2011_RE_0002 x Researcher             0.0
27     2011_RE_0002 x CaptureSite            0.0
28     2011_RE_0002 x ForagingGround         0.0
29     2011_RE_0002 x CaptureMethod          0.0
...                             ...          ...
34020  2011_RE_1364 x Date_Release           0.0
34021  2011_RE_1364 x Release_Admiss_Notes   0.0
34022  2011_RE_1364 x SpecialRemarks         0.0
34023  2011_RE_1364 x PCVNumber              0.0
34024  2011_RE_1364 x Expenditure            0.0
34025  2011_RE_1365 x Date_Caught            0.0
34026  2011_RE_1365 x Researcher             0.0
34027  2011_RE_1365 x CaptureSite            0.0
34028  2011_RE_1365 x ForagingGround         0.0
34029  2011_RE_1365 x CaptureMethod          0.0
34030  2011_RE_1365 x Fisher                 0.0
34031  2011_RE_1365 x LandingSite            0.0
34032  2011_RE_1365 x Species                0.0
34033  2011_RE_1365 x ReleaseSite            0.0
34034  2011_RE_1365 x Tag_1                  0.0
34035  2011_RE_1365 x Tag_2                  0.0
34036  2011_RE_1365 x Tag_3                  0.0
34037  2011_RE_1365 x Lost_Tags              0.0
34038  2011_RE_1365 x T_Number               0.0
34039  2011_RE_1365 x CCL_cm                 0.0
34040  2011_RE_1365 x CCW_cm                 0.0
34041  2011_RE_1365 x Weight_Kg              0.0
34042  2011_RE_1365 x Sex                    0.0
34043  2011_RE_1365 x TurtleCharacteristics  0.0
34044  2011_RE_1365 x Status                 0.0
34045  2011_RE_1365 x Date_Release           0.0
34046  2011_RE_1365 x Release_Admiss_Notes   0.0
34047  2011_RE_1365 x SpecialRemarks         0.0
34048  2011_RE_1365 x PCVNumber              0.0
34049  2011_RE_1365 x Expenditure            0.0

[34050 rows x 2 columns]

In [32]:
submission_example

      ID                                     error
0      2011_RE_0001 x Date_Caught            0.0
1      2011_RE_0001 x Researcher             1.0
2      2011_RE_0001 x CaptureSite            1.0
3      2011_RE_0001 x ForagingGround         0.0
4      2011_RE_0001 x CaptureMethod          1.0
5      2011_RE_0001 x Fisher                 1.0
6      2011_RE_0001 x LandingSite            1.0
7      2011_RE_0001 x Species                0.0
8      2011_RE_0001 x ReleaseSite            0.0
9      2011_RE_0001 x Tag_1                  0.0
10     2011_RE_0001 x Tag_2                  0.0
11     2011_RE_0001 x Tag_3                  0.0
12     2011_RE_0001 x Lost_Tags              1.0
13     2011_RE_0001 x T_Number               1.0
14     2011_RE_0001 x CCL_cm                 0.0
15     2011_RE_0001 x CCW_cm                 1.0
16     2011_RE_0001 x Weight_Kg              0.0
17     2011_RE_0001 x Sex                    0.0
18     2011_RE_0001 x TurtleCharacteristics  1.0
19     2011_RE_0001 x Status                 0.0
20     2011_RE_0001 x Date_Release           1.0
21     2011_RE_0001 x Release_Admiss_Notes   0.0
22     2011_RE_0001 x SpecialRemarks         1.0
23     2011_RE_0001 x PCVNumber              0.0
24     2011_RE_0001 x Expenditure            1.0
25     2011_RE_0002 x Date_Caught            0.0
26     2011_RE_0002 x Researcher             0.0
27     2011_RE_0002 x CaptureSite            1.0
28     2011_RE_0002 x ForagingGround         1.0
29     2011_RE_0002 x CaptureMethod          0.0
...                             ...          ...
34020  2011_RE_1364 x Date_Release          NaN
34021  2011_RE_1364 x Release_Admiss_Notes  NaN
34022  2011_RE_1364 x SpecialRemarks        NaN
34023  2011_RE_1364 x PCVNumber             NaN
34024  2011_RE_1364 x Expenditure           NaN
34025  2011_RE_1365 x Date_Caught           NaN
34026  2011_RE_1365 x Researcher            NaN
34027  2011_RE_1365 x CaptureSite           NaN
34028  2011_RE_1365 x ForagingGround        NaN
34029  2011_RE_1365 x CaptureMethod         NaN
34030  2011_RE_1365 x Fisher                NaN
34031  2011_RE_1365 x LandingSite           NaN
34032  2011_RE_1365 x Species               NaN
34033  2011_RE_1365 x ReleaseSite           NaN
34034  2011_RE_1365 x Tag_1                 NaN
34035  2011_RE_1365 x Tag_2                 NaN
34036  2011_RE_1365 x Tag_3                 NaN
34037  2011_RE_1365 x Lost_Tags             NaN
34038  2011_RE_1365 x T_Number              NaN
34039  2011_RE_1365 x CCL_cm                NaN
34040  2011_RE_1365 x CCW_cm                NaN
34041  2011_RE_1365 x Weight_Kg             NaN
34042  2011_RE_1365 x Sex                   NaN
34043  2011_RE_1365 x TurtleCharacteristics NaN
34044  2011_RE_1365 x Status                NaN
34045  2011_RE_1365 x Date_Release          NaN
34046  2011_RE_1365 x Release_Admiss_Notes  NaN
34047  2011_RE_1365 x SpecialRemarks        NaN
34048  2011_RE_1365 x PCVNumber             NaN
34049  2011_RE_1365 x Expenditure           NaN

[34050 rows x 2 columns]

In [18]:
sub_example[['ID', 'error']].to_csv('Submission_with_species_Tag_1_2_Lost_Tag2.csv', index=False)